import { classAccess, classByCode } from "@/lib/live-classrooms";
import { createId, getDatabase, getSessionUser } from "@/lib/auth";
import { createClassParticipant, createClassProviderRoom } from "@/lib/live-class-realtimekit";

export async function POST(request:Request,{params}:{params:Promise<{code:string}>}){
  try{
    const{code}=await params,room=await classByCode(code);if(!room)return Response.json({error:"Class not found"},{status:404});const body=await request.json().catch(()=>({}))as{displayName?:string;identity?:string;publish?:boolean;start?:boolean},user=await getSessionUser(request),access=await classAccess(room,user);if(!access.allowed)return Response.json({error:"Private class invitation required"},{status:403});const db=getDatabase(),now=Math.floor(Date.now()/1000),identity=String(body.identity||crypto.randomUUID()).slice(0,100),displayName=String(body.displayName||user?.displayName||"Guest").trim().slice(0,80)||"Guest";let providerMeetingId=room.providerMeetingId;if((body.start||body.publish)&&access.manager&&!room.streamActive){const created=await createClassProviderRoom(room.title);providerMeetingId=created.id;await db.prepare("UPDATE live_class_rooms SET provider_meeting_id=?,stream_active=1,mute_all=CASE WHEN class_type='private' THEN 0 ELSE 1 END,updated_at=? WHERE id=?").bind(providerMeetingId,now,room.id).run();}if(!providerMeetingId||(!room.streamActive&&!body.start&&!body.publish))return Response.json({error:"STREAM_NOT_ACTIVE"},{status:409});let role:"viewer"|"member"|"host"="viewer";if(access.manager)role="host";else if(body.publish){const fresh=await classByCode(code);if(fresh?.classType!=="private"&&fresh?.muteAll) return Response.json({error:"WAITING_FOR_MANAGER"},{status:403});const count=await db.prepare("SELECT COUNT(*) AS count FROM live_class_media_presence WHERE room_id=? AND active=1 AND (mic_on=1 OR camera_on=1) AND last_seen_at>?").bind(room.id,now-45).first<{count:number}>();if(Number(count?.count||0)>=8)return Response.json({error:"PUBLISHER_LIMIT"},{status:409});role="member";}const participant=await createClassParticipant(providerMeetingId,identity,displayName,role);await db.prepare(`INSERT INTO live_class_media_presence(id,room_id,identity,user_id,display_name,is_member,mic_on,camera_on,active,last_seen_at) VALUES(?,?,?,?,?,?,0,0,1,?) ON CONFLICT(room_id,identity) DO UPDATE SET user_id=excluded.user_id,display_name=excluded.display_name,is_member=excluded.is_member,active=1,last_seen_at=excluded.last_seen_at`).bind(createId(),room.id,identity,user?.id||null,displayName,user?1:0,now).run();return Response.json({authToken:participant.token,identity,role,meetingId:providerMeetingId,streamingMode:room.streamingMode,muteAll:room.classType==="private"?false:Boolean(room.muteAll),manager:access.manager});
  }catch(issue){
    const message=issue instanceof Error?issue.message:"REALTIMEKIT_REQUEST_FAILED";
    console.error("Classroom RealtimeKit join failed",message);
    return Response.json({error:message},{status:502});
  }
}
