import Link from "next/link";
import { notFound } from "next/navigation";
import { CollegeManageForm } from "../../../../components/CollegeAdminForms";
import { CollegeDepartmentManager } from "../../../../components/CollegeDepartmentManager";
import { SiteFooter } from "../../../../components/SiteFooter";
import { SiteHeader } from "../../../../components/SiteHeader";
import { requestUser } from "../../../../lib/request-user";
import { collegeDepartments, supervisorLicense } from "../../../../lib/college-departments";
import { activeCollegeTags, canManageCollege, collegeByCode, collegeTags } from "../../../../lib/smartlingo-colleges";

export const dynamic="force-dynamic";
export default async function CollegePage({params}:{params:Promise<{lang:string;code:string}>}){const{lang,code}=await params;if(lang!=="en"&&lang!=="zh"&&lang!=="es"&&lang!=="ja"&&lang!=="ko"&&lang!=="fr"&&lang!=="de"&&lang!=="ru"&&lang!=="it"&&lang!=="pt"&&lang!=="ar"&&lang!=="hi")notFound();const college=await collegeByCode(code);if(!college||college.status!=="active")notFound();const zh=lang==="zh",user=await requestUser(),canManage=canManageCollege(college,user),[departments,tags,license]=await Promise.all([collegeDepartments(college.id),activeCollegeTags(),user?supervisorLicense(user.id):Promise.resolve(null)]);const title=zh?college.titleZh:college.titleEn,description=zh?college.descriptionZh:college.descriptionEn;return <main className="college-detail-page" data-layout-page="college-detail"><SiteHeader lang={lang as any}/><section className="college-detail-hero" data-layout-fill="college-detail-hero"><p className="section-kicker">COLLEGE · {college.code}</p><h1>{title}</h1><p>{description}</p><div className="college-detail-meta"><span>{zh?"招生学院":"Enrollment college"}</span><span>{zh?"院长":"College owner"} · {college.ownerName}</span>{collegeTags(college).map(tag=><span key={tag.id}>{zh?tag.nameZh:tag.nameEn}</span>)}</div><div className="college-directory-actions"><Link className="secondary-button" href={`/${lang}/colleges`}>{zh?"浏览学院":"Browse colleges"}</Link></div></section><section className="college-course-table"><div><p className="section-kicker">LANGUAGE DEPARTMENTS</p><h2>{zh?"按语言部门学习":"Learn through a language department"}</h2><p>{zh?"每个部门提供管理员定价的课程、四项免费产品与专属 Webinar。":"Each department includes admin-priced courses, four free products, and its own Webinar."}</p></div><div className="college-course-list">{departments.map(department=><article key={department.id}><span>{department.sourceLanguage.toUpperCase()} → {department.targetLanguage.toUpperCase()}</span><div><h3>{zh?department.titleZh:department.titleEn}</h3><p>{department.courseCount} {zh?"门课程 · Webinar":"courses · Webinar"}</p></div><Link href={`/${lang}/college/${code}/departments/${department.id}`}>{zh?"进入部门":"Enter department"} →</Link></article>)}</div></section>{canManage?<section className="college-manager-section"><p className="section-kicker">COLLEGE MANAGEMENT</p><h2>{zh?"学院资料":"College profile"}</h2><CollegeManageForm lang={lang as any} college={college} tags={tags}/><CollegeDepartmentManager lang={lang} collegeCode={code} departments={departments} quota={user?.email.toLowerCase()==="bingliu@cybeye.com"?null:license?{max:license.maxDepartments,used:license.departmentCount}:null}/></section>:null}<SiteFooter lang={lang as any}/></main>;}
