import Link from "next/link";
import { notFound } from "next/navigation";
import { CollegeManageForm } from "../../../../components/CollegeAdminForms";
import { SiteFooter } from "../../../../components/SiteFooter";
import { SiteHeader } from "../../../../components/SiteHeader";
import { requestUser } from "../../../../lib/request-user";
import { activeCollegeTags, availableCollegeCourses, canManageCollege, collegeByCode, collegeCourses, collegeTags } from "../../../../lib/smartlingo-colleges";

export const dynamic="force-dynamic";
export default async function CollegePage({params}:{params:Promise<{lang:string;code:string}>}){const{lang,code}=await params;if(lang!=="en"&&lang!=="zh"&&lang!=="es"&&lang!=="ja"&&lang!=="ko"&&lang!=="fr"&&lang!=="de"&&lang!=="ru"&&lang!=="it"&&lang!=="pt"&&lang!=="ar"&&lang!=="hi")notFound();const college=await collegeByCode(code);if(!college||college.status!=="active")notFound();const zh=lang==="zh",user=await requestUser(),canManage=canManageCollege(college,user),[courses,tags,available]=await Promise.all([collegeCourses(college.id),activeCollegeTags(),canManage?availableCollegeCourses(college.id):Promise.resolve([])]);const title=zh?college.titleZh:college.titleEn,description=zh?college.descriptionZh:college.descriptionEn,access=college.accessType==="public"?(zh?"公开学院":"Open college"):college.accessType==="trial"?(zh?"推荐学院":"Referred college"):(zh?"专属学院":"Private college"),price=college.tuitionCents?new Intl.NumberFormat(lang,{style:"currency",currency:college.currency}).format(college.tuitionCents/100):(zh?"免费":"Free");return <main className="college-detail-page" data-layout-page="college-detail"><SiteHeader lang={lang}/><section className="college-detail-hero" data-layout-fill="college-detail-hero"><p className="section-kicker">COLLEGE · {college.code}</p><h1>{title}</h1><p>{description}</p><div className="college-detail-meta"><span>{access}</span><span>{price}</span><span>{zh?"院长":"College owner"} · {college.ownerName}</span>{collegeTags(college).map(tag=><span key={tag.id}>{zh?tag.nameZh:tag.nameEn}</span>)}</div><div className="college-directory-actions"><Link className="primary-button" href={`/${lang}/classes/${college.introductoryCourseId}`}>{zh?"加入导论课程":"Join introductory course"} →</Link><Link className="secondary-button" href={`/${lang}/colleges`}>{zh?"浏览学院":"Browse colleges"}</Link></div></section><section className="college-course-table"><div><p className="section-kicker">COURSE TABLE</p><h2>{zh?"学院课程表":"College course table"}</h2><p>{zh?"先从导论课程开始，再按每门课程自己的价格与访问设置加入。":"Start with the introduction, then join each course under its own price and access settings."}</p></div><div className="college-course-list">{courses.map(course=><article key={course.id}><span>{course.kind==="introductory"?(zh?"导论":"INTRO"):zh?"课程":"COURSE"}</span><div><h3>{course.title}</h3><p>{course.targetLanguage.toUpperCase()} · {course.level} · {course.priceCents?new Intl.NumberFormat(lang,{style:"currency",currency:course.currency}).format(course.priceCents/100):(zh?"免费":"Free")}</p></div><Link href={`/${lang}/classes/${course.id}`}>{zh?"查看课程":"View course"} →</Link></article>)}</div></section>{canManage?<section className="college-manager-section"><p className="section-kicker">COLLEGE MANAGEMENT</p><h2>{zh?"学院资料与课程表":"College profile & course table"}</h2><CollegeManageForm lang={lang} college={college} tags={tags} courses={available}/></section>:null}<SiteFooter lang={lang}/></main>;}
