CREATE TABLE IF NOT EXISTS crypto_payment_settings (
 id TEXT PRIMARY KEY NOT NULL,label TEXT NOT NULL,chain_type TEXT NOT NULL DEFAULT 'evm' CHECK(chain_type='evm'),chain_name TEXT NOT NULL,chain_id INTEGER NOT NULL CHECK(chain_id>0),token_symbol TEXT NOT NULL,token_contract TEXT NOT NULL,token_decimals INTEGER NOT NULL CHECK(token_decimals BETWEEN 0 AND 18),receiver_wallet TEXT NOT NULL,
 basic_amount_cents INTEGER NOT NULL DEFAULT 2000 CHECK(basic_amount_cents=2000),intermediate_amount_cents INTEGER NOT NULL DEFAULT 10000 CHECK(intermediate_amount_cents=10000),advanced_amount_cents INTEGER NOT NULL DEFAULT 30000 CHECK(advanced_amount_cents=30000),basic_token_amount TEXT NOT NULL,intermediate_token_amount TEXT NOT NULL,advanced_token_amount TEXT NOT NULL,
 min_confirmations INTEGER NOT NULL DEFAULT 12 CHECK(min_confirmations BETWEEN 1 AND 1000),walletconnect_project_id TEXT,enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),created_by_user_id TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL DEFAULT(unixepoch()),updated_at INTEGER NOT NULL DEFAULT(unixepoch()),deleted_at INTEGER
);
CREATE INDEX IF NOT EXISTS crypto_payment_settings_active_idx ON crypto_payment_settings(enabled,deleted_at,chain_id);
CREATE TABLE IF NOT EXISTS crypto_payment_claims (
 id TEXT PRIMARY KEY NOT NULL,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,setting_id TEXT NOT NULL REFERENCES crypto_payment_settings(id),tx_hash TEXT NOT NULL UNIQUE,plan_id TEXT NOT NULL CHECK(plan_id IN ('basic','intermediate','advanced')),language_code TEXT NOT NULL CHECK(language_code IN ('zh','en','es','ja','ko','fr','de','ru','it','pt','ar','hi')),class_id TEXT NOT NULL REFERENCES smartlingo_language_classes(id),chain_id INTEGER NOT NULL,chain_name TEXT NOT NULL,token_symbol TEXT NOT NULL,payer_wallet TEXT NOT NULL,receiver_wallet TEXT NOT NULL,expected_atomic_amount TEXT NOT NULL,observed_atomic_amount TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'verified' CHECK(status IN ('verified','rejected')),entitlement_status TEXT NOT NULL DEFAULT 'synced' CHECK(entitlement_status IN ('pending_sync','synced','rejected')),created_at INTEGER NOT NULL DEFAULT(unixepoch()),verified_at INTEGER
);
CREATE INDEX IF NOT EXISTS crypto_payment_claims_user_idx ON crypto_payment_claims(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS crypto_payment_admin_audit (id TEXT PRIMARY KEY NOT NULL,admin_user_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL,setting_id TEXT NOT NULL,created_at INTEGER NOT NULL DEFAULT(unixepoch()));
CREATE INDEX IF NOT EXISTS crypto_payment_admin_audit_idx ON crypto_payment_admin_audit(admin_user_id,created_at DESC);
