-- Forward-only pt vocabulary quality sweep for the complete 48,000-row catalog.
-- Repairs only rows that failed deterministic repetition, corruption, length, or learner-safety gates.
UPDATE smartlingo_vocabulary_items SET meaning_en='of; from', meaning_zh='……的；从；来自', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_29_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='the (feminine singular); her; it', meaning_zh='定冠词（阴性单数）；她；它', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_30_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='the (masculine singular); him; it', meaning_zh='定冠词（阳性单数）；他；它', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_31_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='that; which; what', meaning_zh='引导从句；哪个；什么', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_32_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='and', meaning_zh='和；以及', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_33_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='in; at; on', meaning_zh='在……里面；在；在……上', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_34_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='is', meaning_zh='是（ser 的第三人称单数）', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_35_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='for; to; toward', meaning_zh='为了；给；向', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_36_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='one; a; an', meaning_zh='一；一个；不定冠词', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_37_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='with', meaning_zh='和；与……一起', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_38_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='oneself; if', meaning_zh='自己；如果', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_39_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='by; through; for', meaning_zh='由；通过；为了', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_40_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='them', meaning_zh='他们', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_44_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='more', meaning_zh='用于形成形容词和副词的比较；更多；-er', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_45_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='much; many; a lot of', meaning_zh='许多；很多', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_55_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='too; also (in addition; as well', meaning_zh='此外(此外；还有', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_58_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='hair (filament which grows on the skin of mammals; except hair on top of humans’ heads; which is called cabelo', meaning_zh='头发', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_61_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='only; just (alone in a category', meaning_zh='仅；公正( 单独属于一个类别', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_63_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='on; atop; on top of (located on the top surface of', meaning_zh='上；顶部( 位于顶部表面', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_65_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='well; accurately; competently', meaning_zh='好吧；准确的；能胜任的', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_66_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='their or your kin; folks; fellows', meaning_zh='他们的亲戚；或你们的亲戚；或你们的同胞', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_81_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='where; wherever (in or at what place; in or at a', meaning_zh='地点；地点(在或在哪里；在或在一个地点', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_85_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='catafalque (platform to display or convey a coffin', meaning_zh='显示或传送棺材的平台', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_90_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='nothing (not any thing; no thing', meaning_zh='无(无；无', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_94_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='large; great; big (of great size or extent', meaning_zh='大；大( 很大或很大', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_100_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='part; section; portion', meaning_zh='部分', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_108_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='major; greater', meaning_zh='主要；较大', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_124_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='there; over there', meaning_zh='那边', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_147_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='photo; photograph', meaning_zh='图片；照片', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_171_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='end; conclusion; closure', meaning_zh='结束；结论', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_184_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='final; ultimate; last', meaning_zh='最终；最后', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_185_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='father (male who sires a child', meaning_zh='父亲(男；女', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_194_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='one thousand; a thousand; 1000', meaning_zh='千', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_210_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='region; district', meaning_zh='地区', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_223_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='area; region; place (a geographical location', meaning_zh='区域；地点(一个地理位置', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_226_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='film; movie; motion picture', meaning_zh='电影', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_238_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='done; made; produced', meaning_zh='完成；生产', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_249_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to use; to utilise; to employ', meaning_zh='使用', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_267_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='help; assistance; aid', meaning_zh='帮助；援助', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_268_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='truly; really; actually', meaning_zh='真实的；实际的', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_272_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='a lot', meaning_zh='基多语的同义词', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_287_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='difficult; hard; unlikely', meaning_zh='难度；不太可能', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_299_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='force; strength', meaning_zh='部队；兵力', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_302_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Mediterranean parrotfish (Sparisoma cretense; a fish of the Atlantic Ocean', meaning_zh='地中海鹦鹉鱼', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_306_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='morning', meaning_zh='早 间', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_311_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='no; none', meaning_zh='否；无', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_312_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='football; soccer', meaning_zh='足球', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_319_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='true; real', meaning_zh='真实', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_329_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to return; to come back', meaning_zh='返回', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_340_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='oneself; yourself; himself', meaning_zh='自己；你自己', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_347_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to start; to begin; to commence', meaning_zh='开始', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_360_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='close; closely; next (at a little distance', meaning_zh='关闭；下一个( 距离稍远', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_367_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='abbreviation of segundo', meaning_zh='的缩写', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_369_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='support; backing', meaning_zh='支持', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_375_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to enter; to go into', meaning_zh='输入', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_377_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='enough; sufficiently', meaning_zh='足够', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_386_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='young; youthful', meaning_zh='年轻', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_388_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='due; owing', meaning_zh='应付款', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_412_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='top; summit', meaning_zh='顶端', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_425_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='way; manner; fashion (how something is done', meaning_zh='方式；时尚( 如何做', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_458_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='meeting; gathering; get-together', meaning_zh='会议；聚会', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_469_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to try; go for; attempt', meaning_zh='尝试；去尝试', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_480_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to take; take out; take away', meaning_zh='取；取出；取走', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_481_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='subject; topic; theme', meaning_zh='主题', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_483_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to get; obtain', meaning_zh='获取', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_486_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='far; a long way', meaning_zh='很远', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_499_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='examination; test', meaning_zh='考试', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_500_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to place; to put', meaning_zh='备置', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_506_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='not correct; wrong; incorrect', meaning_zh='不正确；错误', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_507_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='just; only; merely', meaning_zh='正义；仅仅', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_512_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to happen; to occur; to take place', meaning_zh='发生', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_528_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='chief; head; head man', meaning_zh='主管', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_538_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to understand; to grasp; to comprehend', meaning_zh='理解；把握', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_542_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='answer; response', meaning_zh='回答；回应', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_545_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='evening', meaning_zh='晚间', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_546_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='step; footstep; pace (movement made from one foot to the other', meaning_zh='步数( 从一脚移动到另一脚', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_561_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='title given to a female saint: Saint; St', meaning_zh='授予女性圣徒的头衔:圣徒；圣徒', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_566_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='trip; journey; voyage', meaning_zh='旅行；航行', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_580_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='bramble (any of various thorny shrubs; especially those in the family Rubus', meaning_zh='粗糙的', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_595_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='theme; topic; subject (what something is about', meaning_zh='主题( 问题是什么', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_596_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='radium (chemical element', meaning_zh='化学元素', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_607_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='behind; rear', meaning_zh='后面；后边', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_610_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to call; to summon (to ask someone to come', meaning_zh='召唤；叫人来', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_627_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='liberty; freedom', meaning_zh='自由；自由权', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_644_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='direction; way', meaning_zh='方向；方式', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_668_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='mount; a mountain or large hill', meaning_zh='登山；一座山或大山', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_677_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='conversation; talking', meaning_zh='对话', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_704_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='measurement; measure', meaning_zh='测量', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_709_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to want; to wish; to desire', meaning_zh='渴望；愿望', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_715_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='contrary; opposite', meaning_zh='反对；反', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_717_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='noncredible; uncredible', meaning_zh='不可信', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_719_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='minor; lesser', meaning_zh='次要；较小', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_720_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='able; capable', meaning_zh='能够', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_726_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='east (compass point', meaning_zh='东( 坐标点', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_733_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='interesting (arousing or holding someone’s interest', meaning_zh='有趣( 无视或持有某人的利益', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_750_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='holy; sacred', meaning_zh='圣洁', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_755_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sufficient; enough', meaning_zh='足够', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_756_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='ground; soil; earth', meaning_zh='地面；土壤；土质', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_789_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='completely; fully; totally (to a complete extent or degree', meaning_zh='完全(完全或程度', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_790_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sign; mark; trace (a visible or otherwise perceivable indication of something', meaning_zh='标记；追踪(可见或可察觉的某物迹象', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_812_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='alone; by oneself; on one''s own', meaning_zh='一个人', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_813_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='deputy; Member of Parliament', meaning_zh='议员', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_819_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='error; mistake', meaning_zh='错误', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_837_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='whole; entire; in full (with nothing missing', meaning_zh='整体( 无遗漏', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_859_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='responsibility; responsibleness', meaning_zh='责任', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_871_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='destiny; fate', meaning_zh='命运', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_886_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='illness; disease; ailment (an abnormal medical condition', meaning_zh='疾病(异常的健康状况', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_888_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='shop; store', meaning_zh='商店', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_894_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='very large; huge', meaning_zh='非常大；巨大的', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_898_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to deal with; to handle', meaning_zh='处理', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_909_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='rapidly; quickly', meaning_zh='快点', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_914_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='step; footstep; pace (movement made from one foot to the other', meaning_zh='步数( 从一脚移动到另一脚', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_925_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='powders', meaning_zh='类同词', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_927_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='full; filled; completed', meaning_zh='满；填充；完成', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_970_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='highlight; prominence', meaning_zh='突出显示', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_972_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='abbreviation of hora', meaning_zh='缩略语', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_974_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to obtain; get', meaning_zh='获取', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_978_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to search; to seek; to look for', meaning_zh='搜索；寻找', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_979_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='soil; ground', meaning_zh='土壤；地面', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_985_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='post; occupation; profession', meaning_zh='职位；职业', updated_at=unixepoch() WHERE id='vocab_pt_beginner_frequency_991_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='existence; being', meaning_zh='存在', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1008_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to improve; to ameliorate; to better', meaning_zh='改进；改善', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1013_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='approximately; about; circa', meaning_zh='大约', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1027_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to fall; to fall down; to drop', meaning_zh='下降', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1029_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sweet; sugary', meaning_zh='甜的；甜的( 甜的', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1034_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='hot; warm', meaning_zh='热；温暖', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1063_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of género', meaning_zh='巴西葡萄牙语标准拼写gé', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1079_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='pre-reform spelling (used until 1990) of ideia; may still occur as a sporadic misspelling', meaning_zh='改革前(直到1990年使用)的 " " 拼写；仍可能作为零星的拼写出现', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1081_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='moonlight; moonshine', meaning_zh='月光', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1082_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to realise (to convert something imaginary or planned; as a goal or idea; into reality', meaning_zh='实现(将想象或计划的东西转化为目标或想法；转化为现实', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1085_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='crazy; mad; insane (of unsound mind', meaning_zh='狂狂；狂狂狂', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1103_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='portal; doorway; gateway', meaning_zh='门户；门路；网关', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1124_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='joy; happiness', meaning_zh='快乐', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1132_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='trust; confidence', meaning_zh='信任', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1139_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to take care (of; to look after (to provide care for', meaning_zh='照顾(照顾', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1141_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='a thought; an idea', meaning_zh='一个想法', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1147_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='rich; wealthy', meaning_zh='富贵', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1150_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='bathroom; lavatory', meaning_zh='卫生间；厕所', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1152_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to link; to connect; to join (to put things together so they work together', meaning_zh='连接( 将事物组合在一起；以便它们一起工作', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1164_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to order; command', meaning_zh='命令', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1166_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sensation; sense', meaning_zh='感觉', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1190_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to offer; bid; tender', meaning_zh='发价；投标', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1203_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='talk; lecture; speech (session of speaking', meaning_zh='演讲(讲课', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1216_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='how many; what number', meaning_zh='多少个', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1224_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='feeling; emotion; sentiment', meaning_zh='感觉；情感', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1227_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='comment; observation; remark', meaning_zh='注释', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1230_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='intention; intent', meaning_zh='意图', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1241_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='start; beginning', meaning_zh='开始', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1247_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='site; location; place', meaning_zh='地点；位置', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1249_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='cool; awesome', meaning_zh='酷毙了 酷毙了', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1250_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='flat; apartment', meaning_zh='平面；公寓楼', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1252_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='canvas (piece of canvas cloth stretched across a frame on which one may paint', meaning_zh='画布(画布布件；可画在画框上', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1272_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to an extreme degree; extremely', meaning_zh='- 极端程度', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1290_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='possession; land', meaning_zh='拥有；土地', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1315_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='purpose; target; aim', meaning_zh='目标', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1316_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='elect; elected', meaning_zh='选举；当选', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1329_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to permit; to allow; to let', meaning_zh='允许', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1341_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='agriculture; farming', meaning_zh='农业', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1346_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='conflict; strife; war (clash', meaning_zh='冲突；战争(冲突', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1380_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='boy; young man; lad', meaning_zh='男孩 年轻人 小伙子', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1394_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to face; confront', meaning_zh='面对面', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1405_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='idiotic', meaning_zh='蠢货', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1410_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='building; edifice', meaning_zh='建筑物；建筑', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1428_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='having womanly qualities; womanly; feminine', meaning_zh='具有女性素质；女性素质', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1431_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to ascend; to go up', meaning_zh='升华', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1444_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='cat (domestic cat: Felis silvestris catus', meaning_zh='猫 猫科动物 猫科动物(家用猫:家用猫) 猫科动', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1457_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='winter (the coldest of the four seasons', meaning_zh='冬天(四季中最冷的季节', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1458_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='meaning; significance', meaning_zh='意义', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1465_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='current; flow', meaning_zh='当前；流动', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1479_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='step; stage; phase', meaning_zh='步骤；阶段', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1485_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='annual; yearly', meaning_zh='每年', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1504_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='obviously; evidently; clearly', meaning_zh='很明显；显然', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1513_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='frequently; often', meaning_zh='经常', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1521_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='at least; at the least', meaning_zh='起码；至少', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1531_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='job; task', meaning_zh='任务', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1558_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='vacancy; opening', meaning_zh='空缺；打开', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1564_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='utilization; use', meaning_zh='使用', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1584_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='assistance; aid; help', meaning_zh='援助；帮助', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1585_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='game; play', meaning_zh='游戏', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1587_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='third-person plural preterite; pluperfect indicative of levar', meaning_zh='第三人称复数前；表示', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1593_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='den; burrow', meaning_zh='凹槽', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1606_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='profitable; advantageous', meaning_zh='有利可图；有利', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1608_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to combine; to unite', meaning_zh='合并', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1625_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='samba (Brazilian genre of music and dance', meaning_zh='桑巴(巴西音乐舞蹈流派', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1633_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='similar; alike', meaning_zh='类似', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1634_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='dressed; clothed', meaning_zh='着装', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1638_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='oil; petroleum', meaning_zh='石油', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1652_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to spread; disseminate; popularize', meaning_zh='传播；普及', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1669_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='jack (switch for a jack plug', meaning_zh='插孔；插座', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1674_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='louis (gold or silver coin issued by the French kings from Louis XIII to Louis XVI', meaning_zh='洛伊斯(法国国王从路易十三到路易十六发行的金币或银币', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1675_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='edge; margin; border', meaning_zh='边缘；边距；边框', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1685_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sleepy; tired', meaning_zh='困；疲劳', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1686_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='tea plant (Camellia sinensis; a bush whose leaves are used to make tea', meaning_zh='茶叶植物', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1687_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='closed; shut', meaning_zh='关闭', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1695_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='coach; trainer; handler', meaning_zh='教练；操作员', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1710_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to use; employ; apply', meaning_zh='使用；应用', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1711_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='placed; put', meaning_zh='放置', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1716_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to carry out; to do; to perform', meaning_zh='执行', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1718_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to prove; show; to demonstrate that something is true', meaning_zh='证明；显示；证明某物属实', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1732_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='determinate; ascertained', meaning_zh='确定', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1751_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='third-person plural preterite; pluperfect indicative of acabar', meaning_zh='第三人称复数前；表示', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1765_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='adolescent; teenage', meaning_zh='青少年', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1766_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='huge; gigantic', meaning_zh='巨大的', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1781_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='mum; mom; mummy', meaning_zh='妈妈', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1784_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='fan (admirer or aficionado', meaning_zh='风扇( 画家或画家', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1816_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='rice (Oryza sativa; a cereal', meaning_zh='稻米', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1832_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='horse (Equus ferus caballus', meaning_zh='木马', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1835_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='chosen; selected; picked', meaning_zh='选中', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1843_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='obviously; evidently; clearly', meaning_zh='很明显；显然', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1856_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='explanation; explication', meaning_zh='解释', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1885_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='false; untrue; not factual', meaning_zh='虚假；不真实', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1886_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='herdsman; herder (someone who tends livestock', meaning_zh='牧人', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1897_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to supply; provide; furnish', meaning_zh='供应；提供', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1921_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='prepared; ready', meaning_zh='备妥', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1934_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='absolutely; completely; entirely', meaning_zh='绝对；完全', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1942_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='condemned; sentenced; convicted', meaning_zh='已判刑；已定罪', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1948_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to put; to place', meaning_zh='备置', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1961_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='course; path', meaning_zh='路径', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1964_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='nevermind; forget it', meaning_zh='无所谓了；算了吧', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1976_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='internal; interior; inner (inside of something', meaning_zh='内部( 内在', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1982_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='insanity; madness', meaning_zh='疯狂', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1983_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='masculine; male', meaning_zh='男性；男性( 男性', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1984_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='notion; idea; conception', meaning_zh='概念；想法', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1985_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='scallop (mollusc of the family Pectinidae', meaning_zh='扇贝', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_1996_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='increasing; growing', meaning_zh='增长', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2003_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='gamma (the third letter of the Greek alphabet (Γ; γ; preceded by beta (Β', meaning_zh='γ(希腊语字母表的第三个字母(Γ；γ；前为β', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2010_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Portuguese yellow broom (Cytisus striatus', meaning_zh='葡萄牙黄色扫帚', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2016_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='dad; papa', meaning_zh='爸爸；父亲', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2019_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='full; entire', meaning_zh='全文', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2021_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='afterwards; later', meaning_zh='之后', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2022_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='jump; leap', meaning_zh='跳；跳跃', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2025_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to ruin; devastate (proceed with the destruction of; cause the destruction of', meaning_zh='破坏', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2036_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to save; keep; retain', meaning_zh='要保存；保留', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2050_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to start; begin; initiate', meaning_zh='开始；启动', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2051_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='look; glance', meaning_zh='查看；浏览', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2056_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='option; choice; resort', meaning_zh='选项；选择', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2063_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='distant; faraway', meaning_zh='遥远', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2078_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='elevated; raised; high (at a great distance from the ground', meaning_zh='升起', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2080_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='manifestation; expression', meaning_zh='表达式', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2088_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to observe; watch', meaning_zh='要观察；监视', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2095_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='goodbye (an instance of wishing goodbye; especially with the word tchau', meaning_zh='告别', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2102_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='glasses; spectacles', meaning_zh='眼镜', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2107_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to evaluate; assess; appraise', meaning_zh='评估', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2108_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='fondness; affection', meaning_zh='爱', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2109_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to fight; to combat', meaning_zh='战斗', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2112_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to shout; to scream; to yell', meaning_zh='大声喊叫；尖叫；喊叫', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2122_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='trade union; syndicate', meaning_zh='工会；辛迪加', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2134_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='suspicious; suspect', meaning_zh='可疑', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2135_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='advance; advancement', meaning_zh='高级', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2138_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='companion; comrade', meaning_zh='伴侣；同志', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2141_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='favourite; preferred', meaning_zh='首选', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2149_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='risky; unsafe; dangerous', meaning_zh='危险；不安全', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2156_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='adult; grown-up', meaning_zh='成年人', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2165_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='pleasant; agreeable; nice', meaning_zh='愉快', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2166_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to notify; to warn', meaning_zh='通知；警告', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2168_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='ass; butt', meaning_zh='屁股；臀部', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2173_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of fenómeno', meaning_zh='巴西葡萄牙语标准拼音fenó', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2185_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='exactly; precisely', meaning_zh='准确的', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2190_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to put in; to insert into', meaning_zh='插入', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2192_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='pro; in favour of', meaning_zh='赞成', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2201_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to understand; to comprehend', meaning_zh='理解', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2217_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of eletrónico', meaning_zh='巴西葡萄牙语标准拼写 ó', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2221_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='partner; associate', meaning_zh='合作伙伴；协理', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2244_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='WhatsApp (a message on WhatsApp', meaning_zh='何斯App 互联网档案馆的存檔；存档日期2013-09-02', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2249_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='fantastic (wonderful; marvelous', meaning_zh='赞极了', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2261_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='nick; nickname', meaning_zh='昵称', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2266_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to remain; stay; persist', meaning_zh='a) 长期居留', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2269_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='lately; recently; of late', meaning_zh='最近', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2275_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='shelter; haven; refuge', meaning_zh='庇护所', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2277_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='devil; demon; fiend (creature from Hell', meaning_zh='恶魔', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2287_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to decrease; diminish; lessen', meaning_zh='减少', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2288_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='faithful; loyal', meaning_zh='忠诚', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2291_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='tape; ribbon; band', meaning_zh='带子；丝带', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2293_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='purpose; goal', meaning_zh='目的；目标', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2297_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='hug; embrace', meaning_zh='拥抱', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2308_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to repel; to push away (cause to move away', meaning_zh='被驱赶', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2310_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='DJ; deejay; disk jockey (person who plays or mixes recorded music at nightclubs', meaning_zh='DJ；磁盘骑师(在夜总会演奏或混音录制音乐的人', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2321_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='tasty; tasteful', meaning_zh='好吃；有品味；不错', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2329_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='crazy; mad', meaning_zh='疯了', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2335_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to replace; substitute', meaning_zh='替换', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2348_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='count; counting', meaning_zh='计数', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2360_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='unknown; strange', meaning_zh='未知；奇数', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2365_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='helmeted guineafowl (Numida meleagris', meaning_zh='头盔豚鼠', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2375_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='stopped; halted; immobile', meaning_zh='停止；无法移动', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2383_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='ready; prepared', meaning_zh='备妥', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2387_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='comprehension; understanding', meaning_zh='理解', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2406_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of eletrónica', meaning_zh='巴西葡萄牙语标准拼写 ó', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2408_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='official; functionary', meaning_zh='官员；函数', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2414_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='salvo (salute paid by simultaneous firing of cannons', meaning_zh='通过同时发射大炮支付薪金', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2427_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='attention; cautiousness; prudence', meaning_zh='注意；谨慎', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2431_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='for free; free of charge', meaning_zh='免费', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2454_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='assembly; assemblage', meaning_zh='组装', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2462_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to go forward; advance', meaning_zh='前进', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2483_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='conduct; behavior; demeanor', meaning_zh='行为', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2487_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to overthrow; overturn', meaning_zh='推翻', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2490_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='petrol; gasoline', meaning_zh='汽油', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2493_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='wonder; marvel (something that causes amazement or awe', meaning_zh='奇事:', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2495_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to occur; happen', meaning_zh='发生', updated_at=unixepoch() WHERE id='vocab_pt_intermediate_frequency_2499_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='single (song released on its own or with an extra track', meaning_zh='单曲( 单曲', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2510_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='assault; attack', meaning_zh='攻击', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2521_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='holy; sacred', meaning_zh='圣洁', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2523_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='phase; stage', meaning_zh='阶段', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2532_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='phi (name of the Greek letter Φ', meaning_zh='phi( 希腊字母 的名称', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2534_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='wolf (a wild canid', meaning_zh='狼(一只野狗', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2539_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='course; route', meaning_zh='课程；路线', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2544_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='pre-reform spelling (used until 1943 in Brazil and 1911 in Portugal) of polícia', meaning_zh='改革前拼法(巴西使用至1943年；葡萄牙使用至1911年) Polícia', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2545_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of polémica', meaning_zh='巴西葡萄牙语标准拼写 Polé', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2546_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='prohibited; forbidden', meaning_zh='禁止', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2548_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='holy; sacred', meaning_zh='圣洁', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2551_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='integral; whole; entire', meaning_zh='整体', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2578_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='iPhone (smartphone produced by Apple Inc', meaning_zh='苹果公司生产的智能手机', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2579_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='lose', meaning_zh='输', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2587_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='plastic; malleable; mouldable', meaning_zh='塑料；可塑；可铸造', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2589_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to reveal; disclose', meaning_zh='披露', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2595_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to state; to declare; to affirm (to make a declaration', meaning_zh='声明；确认(作出声明', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2600_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='circular; round', meaning_zh='圆', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2605_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to pass; to elapse', meaning_zh='要通过；要结束', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2609_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='heritage; inheritance; legacy', meaning_zh='遗产', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2616_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='maize (seeds of the plant Zea mays', meaning_zh='玉米', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2619_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='significant; important', meaning_zh='重要', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2629_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to descend; to go down', meaning_zh='降', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2648_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='fun; amusing; entertaining', meaning_zh='乐趣；娱乐', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2651_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='effective; efficacious', meaning_zh='有效', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2653_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='evident; obvious; self-explanatory', meaning_zh='明显；不言自明', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2656_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='hurry; rush; haste', meaning_zh='快点', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2669_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='depth; deepness', meaning_zh='深度', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2670_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='calm; peaceful; tranquil (without motion or sound', meaning_zh='平静(无运动或声音', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2676_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='anime (Japanese animation', meaning_zh='日本动画', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2683_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to confirm; corroborate; affirm', meaning_zh='证实；确认', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2689_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='intense; strong', meaning_zh='强烈', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2701_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='judicial; justiciary', meaning_zh='司法；司法权', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2703_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='LGBT; initialism of lésbicas; gays', meaning_zh='lé 的初始主义；同性恋', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2706_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='afro (hairstyle', meaning_zh='头发样式', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2724_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='third-person plural preterite; pluperfect indicative of decidir', meaning_zh='第三人称复数前结晶；表示', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2733_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='negative; negation', meaning_zh='负；否定', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2748_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='disability; handicap', meaning_zh='残疾', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2768_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='injured; hurt; sore', meaning_zh='受伤；痛', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2775_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='containing unpleasant substances such as dirt or grime; dirty; unclean', meaning_zh='含有污秽；污秽等令人不快的物质', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2793_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='capture; seizure', meaning_zh='抓获', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2798_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='necklace; chain', meaning_zh='项链；链条', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2802_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='dance; ball', meaning_zh='舞蹈；舞会', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2805_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='forced; coercive; compulsory', meaning_zh='强迫；强制', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2810_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='breast; bosom', meaning_zh='乳房；乳房( 乳房', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2817_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to go up; climb', meaning_zh='向上爬；爬升', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2821_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='attacked; assaulted', meaning_zh='攻击', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2835_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to highlight; to underline', meaning_zh='要突出显示；下划线', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2842_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to possess; to have; to own', meaning_zh='拥有', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2868_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='burn; burning (the act of burning', meaning_zh='烧灼；烧灼(烧灼', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2871_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='witness (one who sees or has personal knowledge of something', meaning_zh='以物配主者', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2881_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='rope; string', meaning_zh='绳子；字符串', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2892_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='understanding; comprehension', meaning_zh='理解', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2897_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='money; cash; dough', meaning_zh='货币；现金', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2899_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='unbelievable; incredible', meaning_zh='难以置信', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2905_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='lesion; wound', meaning_zh='损伤；伤口', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2907_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of registado', meaning_zh='巴西葡萄牙语 标准拼写法', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2917_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='substitution; replacement', meaning_zh='替换', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2920_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='truly; truthfully', meaning_zh='确是真实的', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2924_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of académico', meaning_zh='巴西葡萄牙语标准拼写 é', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2925_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='last name; surname; family name', meaning_zh='姓', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2927_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to commit; practice; undertake', meaning_zh='承诺；实践', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2930_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to last; endure', meaning_zh='持久；忍耐', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2932_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='below; down', meaning_zh='下面；下', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2933_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='guy; bloke; dude', meaning_zh='哥们；伙计', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2937_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='source; origin; mother', meaning_zh='来源；母亲', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2946_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='wistfulness; melancholy; nostalgia', meaning_zh='柔弱；忧郁；怀旧', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2955_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to call off; to cancel', meaning_zh='取消', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2973_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='unemployment; joblessness', meaning_zh='失业', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2981_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='excess; surplus', meaning_zh='盈余', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_2988_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to tolerate; to put up with; to take', meaning_zh='容忍', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3004_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='learning; schooling', meaning_zh='学习；学校教育', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3013_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='trousers; pants', meaning_zh='裤子', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3018_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Flavius', meaning_zh='法拉维亚诺语的同义词', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3036_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to alter; change', meaning_zh='更改', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3063_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='alteration; change; modification', meaning_zh='改变；修改', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3064_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='vernacular name of macaws and parakeet species in the family Psittacidae', meaning_zh='家族中的鹦鹉和鹦鹉物种的方言名称', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3085_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='naked; nude', meaning_zh='裸体', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3092_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='mobile; mobile phone; cellphone', meaning_zh='移动电话', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3104_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='woof; weft', meaning_zh='摇摆；编织', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3106_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='third-person plural preterite; pluperfect indicative of criar', meaning_zh='第三人称复数先；纯度表示', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3119_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to fill; fill up', meaning_zh='要填满；填充', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3124_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='the gathering or grouping of various spirits; who manifest through mediums in Umbanda', meaning_zh='各种精神的集合或组合；通过媒体在 出现', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3129_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='for free; free of charge', meaning_zh='免费', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3131_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to forgive; to pardon', meaning_zh='赦免', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3140_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='result; end; consequence', meaning_zh='结果；结束；后果', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3153_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='that manages; that administers; administrative', meaning_zh='管理；行政', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3156_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to point out; to indicate', meaning_zh='指出；指明', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3159_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='not arriving until after an expected time; late', meaning_zh='直到预期时间过后才到达；迟到', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3161_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='mess; disorder', meaning_zh='乱', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3163_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='combined; joined; connected', meaning_zh='合并；加入；连接', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3168_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='dependency; dependence', meaning_zh='依赖', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3171_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='deceit; fraud', meaning_zh='欺诈', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3174_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='entirely; fully; wholly', meaning_zh='完全', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3182_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='pig (the domesticated farm animal Sus scrofa', meaning_zh='猪', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3189_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to collect; gather', meaning_zh='要收集；收集', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3203_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='angry; furious; annoyed', meaning_zh='愤怒；烦恼', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3207_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='a tree of species Cnidoscolus quercifolius; native to northeastern Brazil', meaning_zh='一种树种；原生于巴西东北部', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3275_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='wound; injury', meaning_zh='伤', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3276_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='goal; objective', meaning_zh='目标', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3277_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='completely; absolutely; fully', meaning_zh='完全；绝对', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3278_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='harmony; agreement; accord', meaning_zh='和谐；协议', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3280_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='incapable; unable', meaning_zh='无法', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3282_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='instruction; education; teaching', meaning_zh='教学；教育', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3284_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to make up; to compose', meaning_zh='补', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3285_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='washing; rinsing', meaning_zh='洗涤', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3287_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sea; marine', meaning_zh='海洋', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3288_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='notable; noteworthy; remarkable', meaning_zh='显著', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3289_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to collect; gather', meaning_zh='要收集；收集', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3295_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='saga (Old Norse prose narrative', meaning_zh='萨加语(旧诺斯语流言蜚语', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3300_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='salvation; saving', meaning_zh='救赎；拯救', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3301_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='third-person plural preterite; pluperfect indicative of seguir', meaning_zh='第三人称复数前；表示', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3303_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to arise; to emerge', meaning_zh='将出现', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3306_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to confer; bestow', meaning_zh='授予', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3321_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='faithful; loyal', meaning_zh='忠诚', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3322_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of oxigénio', meaning_zh='巴西葡萄牙语标准拼音 énio', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3350_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sincere; truthful', meaning_zh='诚实的', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3356_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='tiger', meaning_zh='老虎', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3361_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='touristic; touristy', meaning_zh='旅游', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3362_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to capture; catch', meaning_zh='要捕获；捕获', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3377_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='decrease; reduction; diminution', meaning_zh='减少', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3385_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to require; need', meaning_zh='需要', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3386_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='mandatory; obligatory', meaning_zh='强制', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3400_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='duck (any aquatic bird of the family Anatidae', meaning_zh='鸭', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3401_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='pre-reform spelling (used until 1943 in Brazil and 1911 in Portugal) of também', meaning_zh='ém改革前的拼写(巴西使用至1943年；葡萄牙使用至1911年', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3412_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='every year; yearly; annually', meaning_zh='每年', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3424_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to declare; to state', meaning_zh='声明', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3441_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to cause; suffer an explosion; to (make) burst', meaning_zh='造成爆炸', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3451_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='outside of; external', meaning_zh='外部', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3452_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to provide incentive; to incentivize; to foster', meaning_zh='提供奖励；奖励', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3459_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='head; chief; main (foremost in rank', meaning_zh='头；主( 职级前', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3465_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='an amorous but non-marital relationship; a relationship envolving a boyfriend or girlfriend', meaning_zh='- 涉及男友或女友的关系', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3467_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='third-person plural preterite; pluperfect indicative of achar', meaning_zh='第三人称复数前结晶；纯度表示', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3488_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to acquire; get; obtain', meaning_zh='获取', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3489_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='idiot; moron', meaning_zh='蠢货', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3492_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='corporal; carnal', meaning_zh='下士；性爱', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3507_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='gratitude; gratefulness', meaning_zh='感谢', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3518_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='uncommon; unusual', meaning_zh='不寻常', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3522_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='MC', meaning_zh='冰毒的同义词', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3523_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='substance; physical matter', meaning_zh='物质', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3536_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='ending; termination; conclusion', meaning_zh='结束；结论', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3540_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='competition; rivalry', meaning_zh='竞争', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3551_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='cupola; dome', meaning_zh='圆顶', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3554_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to dominate; to predominate', meaning_zh='主导', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3559_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='gaucho (cowboy of the South American pampas', meaning_zh='南美纸币的牛仔', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3569_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='dwelling; abode; home', meaning_zh='住所', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3576_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='peak; summit; top (the highest point of a mountain', meaning_zh='峰顶( 一座山的最高点', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3577_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='breathing; respiration', meaning_zh='呼吸', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3585_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='fabrication; manufacture', meaning_zh='制造', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3606_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='supply; provision', meaning_zh='供应', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3608_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='the flu; influenza', meaning_zh='流感', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3610_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='valiant; courageous', meaning_zh='勇敢', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3628_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='silly; stupid', meaning_zh='傻子 傻子', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3637_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='goodness; kindness; mildness', meaning_zh='善良；温和', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3638_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='funk (a genre of popular music derived from soul music', meaning_zh='源于灵魂音乐的流行音乐流派', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3649_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='a female youngster; a girl', meaning_zh='女青年', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3661_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='refuge; haven', meaning_zh='避难；避难所', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3669_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='translating; translator', meaning_zh='翻译', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3679_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to transport; carry', meaning_zh='运输；载运', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3680_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to brawl; fight', meaning_zh='战斗', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3698_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='competence; competency', meaning_zh='能力', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3703_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to see (to perceive with the eyes; to regard', meaning_zh='以眼看', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3710_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to be missing; to be lacking', meaning_zh='失踪', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3713_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='interchange; exchange', meaning_zh='交换', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3717_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='maté (Ilex paraguariensis) (a shrub native to southern South America', meaning_zh='maté (一种原生于南美洲南部的灌木', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3721_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='pre-reform spelling (used until 1943 in Brazil and 1911 in Portugal) of ópera', meaning_zh='改革前拼法(巴西使用至1943年；葡萄牙使用至1911年', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3724_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='reduced; diminished', meaning_zh='减少', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3731_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='bear (a member of the family Ursidae', meaning_zh='熊', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3742_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='ash; ashes', meaning_zh='灰烬', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3750_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='something which elevates (agent noun of elevar', meaning_zh='高级名词', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3765_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='darkness', meaning_zh='阴暗', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3767_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='manifest; evident; patent', meaning_zh='明显；专利', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3782_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='dwelling; residence', meaning_zh='住所', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3786_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='portion; part', meaning_zh='组件', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3791_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='restriction; limitation', meaning_zh='限制', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3793_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='toughness; hardness; stiffness', meaning_zh='坚硬', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3799_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='sporting; sports', meaning_zh='运动', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3822_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to bother; to annoy', meaning_zh='烦恼', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3828_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to measure; gauge', meaning_zh='测量', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3880_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to endeavor to gain (someone''s) affection; to woo; to court', meaning_zh='欲得人之爱', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3881_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Brazilian Portuguese standard spelling of crónica', meaning_zh='巴西葡萄牙语标准拼写cró', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3911_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='Islamic; Muslim', meaning_zh='伊斯兰教；穆斯林', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3921_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='race (of people; racial', meaning_zh='种族(人；种族', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3933_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='referee (umpire; judge; the supervisor of a game', meaning_zh='裁判', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3940_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='which conserves; preserves', meaning_zh='保护', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3954_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='duly; properly; correctly', meaning_zh='正确', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3958_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='dominant; prevailing', meaning_zh='占优势', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3959_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='stain; blemish; mark', meaning_zh='污点；标记', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3971_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to navigate; sail', meaning_zh='导航；航行', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3975_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='to harm; damage', meaning_zh='损害', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3984_v1';
UPDATE smartlingo_vocabulary_items SET meaning_en='harm; injury', meaning_zh='伤害', updated_at=unixepoch() WHERE id='vocab_pt_advanced_frequency_3985_v1';
CREATE TABLE smartlingo_vocab_quality_check(value INTEGER CHECK(value=1));
INSERT INTO smartlingo_vocab_quality_check SELECT COUNT(*) IN (28,4000) FROM smartlingo_vocabulary_items WHERE target_language='pt' AND review_status='published';
DROP TABLE smartlingo_vocab_quality_check;
