-- Add separate target-language phonetics and interface-language sound guides.
-- The 336 published rows below were AI-assisted from the versioned, reviewed
-- SmartLingo catalog, then validated for exact ID and language coverage.
ALTER TABLE smartlingo_vocabulary_items ADD COLUMN target_phonetic TEXT NOT NULL DEFAULT '';
ALTER TABLE smartlingo_vocabulary_items ADD COLUMN pronunciation_en TEXT NOT NULL DEFAULT '';
ALTER TABLE smartlingo_vocabulary_items ADD COLUMN pronunciation_zh TEXT NOT NULL DEFAULT '';

UPDATE smartlingo_vocabulary_items SET target_phonetic='/həˈloʊ/', pronunciation_en='huh-LOH', pronunciation_zh='hē-lóu', updated_at=unixepoch() WHERE id='vocab_en_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pliːz/', pronunciation_en='PLEEZ', pronunciation_zh='pǔ-lǐzī', updated_at=unixepoch() WHERE id='vocab_en_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈθæŋk juː/', pronunciation_en='THANK yoo', pronunciation_zh='sāngk yóu', updated_at=unixepoch() WHERE id='vocab_en_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɪkˈskjuːz miː/', pronunciation_en='ik-SKYOOS mee', pronunciation_zh='ì-kè-sī-kyù-zī mǐ', updated_at=unixepoch() WHERE id='vocab_en_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/maɪ neɪm ɪz/', pronunciation_en='my NAME iz', pronunciation_zh='mài néim yìz', updated_at=unixepoch() WHERE id='vocab_en_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/aɪ æm frəm/', pronunciation_en='eye am frum', pronunciation_zh='ài ēm fǎ-rěm', updated_at=unixepoch() WHERE id='vocab_en_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/jɛs/', pronunciation_en='YES', pronunciation_zh='yés', updated_at=unixepoch() WHERE id='vocab_en_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/noʊ/', pronunciation_en='NOH', pronunciation_zh='nóu', updated_at=unixepoch() WHERE id='vocab_en_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈɛrˌpɔrt/', pronunciation_en='AIR-port', pronunciation_zh='āi-pōrt', updated_at=unixepoch() WHERE id='vocab_en_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈtɪkɪt/', pronunciation_en='TIK-it', pronunciation_zh='tǐ-kít', updated_at=unixepoch() WHERE id='vocab_en_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɡeɪt/', pronunciation_en='GATE', pronunciation_zh='gēit', updated_at=unixepoch() WHERE id='vocab_en_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/wɛr ɪz/', pronunciation_en='wair iz', pronunciation_zh='wē’r yìz', updated_at=unixepoch() WHERE id='vocab_en_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/lɛft/', pronunciation_en='LEFT', pronunciation_zh='léft', updated_at=unixepoch() WHERE id='vocab_en_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/raɪt/', pronunciation_en='RYTE', pronunciation_zh='rài-t', updated_at=unixepoch() WHERE id='vocab_en_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/streɪt əˈhɛd/', pronunciation_en='STRAYT uh-HED', pronunciation_zh='sī-t''rēit ā-hēd', updated_at=unixepoch() WHERE id='vocab_en_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈrɛst.ruːm/', pronunciation_en='REST-room', pronunciation_zh='ruìs-t-rūm', updated_at=unixepoch() WHERE id='vocab_en_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈmɛnjuː/', pronunciation_en='MEN-yoo', pronunciation_zh='mén-yū', updated_at=unixepoch() WHERE id='vocab_en_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈwɔtər/', pronunciation_en='WAW-ter', pronunciation_zh='wǒ-těr', updated_at=unixepoch() WHERE id='vocab_en_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˌvɛdʒəˈtɛriən/', pronunciation_en='VEDJ-uh-TAIR-ee-un', pronunciation_zh='wěi-jǔ-tē-rī-ěn', updated_at=unixepoch() WHERE id='vocab_en_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ðə bɪl pliːz/', pronunciation_en='thuh BILL PLEEZ', pronunciation_zh='dā bǐl pǔ-līz', updated_at=unixepoch() WHERE id='vocab_en_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/haʊ mʌtʃ/', pronunciation_en='how MUCH', pronunciation_zh='háu mǎ-ch', updated_at=unixepoch() WHERE id='vocab_en_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kæʃ/', pronunciation_en='KASH', pronunciation_zh='kǎsh', updated_at=unixepoch() WHERE id='vocab_en_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kɑrd/', pronunciation_en='KARD', pronunciation_zh='kǎrd', updated_at=unixepoch() WHERE id='vocab_en_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/rɪˈsiːt/', pronunciation_en='ri-SEET', pronunciation_zh='rǐ-sīt', updated_at=unixepoch() WHERE id='vocab_en_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/help/', pronunciation_en='HELP', pronunciation_zh='hélp', updated_at=unixepoch() WHERE id='vocab_en_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/aɪ æm lɔst/', pronunciation_en='eye am LOST', pronunciation_zh='āi ǒm lòst', updated_at=unixepoch() WHERE id='vocab_en_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈdɑktər/', pronunciation_en='DOK-ter', pronunciation_zh='dá-k-těr', updated_at=unixepoch() WHERE id='vocab_en_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pəˈliːs/', pronunciation_en='puh-LEES', pronunciation_zh='pǔ-līs', updated_at=unixepoch() WHERE id='vocab_en_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ni˧˩˦ xaʊ˨˩˦/', pronunciation_en='NEE haow', pronunciation_zh='nǐ hǎo', updated_at=unixepoch() WHERE id='vocab_zh_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕʰiŋ˨˩˦/', pronunciation_en='CHEENG', pronunciation_zh='qǐng', updated_at=unixepoch() WHERE id='vocab_zh_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɕjɛ˥˩ ɕjɛ/', pronunciation_en='SHYEH shyeh', pronunciation_zh='xiè xie', updated_at=unixepoch() WHERE id='vocab_zh_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pu˥˩ xaʊ˨˩˦ i˥˩ sɿ/', pronunciation_en='BOO haow EE suh', pronunciation_zh='bù hǎo yì si', updated_at=unixepoch() WHERE id='vocab_zh_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/wɔ˨˩˦ tɕjɑʊ˥˩/', pronunciation_en='WAW JYOW', pronunciation_zh='wǒ jiào', updated_at=unixepoch() WHERE id='vocab_zh_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/wɔ˨˩˦ laɪ˧˥ tsɿ˥˩/', pronunciation_en='WAW lie dzuh', pronunciation_zh='wǒ lái zì', updated_at=unixepoch() WHERE id='vocab_zh_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʂɻ̩˥˩/', pronunciation_en='SHRR', pronunciation_zh='shì', updated_at=unixepoch() WHERE id='vocab_zh_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pu˧˥ ʂɻ̩˥˩/', pronunciation_en='BOO SHRR', pronunciation_zh='bú shì', updated_at=unixepoch() WHERE id='vocab_zh_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕi˥ tʂʰɑŋ˨˩˦/', pronunciation_en='JEE chahng', pronunciation_zh='jī chǎng', updated_at=unixepoch() WHERE id='vocab_zh_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pʰjɑʊ˥˩/', pronunciation_en='PYOW', pronunciation_zh='piào', updated_at=unixepoch() WHERE id='vocab_zh_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/təŋ˥ tɕi˥ kʰoʊ˨˩˦/', pronunciation_en='DUNG JEE kohw', pronunciation_zh='dēng jī kǒu', updated_at=unixepoch() WHERE id='vocab_zh_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tsaɪ˥˩ na˨˩˦ li/', pronunciation_en='dzye nah lee', pronunciation_zh='zài nǎ lǐ', updated_at=unixepoch() WHERE id='vocab_zh_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tswɔ˨˩˦ pjɛn˥/', pronunciation_en='dzwaw BYEN', pronunciation_zh='zuǒ biān', updated_at=unixepoch() WHERE id='vocab_zh_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/joʊ˥˩ pjɛn˥/', pronunciation_en='YOH BYEN', pronunciation_zh='yòu biān', updated_at=unixepoch() WHERE id='vocab_zh_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/i˥ ʈʂɻ̩˧˥ tsoʊ˨˩˦/', pronunciation_en='EE JER dzoh', pronunciation_zh='yī zhí zǒu', updated_at=unixepoch() WHERE id='vocab_zh_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɕi˨˩˦ ʂoʊ˨˩˦ tɕjɛn˥/', pronunciation_en='shee SHOW jyen', pronunciation_zh='xǐ shǒu jiān', updated_at=unixepoch() WHERE id='vocab_zh_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tsʰaɪ˥˩ tan˥/', pronunciation_en='ts eye DAHN', pronunciation_zh='cài dān', updated_at=unixepoch() WHERE id='vocab_zh_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʂweɪ˨˩˦/', pronunciation_en='shway', pronunciation_zh='shuǐ', updated_at=unixepoch() WHERE id='vocab_zh_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/su˥˩ ʂɻ̩˧˥/', pronunciation_en='SOO shir', pronunciation_zh='sù shí', updated_at=unixepoch() WHERE id='vocab_zh_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕʰiŋ˨˩˦ tɕjɛ˧˥ ʈʂɑŋ˥˩/', pronunciation_en='ching JYEH jahng', pronunciation_zh='qǐng jié zhàng', updated_at=unixepoch() WHERE id='vocab_zh_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tuɔ˥ ʂaʊ tɕʰjɛn˧˥/', pronunciation_en='dwoh shaow chyen', pronunciation_zh='duō shao qián', updated_at=unixepoch() WHERE id='vocab_zh_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɕjɛn˥˩ tɕin˥/', pronunciation_en='shyen JEEN', pronunciation_zh='xiàn jīn', updated_at=unixepoch() WHERE id='vocab_zh_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʂwɑ˥ kʰɑ˨˩˦/', pronunciation_en='shwah KAH', pronunciation_zh='shuā kǎ', updated_at=unixepoch() WHERE id='vocab_zh_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʂoʊ˥ tɕy˥˩/', pronunciation_en='SHOW jyoo', pronunciation_zh='shōu jù', updated_at=unixepoch() WHERE id='vocab_zh_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pɑŋ˥ pɑŋ wɔ˧˩˦/', pronunciation_en='BAHNG bahng WAW', pronunciation_zh='bāng bang wǒ', updated_at=unixepoch() WHERE id='vocab_zh_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/wɔ˧˩˦ mi˧˥ lu˥˩ lə/', pronunciation_en='waw mee LOO luh', pronunciation_zh='wǒ mí lù le', updated_at=unixepoch() WHERE id='vocab_zh_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/i˥ ʂəŋ˥/', pronunciation_en='EE shung', pronunciation_zh='yī shēng', updated_at=unixepoch() WHERE id='vocab_zh_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕiŋ˨˩˦ ʈʂʰɑ˧˥/', pronunciation_en='JING chah', pronunciation_zh='jǐng chá', updated_at=unixepoch() WHERE id='vocab_zh_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈola/', pronunciation_en='OH-lah', pronunciation_zh='ōu-lā', updated_at=unixepoch() WHERE id='vocab_es_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/poɾ faˈβoɾ/', pronunciation_en='por fah-VOR', pronunciation_zh='pōr fā-wǒr', updated_at=unixepoch() WHERE id='vocab_es_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈɡɾasjas/', pronunciation_en='GRAH-syahs', pronunciation_zh='gē-lā-sī-yǎs', updated_at=unixepoch() WHERE id='vocab_es_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/peɾˈdon/', pronunciation_en='pehr-DON', pronunciation_zh='péi-ěr-dōng', updated_at=unixepoch() WHERE id='vocab_es_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/me ˈʝamo/', pronunciation_en='meh YAH-moh', pronunciation_zh='mē yā-mō', updated_at=unixepoch() WHERE id='vocab_es_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/soj ðe/', pronunciation_en='SOY deh', pronunciation_zh='sōi dé', updated_at=unixepoch() WHERE id='vocab_es_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/si/', pronunciation_en='SEE', pronunciation_zh='xī', updated_at=unixepoch() WHERE id='vocab_es_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/no/', pronunciation_en='NOH', pronunciation_zh='nōu', updated_at=unixepoch() WHERE id='vocab_es_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/aeɾoˈpweɾto/', pronunciation_en='ah-eh-roh-PWEHR-toh', pronunciation_zh='ā-ē-rō-pwé-ěr-tō', updated_at=unixepoch() WHERE id='vocab_es_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/biˈʝete/', pronunciation_en='bee-YEH-teh', pronunciation_zh='bī-yé-tè', updated_at=unixepoch() WHERE id='vocab_es_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈpweɾta/', pronunciation_en='PWEHR-tah', pronunciation_zh='pwé-ěr-tā', updated_at=unixepoch() WHERE id='vocab_es_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈdonde esˈta/', pronunciation_en='DOHN-deh es-TAH', pronunciation_zh='dōn-dè ē-sī-tā', updated_at=unixepoch() WHERE id='vocab_es_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/isˈkjeɾða/', pronunciation_en='ees-KYEHR-dah', pronunciation_zh='īs-kyé-ěr-dā', updated_at=unixepoch() WHERE id='vocab_es_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/deˈɾetʃa/', pronunciation_en='deh-REH-cha', pronunciation_zh='dé-ré-chā', updated_at=unixepoch() WHERE id='vocab_es_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈtoðo ˈrekto/', pronunciation_en='TOH-doh REK-toh', pronunciation_zh='tōu-dōu léi-kè-tōu', updated_at=unixepoch() WHERE id='vocab_es_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈbaɲo/', pronunciation_en='BAH-nyoh', pronunciation_zh='bā-nyóu', updated_at=unixepoch() WHERE id='vocab_es_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/meˈnu/', pronunciation_en='meh-NOO', pronunciation_zh='méi-nǔ', updated_at=unixepoch() WHERE id='vocab_es_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈaɣwa/', pronunciation_en='AH-gwah', pronunciation_zh='ā-guā', updated_at=unixepoch() WHERE id='vocab_es_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/βexe taˈɾjano/', pronunciation_en='beh-HEH-tah-ree-AH-noh', pronunciation_zh='bēi-hēi-tā-lǐ-yā-nuò', updated_at=unixepoch() WHERE id='vocab_es_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/la ˈkwenta poɾ faˈβoɾ/', pronunciation_en='lah KWEN-tah por fah-VOR', pronunciation_zh='lā kuén-tā pōr fā-bōr', updated_at=unixepoch() WHERE id='vocab_es_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkwanto ˈkwesta/', pronunciation_en='KWAHN-toh KWEHS-tah', pronunciation_zh='kuāntō kuēi-s tā', updated_at=unixepoch() WHERE id='vocab_es_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/efekˈtiβo/', pronunciation_en='eh-fehk-TEE-boh', pronunciation_zh='āi-fēi-kē-dì-bō', updated_at=unixepoch() WHERE id='vocab_es_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/taɾˈxeta/', pronunciation_en='tar-HEH-tah', pronunciation_zh='tā-ěr-héi-tā', updated_at=unixepoch() WHERE id='vocab_es_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/reˈsiβo/', pronunciation_en='reh-SEE-boh', pronunciation_zh='lèi-xī-bō', updated_at=unixepoch() WHERE id='vocab_es_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/aˈʝuða/', pronunciation_en='ah-YOO-dah', pronunciation_zh='ā-yóu-dā', updated_at=unixepoch() WHERE id='vocab_es_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/esˈtoj peɾˈðiðo/', pronunciation_en='ehs-TOY pehr-DEE-doh', pronunciation_zh='āi-sī-tuōi pēi-ěr-dí-dō', updated_at=unixepoch() WHERE id='vocab_es_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈmeðiko/', pronunciation_en='MEH-dee-koh', pronunciation_zh='mēi-dí-kō', updated_at=unixepoch() WHERE id='vocab_es_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/poliˈsia/', pronunciation_en='poh-lee-SEE-ah', pronunciation_zh='bō-lǐ-xī-yā', updated_at=unixepoch() WHERE id='vocab_es_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/koɲɲitɕiɰa/', pronunciation_en='KON-nee-chee-wah', pronunciation_zh='kōng-ní-qí-wā', updated_at=unixepoch() WHERE id='vocab_ja_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/oneɡai ɕimasɯ/', pronunciation_en='oh-neh-GUY SHEE-mah-su', pronunciation_zh='ō-né-gāi xī-mā-sī', updated_at=unixepoch() WHERE id='vocab_ja_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/aɾiɡatoː ɡozaimasɯ/', pronunciation_en='ah-ree-gah-TOH goh-zah-ee-MAH-su', pronunciation_zh='ā-lǐ-gā-tōu gōu-zāi-mā-sī', updated_at=unixepoch() WHERE id='vocab_ja_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/sɯmimasẽɴ/', pronunciation_en='soo-mee-mah-SEN', pronunciation_zh='sū-mī-mā-sēn', updated_at=unixepoch() WHERE id='vocab_ja_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɰataɕi wa … desɯ/', pronunciation_en='wah-TAH-shee wah … DEH-su', pronunciation_zh='wā-tā-xī wā … dé-sī', updated_at=unixepoch() WHERE id='vocab_ja_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/… kaɾa kimaɕita/', pronunciation_en='… KAH-rah kee-mah-SHEE-tah', pronunciation_zh='… kā-lā qǐ-mā-xī-tā', updated_at=unixepoch() WHERE id='vocab_ja_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/hai/', pronunciation_en='HIGH', pronunciation_zh='hāi', updated_at=unixepoch() WHERE id='vocab_ja_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/iːe/', pronunciation_en='EE-eh', pronunciation_zh='yī-yē', updated_at=unixepoch() WHERE id='vocab_ja_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kɯːkoː/', pronunciation_en='KOO-koh', pronunciation_zh='kū-kōng', updated_at=unixepoch() WHERE id='vocab_ja_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kippɯ/', pronunciation_en='KEEP-poo', pronunciation_zh='qǐ-pū', updated_at=unixepoch() WHERE id='vocab_ja_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/toːdʑoːɡɯtɕi/', pronunciation_en='TOH-joh-GOO-chee', pronunciation_zh='tōng-jiōng-gū-qī', updated_at=unixepoch() WHERE id='vocab_ja_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/… wa doko desɯ ka/', pronunciation_en='… wah DOH-koh DEH-su kah', pronunciation_zh='… wā dō-kō dé-sī kā', updated_at=unixepoch() WHERE id='vocab_ja_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/çidaɾi/', pronunciation_en='hee-DAH-ree', pronunciation_zh='xǐ-dā-lǐ', updated_at=unixepoch() WHERE id='vocab_ja_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/miɡi/', pronunciation_en='MEE-gee', pronunciation_zh='mī-gī', updated_at=unixepoch() WHERE id='vocab_ja_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/massɯɡɯ/', pronunciation_en='mahs-SOO-goo', pronunciation_zh='mā-sū-gū', updated_at=unixepoch() WHERE id='vocab_ja_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/toːɾe/', pronunciation_en='TOH-reh', pronunciation_zh='tō-lè', updated_at=unixepoch() WHERE id='vocab_ja_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/meɲːɯː/', pronunciation_en='men-YOO', pronunciation_zh='ményū', updated_at=unixepoch() WHERE id='vocab_ja_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mizɯ/', pronunciation_en='MEE-zoo', pronunciation_zh='mī-zū', updated_at=unixepoch() WHERE id='vocab_ja_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/bedʑitaɾiaɴ/', pronunciation_en='beh-jee-TAH-ree-ahn', pronunciation_zh='bèi-jī-tā-lián', updated_at=unixepoch() WHERE id='vocab_ja_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/okaikeː o oneɡai ɕimasɯ/', pronunciation_en='oh-kai-KAY oh-oh-neh-GUY shee-MAHS', pronunciation_zh='ō-kāi-kēi ō ō-nē-gāi xī-mā-sū', updated_at=unixepoch() WHERE id='vocab_ja_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ikɯɾa desɯ ka/', pronunciation_en='ee-koo-RAH deh-soo kah', pronunciation_zh='yī-kū-lā dé-sū kā', updated_at=unixepoch() WHERE id='vocab_ja_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɡeŋdʑiɴ/', pronunciation_en='GEN-jeen', pronunciation_zh='gēng-jīn', updated_at=unixepoch() WHERE id='vocab_ja_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kaːdo/', pronunciation_en='KAH-doh', pronunciation_zh='kā-dō', updated_at=unixepoch() WHERE id='vocab_ja_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɾeɕiːto/', pronunciation_en='reh-SHEE-toh', pronunciation_zh='lè-xī-tō', updated_at=unixepoch() WHERE id='vocab_ja_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tasɯkete/', pronunciation_en='tah-soo-KEH-teh', pronunciation_zh='tā-sū-kē-tè', updated_at=unixepoch() WHERE id='vocab_ja_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mitɕi ni mayoimasɯta/', pronunciation_en='MEE-chee nee mah-yoh-ee-MAHS-tah', pronunciation_zh='mī-qī nī mā-yō-yī-mā-sū-tā', updated_at=unixepoch() WHERE id='vocab_ja_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/iɕa/', pronunciation_en='EE-shah', pronunciation_zh='yī-xiā', updated_at=unixepoch() WHERE id='vocab_ja_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/keːsatsɯ/', pronunciation_en='KAY-saht-soo', pronunciation_zh='kēi-sā-tsū', updated_at=unixepoch() WHERE id='vocab_ja_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/an.jʌŋ.ha.se.jo/', pronunciation_en='ahn-YUNG-ha-seh-YOH', pronunciation_zh='ān-yōng-hā-sē-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pu.tʰa.kʰam.ni.da/', pronunciation_en='poo-TAHK-hahm-NEE-dah', pronunciation_zh='pū-tā-khām-ní-dā', updated_at=unixepoch() WHERE id='vocab_ko_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kam.sa.ham.ni.da/', pronunciation_en='kahm-SAH-hahm-NEE-dah', pronunciation_zh='kām-sā-hām-ní-dā', updated_at=unixepoch() WHERE id='vocab_ko_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɕil.lje.ham.ni.da/', pronunciation_en='shil-LYEH-hahm-NEE-dah', pronunciation_zh='xǐ-liē-hām-ní-dā', updated_at=unixepoch() WHERE id='vocab_ko_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕe i.rɯ.mɯn ... im.ni.da/', pronunciation_en='JEH ee-reum-un ... IM-nee-dah', pronunciation_zh='jē ī-rěm-ǔn īm-nē-dā', updated_at=unixepoch() WHERE id='vocab_ko_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕʌ.nɯn ... e.sʌ wa.s͈ʌ.jo/', pronunciation_en='JUH-neun ... eh-suh wah-SSUH-yoh', pronunciation_zh='jǔ-něn ē-sǔ wā-sǔ-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ne/', pronunciation_en='NEH', pronunciation_zh='né', updated_at=unixepoch() WHERE id='vocab_ko_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a.ni.jo/', pronunciation_en='ah-nee-YOH', pronunciation_zh='ā-ní-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/koŋ.haŋ/', pronunciation_en='KONG-hahng', pronunciation_zh='kōng-hāng', updated_at=unixepoch() WHERE id='vocab_ko_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pʰjɔ/', pronunciation_en='PYUH', pronunciation_zh='piǎo', updated_at=unixepoch() WHERE id='vocab_ko_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tʰap̚.sɯŋ.ɡu/', pronunciation_en='TAHP-seung-goo', pronunciation_zh='tǎp-sīng-gōu', updated_at=unixepoch() WHERE id='vocab_ko_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/... ɯn ʌ.di.je.jo/', pronunciation_en='... eun uh-dee-YEH-yoh', pronunciation_zh='ēn ā-dí-yé-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/wɛn.tɕ͈ok̚/', pronunciation_en='WEN-jjok', pronunciation_zh='wēn-jjok', updated_at=unixepoch() WHERE id='vocab_ko_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/o.ɾɯn.tɕ͈ok̚/', pronunciation_en='oh-reun-JJOK', pronunciation_zh='ō-rēn-jjok', updated_at=unixepoch() WHERE id='vocab_ko_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕ͈uk̚ ka.se.jo/', pronunciation_en='JJOOK kah-SEH-yoh', pronunciation_zh='jū kǎ sāi yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/hwa.dʑaŋ.ɕil/', pronunciation_en='hwa-JAHNG-shil', pronunciation_zh='huā-zhǎng-xǐ', updated_at=unixepoch() WHERE id='vocab_ko_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/me.nju/', pronunciation_en='MEH-nyoo', pronunciation_zh='méi niū', updated_at=unixepoch() WHERE id='vocab_ko_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mul/', pronunciation_en='mool', pronunciation_zh='mǔl', updated_at=unixepoch() WHERE id='vocab_ko_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tɕʰe.ɕik̚/', pronunciation_en='CHEH-shik', pronunciation_zh='qié xī', updated_at=unixepoch() WHERE id='vocab_ko_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kje.san.he dʑu.se.jo/', pronunciation_en='kyeh-SAHN-heh joo-SEH-yoh', pronunciation_zh='jiē-sān-hē zhū-sāi-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʌl.ma.je.jo/', pronunciation_en='uhl-MAH-yeh-yoh', pronunciation_zh='ǒl-mǎ-yē-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/hjʌn.ɡɯm/', pronunciation_en='hyun-GUM', pronunciation_zh='xiǎn-gǔm', updated_at=unixepoch() WHERE id='vocab_ko_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kʰa.dɯ/', pronunciation_en='KAH-deu', pronunciation_zh='kǎ-dǔ', updated_at=unixepoch() WHERE id='vocab_ko_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/jʌŋ.su.dʑɯŋ/', pronunciation_en='YUNG-soo-jeung', pronunciation_zh='yǒng-sū-zhǔng', updated_at=unixepoch() WHERE id='vocab_ko_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/to.wa.dʑu.se.jo/', pronunciation_en='doh-wah-JOO-seh-yoh', pronunciation_zh='dō-wǎ-zhū-sāi-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ki.rɯl i.rʌs.sʌ.jo/', pronunciation_en='kee-reul ee-ROSS-suh-yoh', pronunciation_zh='jī-lǔ yī-luò-sǒ-yō', updated_at=unixepoch() WHERE id='vocab_ko_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɰi.sa/', pronunciation_en='UI-sah', pronunciation_zh='yī-sǎ', updated_at=unixepoch() WHERE id='vocab_ko_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kjʌŋ.tɕʰal/', pronunciation_en='KYUNG-chahl', pronunciation_zh='jǐng-chǎl', updated_at=unixepoch() WHERE id='vocab_ko_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/bɔ̃.ʒuʁ/', pronunciation_en='bohn-ZHOOR', pronunciation_zh='bōng-zhūr', updated_at=unixepoch() WHERE id='vocab_fr_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/sil vu plɛ/', pronunciation_en='sill voo PLEH', pronunciation_zh='sīl vū plē', updated_at=unixepoch() WHERE id='vocab_fr_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mɛʁ.si/', pronunciation_en='mehr-SEE', pronunciation_zh='mèr-xī', updated_at=unixepoch() WHERE id='vocab_fr_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɛks.ky.ze mwa/', pronunciation_en='ehks-kyoo-ZAY MWAH', pronunciation_zh='èk-sǖ-zé mwā', updated_at=unixepoch() WHERE id='vocab_fr_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʒə ma.pɛl/', pronunciation_en='zhuh mah-PELL', pronunciation_zh='zhē mā-pèl', updated_at=unixepoch() WHERE id='vocab_fr_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʒə vjɛ̃ də/', pronunciation_en='zhuh VYEN duh', pronunciation_zh='zhē wéi-ān dé', updated_at=unixepoch() WHERE id='vocab_fr_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/wi/', pronunciation_en='WEE', pronunciation_zh='wī', updated_at=unixepoch() WHERE id='vocab_fr_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nɔ̃/', pronunciation_en='NOHN', pronunciation_zh='nōng', updated_at=unixepoch() WHERE id='vocab_fr_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a.e.ʁɔ.pɔʁ/', pronunciation_en='ah-ay-roh-POR', pronunciation_zh='ā-āi-rō-pōr', updated_at=unixepoch() WHERE id='vocab_fr_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/bi.jɛ/', pronunciation_en='bee-YEH', pronunciation_zh='bī-yè', updated_at=unixepoch() WHERE id='vocab_fr_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pɔʁt/', pronunciation_en='PORT', pronunciation_zh='pōr-tè', updated_at=unixepoch() WHERE id='vocab_fr_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/u ɛ/', pronunciation_en='oo EH', pronunciation_zh='ū è', updated_at=unixepoch() WHERE id='vocab_fr_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a ɡoʃ/', pronunciation_en='ah GOHSH', pronunciation_zh='ā gō-shī', updated_at=unixepoch() WHERE id='vocab_fr_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a dʁwat/', pronunciation_en='ah DRWAHT', pronunciation_zh='ā dé-rwā-tè', updated_at=unixepoch() WHERE id='vocab_fr_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tu dʁwa/', pronunciation_en='TOO DRWAH', pronunciation_zh='tū dī-ruā', updated_at=unixepoch() WHERE id='vocab_fr_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/twa.lɛt/', pronunciation_en='TWAH-LET', pronunciation_zh='tuā-lài', updated_at=unixepoch() WHERE id='vocab_fr_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mə.ny/', pronunciation_en='muh-NOO', pronunciation_zh='mō-nǚ', updated_at=unixepoch() WHERE id='vocab_fr_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/o/', pronunciation_en='OH', pronunciation_zh='ō', updated_at=unixepoch() WHERE id='vocab_fr_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ve.ʒe.ta.ʁjɛ̃/', pronunciation_en='veh-zhay-tah-RYAN', pronunciation_zh='wéi-zhāi-tā-rāng', updated_at=unixepoch() WHERE id='vocab_fr_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/la.di.sjɔ̃ sil vu plɛ/', pronunciation_en='lah-dee-SYON, SEEL voo PLAY', pronunciation_zh='lā-dī-xióng xīl wū pǔlǎi', updated_at=unixepoch() WHERE id='vocab_fr_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kɔ̃.bjɛ̃ sa kut/', pronunciation_en='kohm-BYAN sah KOOT', pronunciation_zh='kōng-biāng sā kūt', updated_at=unixepoch() WHERE id='vocab_fr_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɛs.pɛs/', pronunciation_en='ess-PESS', pronunciation_zh='ài-sī-pài-sī', updated_at=unixepoch() WHERE id='vocab_fr_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kaʁt/', pronunciation_en='KART', pronunciation_zh='kǎr-tè', updated_at=unixepoch() WHERE id='vocab_fr_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʁə.sy/', pronunciation_en='ruh-SOO', pronunciation_zh='rā-sǖ', updated_at=unixepoch() WHERE id='vocab_fr_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/o sə.kuʁ/', pronunciation_en='OH suh-KOOR', pronunciation_zh='ō sī-kū''ěr', updated_at=unixepoch() WHERE id='vocab_fr_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʒə sɥi pɛʁ.dy/', pronunciation_en='zhuh SWEE pair-DEW', pronunciation_zh='rǎ xǖ pài''ěr-dǖ', updated_at=unixepoch() WHERE id='vocab_fr_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/med.sɛ̃/', pronunciation_en='med-SAN', pronunciation_zh='mài-dāng', updated_at=unixepoch() WHERE id='vocab_fr_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pɔ.lis/', pronunciation_en='poh-LEES', pronunciation_zh='pō-lì-sī', updated_at=unixepoch() WHERE id='vocab_fr_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/haˈloː/', pronunciation_en='hah-LOH', pronunciation_zh='hā-lō', updated_at=unixepoch() WHERE id='vocab_de_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈbɪtə/', pronunciation_en='BIT-tuh', pronunciation_zh='bì-tuh', updated_at=unixepoch() WHERE id='vocab_de_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈdaŋkə/', pronunciation_en='DAHNG-kuh', pronunciation_zh='dāng-kē', updated_at=unixepoch() WHERE id='vocab_de_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɛntˈʃʊldɪɡʊŋ/', pronunciation_en='ent-SHOOL-di-goong', pronunciation_zh='ēnt-shūl-dí-gūng', updated_at=unixepoch() WHERE id='vocab_de_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɪç ˈhaɪ̯sə/', pronunciation_en='ikh HIGH-suh', pronunciation_zh='íkh hāi-sē', updated_at=unixepoch() WHERE id='vocab_de_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɪç ˈkɔmə aʊ̯s/', pronunciation_en='ikh KOM-muh OWS', pronunciation_zh='íkh kǒ-mē āo-sī', updated_at=unixepoch() WHERE id='vocab_de_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/jaː/', pronunciation_en='YAH', pronunciation_zh='yā', updated_at=unixepoch() WHERE id='vocab_de_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/naɪ̯n/', pronunciation_en='NINE', pronunciation_zh='nài-n', updated_at=unixepoch() WHERE id='vocab_de_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈfluːkˌhaːfn̩/', pronunciation_en='FLOOK-hahn-fn', pronunciation_zh='flūg-hān-fn', updated_at=unixepoch() WHERE id='vocab_de_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈfaːɐ̯ˌkaʁtə/', pronunciation_en='FAHR-kar-tuh', pronunciation_zh='fā-er-kā-er-tuh', updated_at=unixepoch() WHERE id='vocab_de_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈfluːkˌʃtaɪ̯k/', pronunciation_en='FLOOK-shtyke', pronunciation_zh='flūg-shtāi-k', updated_at=unixepoch() WHERE id='vocab_de_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/voː ɪst/', pronunciation_en='VOH ist', pronunciation_zh='wō yīst', updated_at=unixepoch() WHERE id='vocab_de_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/lɪŋks/', pronunciation_en='LINKS', pronunciation_zh='lìngks', updated_at=unixepoch() WHERE id='vocab_de_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʁɛçts/', pronunciation_en='REKHTS', pronunciation_zh='ruì-kè-tsī', updated_at=unixepoch() WHERE id='vocab_de_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɡəˈʁaːdəˌʔaʊ̯s/', pronunciation_en='guh-RAH-duh-owss', pronunciation_zh='gē-rā-dē-ào-sī', updated_at=unixepoch() WHERE id='vocab_de_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/toaˈlɛtə/', pronunciation_en='t wah-LET-tuh', pronunciation_zh='tuō-a-lèi-tè', updated_at=unixepoch() WHERE id='vocab_de_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈʃpaɪ̯zəˌkaʁtə/', pronunciation_en='SHPY-zuh-kar-tuh', pronunciation_zh='shpāi-zē-kǎr-tè', updated_at=unixepoch() WHERE id='vocab_de_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈvasɐ/', pronunciation_en='VAH-suh', pronunciation_zh='vā-sā', updated_at=unixepoch() WHERE id='vocab_de_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/veɡeˈtaːʁɪʃ/', pronunciation_en='veh-guh-TAH-rish', pronunciation_zh='wē-gē-tā-rī-shī', updated_at=unixepoch() WHERE id='vocab_de_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/diː ˈʁɛçnʊŋ ˈbɪtə/', pronunciation_en='dee REKH-noong BIT-tuh', pronunciation_zh='dī-rèi-kē-nùng bǐ-tè', updated_at=unixepoch() WHERE id='vocab_de_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/viː fiːl ˈkɔstət das/', pronunciation_en='vee feel KOS-tut dahss', pronunciation_zh='wē-fīl kǒ-sè-tè dā-sī', updated_at=unixepoch() WHERE id='vocab_de_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈbaːɐ̯ɡɛlt/', pronunciation_en='BAH-uh-gelt', pronunciation_zh='bā-a-gēl-tè', updated_at=unixepoch() WHERE id='vocab_de_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkaʁtə/', pronunciation_en='KAR-tuh', pronunciation_zh='kǎr-tè', updated_at=unixepoch() WHERE id='vocab_de_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkvɪtʊŋ/', pronunciation_en='KVIH-toong', pronunciation_zh='Kǔi-tung', updated_at=unixepoch() WHERE id='vocab_de_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈhɪlfə/', pronunciation_en='HIL-fuh', pronunciation_zh='hǐl-fā', updated_at=unixepoch() WHERE id='vocab_de_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɪç ˈhaːbə mɪç fɛɐ̯ˈlaʊ̯fn̩/', pronunciation_en='ikh HAH-buh mikh fehr-LOW-fn', pronunciation_zh='yī hā-bā mǐ-chī fē-lāo-fēn', updated_at=unixepoch() WHERE id='vocab_de_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/aːɐ̯tst/', pronunciation_en='AHR-tst', pronunciation_zh='Ā-er-tst', updated_at=unixepoch() WHERE id='vocab_de_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/poliˈtsaɪ̯/', pronunciation_en='poh-lee-TSY', pronunciation_zh='pō-lī-TSĀI', updated_at=unixepoch() WHERE id='vocab_de_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈzdrastvʊjtʲe/', pronunciation_en='ZDRAST-vuy-teh', pronunciation_zh='zī-dá-sī-twéi', updated_at=unixepoch() WHERE id='vocab_ru_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pɐˈʐalʊstə/', pronunciation_en='puh-ZHAH-loo-stuh', pronunciation_zh='pà-zhā-lù-sī-tǎ', updated_at=unixepoch() WHERE id='vocab_ru_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/spɐˈsʲibə/', pronunciation_en='spuh-SEE-buh', pronunciation_zh='sī-pà-xī-bó', updated_at=unixepoch() WHERE id='vocab_ru_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɪzvʲɪˈnʲitʲe/', pronunciation_en='iz-vee-NEE-tyeh', pronunciation_zh='yīz-wéi-ní-dí', updated_at=unixepoch() WHERE id='vocab_ru_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mʲɪˈnʲa zəˈvut/', pronunciation_en='mee-NYAH zuh-VOOT', pronunciation_zh='mí-ní-yā zā-wù-tè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ja ɪz/', pronunciation_en='yah iz', pronunciation_zh='yā yīz', updated_at=unixepoch() WHERE id='vocab_ru_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/da/', pronunciation_en='DAH', pronunciation_zh='dā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nʲet/', pronunciation_en='NYET', pronunciation_zh='niè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɐɪ̯ɪˈport/', pronunciation_en='ah-ee-PORT', pronunciation_zh='ā-yī-pō-tè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/bʲɪˈlʲet/', pronunciation_en='bee-LYET', pronunciation_zh='bǐ-liè-tè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈvɨxət/', pronunciation_en='VUH-khut', pronunciation_zh='wéi-hā-tè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɡdʲe/', pronunciation_en='GDYEH', pronunciation_zh='gǔ-diē', updated_at=unixepoch() WHERE id='vocab_ru_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nɐˈlʲevə/', pronunciation_en='nuh-LYEH-vuh', pronunciation_zh='nà-liē-wā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nəˈpravə/', pronunciation_en='nuh-PRAH-vuh', pronunciation_zh='nà-pǔ-lā-wā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈprʲamə/', pronunciation_en='PRYAH-muh', pronunciation_zh='pǔ-lā-mó', updated_at=unixepoch() WHERE id='vocab_ru_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tʊɐˈlʲet/', pronunciation_en='too-ah-LYET', pronunciation_zh='tū-ā-liè-tè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mʲɪˈnʲu/', pronunciation_en='mee-NYOO', pronunciation_zh='mǐ-niǔ', updated_at=unixepoch() WHERE id='vocab_ru_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/vɐˈda/', pronunciation_en='vuh-DAH', pronunciation_zh='wǔ-dā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/vʲɪɡʲɪtɐrʲɪˈanskʲɪj/', pronunciation_en='vih-gih-tah-ree-AHN-skee', pronunciation_zh='wí-gí-tā-lǐ-āns-kī', updated_at=unixepoch() WHERE id='vocab_ru_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɕːot pɐˈʐalʊjstə/', pronunciation_en='SHYOT puh-ZHAH-loo-stuh', pronunciation_zh='xiōt pǔ-zhā-lū-sī-tā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈskolʲkə ˈstoɪt/', pronunciation_en='SKOHL-kuh STOH-eet', pronunciation_zh='sī-kōu-lǔ sī-tōu-yī-tè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nɐˈlʲit͡ɕnɨjə/', pronunciation_en='nuh-LEECH-nuh-yuh', pronunciation_zh='nǔ-lì-qí-nǔ-yā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkartə/', pronunciation_en='KAR-tuh', pronunciation_zh='kǎ-ěr-tā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/t͡ɕek/', pronunciation_en='CHEK', pronunciation_zh='qiē-kè', updated_at=unixepoch() WHERE id='vocab_ru_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pəmɐˈɡʲitʲe/', pronunciation_en='puh-muh-GHEE-tyeh', pronunciation_zh='pǔ-mǔ-gēi-tí-ye', updated_at=unixepoch() WHERE id='vocab_ru_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/jɐ zɐblʊˈdʲilsə/', pronunciation_en='yuh zuh-bloo-DEEL-suh', pronunciation_zh='yǔ zǔ-bù-dí-ěr-sā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/vrat͡ɕ/', pronunciation_en='VRACH', pronunciation_zh='wǔ-rā-ch', updated_at=unixepoch() WHERE id='vocab_ru_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pɐˈlʲit͡sɨjə/', pronunciation_en='puh-LEE-tsuh-yuh', pronunciation_zh='pū-lí-tsī-yā', updated_at=unixepoch() WHERE id='vocab_ru_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈtʃa.o/', pronunciation_en='CHAH-oh', pronunciation_zh='qiā-o', updated_at=unixepoch() WHERE id='vocab_it_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/per faˈvo.re/', pronunciation_en='pehr fa-VOH-reh', pronunciation_zh='pēr fǎ-wó-rè', updated_at=unixepoch() WHERE id='vocab_it_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈɡrat.tsje/', pronunciation_en='GRAHT-tsyeh', pronunciation_zh='gē-lā-cī-yē', updated_at=unixepoch() WHERE id='vocab_it_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mi ˈsku.zi/', pronunciation_en='mee SKOO-zee', pronunciation_zh='mī sī-kū-zī', updated_at=unixepoch() WHERE id='vocab_it_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mi ˈkja.mo/', pronunciation_en='mee KYA-moh', pronunciation_zh='mī qiā-mō', updated_at=unixepoch() WHERE id='vocab_it_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈvɛŋ.ɡo da/', pronunciation_en='VENG-goh dah', pronunciation_zh='wén-gō dā', updated_at=unixepoch() WHERE id='vocab_it_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/si/', pronunciation_en='SEE', pronunciation_zh='xī', updated_at=unixepoch() WHERE id='vocab_it_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/no/', pronunciation_en='NOH', pronunciation_zh='nuō', updated_at=unixepoch() WHERE id='vocab_it_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a.e.roˈpɔr.to/', pronunciation_en='ah-eh-roh-POR-toh', pronunciation_zh='ā-ē-rō-pōr-tō', updated_at=unixepoch() WHERE id='vocab_it_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/biʎˈʎet.to/', pronunciation_en='bee-LYET-toh', pronunciation_zh='bī-liè-tō', updated_at=unixepoch() WHERE id='vocab_it_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈu.ʃi.ta/', pronunciation_en='OO-shee-tah', pronunciation_zh='ū-xī-tā', updated_at=unixepoch() WHERE id='vocab_it_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/doˈvɛ/', pronunciation_en='doh-VEH', pronunciation_zh='dō-wèi', updated_at=unixepoch() WHERE id='vocab_it_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a siˈni.stra/', pronunciation_en='ah see-NEE-strah', pronunciation_zh='ā xī-nī-sī-lā', updated_at=unixepoch() WHERE id='vocab_it_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a ˈde.stra/', pronunciation_en='ah DES-trah', pronunciation_zh='ā dé-sī-lā', updated_at=unixepoch() WHERE id='vocab_it_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈsɛm.pre ˈdrit.to/', pronunciation_en='SEM-preh DREET-toh', pronunciation_zh='sēn-pǔ-léi zhī-tōu', updated_at=unixepoch() WHERE id='vocab_it_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈbaɲ.ɲo/', pronunciation_en='BAHN-nyoh', pronunciation_zh='bā-nyóu', updated_at=unixepoch() WHERE id='vocab_it_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/meˈnu/', pronunciation_en='meh-NOO', pronunciation_zh='mē-Nǔ', updated_at=unixepoch() WHERE id='vocab_it_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈak.kwa/', pronunciation_en='AHK-kwah', pronunciation_zh='ā-kǔā', updated_at=unixepoch() WHERE id='vocab_it_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ve.dʒe.taˈrja.no/', pronunciation_en='veh-jeh-tah-RYAH-noh', pronunciation_zh='wéi-jié-tǎ-Liā-nuō', updated_at=unixepoch() WHERE id='vocab_it_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/il ˈkon.to per faˈvo.re/', pronunciation_en='eel KON-toh pehr fa-VOH-reh', pronunciation_zh='yīl KŌNG-tuō pèh fǎ-WŌ-léi', updated_at=unixepoch() WHERE id='vocab_it_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkwan.to ˈkɔ.sta/', pronunciation_en='KWAHN-toh KAW-stah', pronunciation_zh='kuāng-tuō KŌU-sī-tǎ', updated_at=unixepoch() WHERE id='vocab_it_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/konˈtan.ti/', pronunciation_en='kon-TAHN-tee', pronunciation_zh='kōng-TĀN-dì', updated_at=unixepoch() WHERE id='vocab_it_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkar.ta/', pronunciation_en='KAR-tah', pronunciation_zh='kǎr-tǎ', updated_at=unixepoch() WHERE id='vocab_it_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ri.tʃeˈvu.ta/', pronunciation_en='ree-cheh-VOO-tah', pronunciation_zh='lǐ-qié-WǓ-tǎ', updated_at=unixepoch() WHERE id='vocab_it_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/aˈju.to/', pronunciation_en='ah-YOO-toh', pronunciation_zh='ā-YŪ-tuō', updated_at=unixepoch() WHERE id='vocab_it_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mi ˈso.no ˈpɛr.so/', pronunciation_en='mee SOH-noh PEHR-soh', pronunciation_zh='mī SŌ-nuō PÉR-suō', updated_at=unixepoch() WHERE id='vocab_it_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈmɛ.di.ko/', pronunciation_en='MEH-dee-koh', pronunciation_zh='mēi-dì-kō', updated_at=unixepoch() WHERE id='vocab_it_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/po.liˈtsi.a/', pronunciation_en='poh-lee-TSEE-ah', pronunciation_zh='pō-lǐ-ZĪ-yǎ', updated_at=unixepoch() WHERE id='vocab_it_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/oˈla/', pronunciation_en='oh-LAH', pronunciation_zh='òu-lá', updated_at=unixepoch() WHERE id='vocab_pt_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/poʁ faˈvoʁ/', pronunciation_en='pohr fah-VOR', pronunciation_zh='pōr fā-vóěr', updated_at=unixepoch() WHERE id='vocab_pt_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/obɾiˈɡadu/', pronunciation_en='oh-bree-GAH-doo', pronunciation_zh='òu-bǔ-lí-gá-dù', updated_at=unixepoch() WHERE id='vocab_pt_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kõ liˈsẽsɐ/', pronunciation_en='kohng lee-SEN-sah', pronunciation_zh='kǒng lí-sēng-sā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈʃɐmu mi/', pronunciation_en='SHAH-moo mee', pronunciation_zh='shā-mù mī', updated_at=unixepoch() WHERE id='vocab_pt_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/soʊ dʒi/', pronunciation_en='SOH-jee', pronunciation_zh='sōu-jī', updated_at=unixepoch() WHERE id='vocab_pt_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/sĩ/', pronunciation_en='SEENG', pronunciation_zh='xīng', updated_at=unixepoch() WHERE id='vocab_pt_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nɐ̃w/', pronunciation_en='NOWN', pronunciation_zh='nǎo', updated_at=unixepoch() WHERE id='vocab_pt_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a.eɾoˈpɔʁtu/', pronunciation_en='ah-eh-roh-POR-too', pronunciation_zh='ā-ē-luō-póěr-tù', updated_at=unixepoch() WHERE id='vocab_pt_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/biˈʎɛtʃi/', pronunciation_en='bee-LYEH-chee', pronunciation_zh='bǐ-lí-ēi-chī', updated_at=unixepoch() WHERE id='vocab_pt_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈpɔʁtɐ/', pronunciation_en='POR-tah', pronunciation_zh='póěr-tā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈõdʒi ˈfikɐ/', pronunciation_en='ON-jee FEE-kah', pronunciation_zh='ǒng-jī fī-kā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a esˈkɛʁdɐ/', pronunciation_en='ah es-KEHR-dah', pronunciation_zh='ā ēis-kéěr-dā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a dʒiˈɾeɪtɐ/', pronunciation_en='ah jee-RAY-tah', pronunciation_zh='ā jī-léi-tā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈsẽpɾi ẽ ˈfɾẽtʃi/', pronunciation_en='SEM-preh ehng FREN-chee', pronunciation_zh='sēng-pēi ēng fēng-chí', updated_at=unixepoch() WHERE id='vocab_pt_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkazɐ dʒi ˈbɐɲu/', pronunciation_en='KAH-zah jee BAH-nyoo', pronunciation_zh='kā-zā jī bā-nyú', updated_at=unixepoch() WHERE id='vocab_pt_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/meˈnu/', pronunciation_en='meh-NOO', pronunciation_zh='méi-nú', updated_at=unixepoch() WHERE id='vocab_pt_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈaɡwɐ/', pronunciation_en='AH-gwah', pronunciation_zh='ā-gwā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/veʒetɐɾiˈɐnu/', pronunciation_en='veh-zheh-tah-ree-AH-noo', pronunciation_zh='wéi-zhē-tā-lǐ-ā-nú', updated_at=unixepoch() WHERE id='vocab_pt_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/a ˈkõtɐ poʁ faˈvoʁ/', pronunciation_en='ah KON-tah por fah-VOR', pronunciation_zh='ā kǒng-tā pōr fā-vóu', updated_at=unixepoch() WHERE id='vocab_pt_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈkwɐ̃tu ˈkustɐ/', pronunciation_en='KWAN-too KOOS-tah', pronunciation_zh='kuāng-tú kū-sī-tā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/dʒiˈɲejɾu/', pronunciation_en='jee-NYAY-roo', pronunciation_zh='jī-nyé-lú', updated_at=unixepoch() WHERE id='vocab_pt_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kaʁˈtɐ̃w/', pronunciation_en='kar-TAWN', pronunciation_zh='kā-tāng', updated_at=unixepoch() WHERE id='vocab_pt_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʁeˈsibu/', pronunciation_en='heh-SEE-boo', pronunciation_zh='hē-sí-bū', updated_at=unixepoch() WHERE id='vocab_pt_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/soˈkoʁu/', pronunciation_en='soh-KOH-hoo', pronunciation_zh='sō-kō-hú', updated_at=unixepoch() WHERE id='vocab_pt_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/esˈtow peʁˈdʒidu/', pronunciation_en='ehs-TOW pehr-JEE-doo', pronunciation_zh='ē-sī-tóu pē-jí-dū', updated_at=unixepoch() WHERE id='vocab_pt_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈmɛdʒiku/', pronunciation_en='MEH-jee-koo', pronunciation_zh='méi-jí-kū', updated_at=unixepoch() WHERE id='vocab_pt_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/poˈlisjɐ/', pronunciation_en='poh-LEE-see-ah', pronunciation_zh='pō-lí-xiā', updated_at=unixepoch() WHERE id='vocab_pt_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈmar.ħa.ban/', pronunciation_en='MAR-ha-ban', pronunciation_zh='Mǎr-hā-bān', updated_at=unixepoch() WHERE id='vocab_ar_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/min ˈfadˤ.lik/', pronunciation_en='min FADH-lik', pronunciation_zh='mǐn Fǎd-lǐk', updated_at=unixepoch() WHERE id='vocab_ar_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈʃuk.ran/', pronunciation_en='SHOOK-ran', pronunciation_zh='Shū-kè-rán', updated_at=unixepoch() WHERE id='vocab_ar_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈʕuð.ran/', pronunciation_en='OODH-ran', pronunciation_zh='Wū-dhā-rán', updated_at=unixepoch() WHERE id='vocab_ar_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈʔis.miː/', pronunciation_en='ISS-mee', pronunciation_zh='Yī-sī-mī', updated_at=unixepoch() WHERE id='vocab_ar_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʔaˈnaː min/', pronunciation_en='uh-NAH min', pronunciation_zh='ā-NĀ mǐn', updated_at=unixepoch() WHERE id='vocab_ar_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈna.ʕam/', pronunciation_en='NAH-am', pronunciation_zh='nā-ām', updated_at=unixepoch() WHERE id='vocab_ar_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/laː/', pronunciation_en='LAA', pronunciation_zh='Lā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/maˈtˤaːr/', pronunciation_en='ma-TAR', pronunciation_zh='mǎ-Tā-er', updated_at=unixepoch() WHERE id='vocab_ar_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈtið.ki.ra/', pronunciation_en='TITH-ki-ra', pronunciation_zh='Tǐ-dhī-kè-rā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/bawˈwaː.ba/', pronunciation_en='baw-WAA-ba', pronunciation_zh='bāo-Wā-bā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈʔaj.na/', pronunciation_en='EYE-na', pronunciation_zh='Āi-nā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/jaˈsaːr/', pronunciation_en='ya-SAAR', pronunciation_zh='yā-Sā-er', updated_at=unixepoch() WHERE id='vocab_ar_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/jaˈmiːn/', pronunciation_en='ya-MEEN', pronunciation_zh='yā-Mǐn', updated_at=unixepoch() WHERE id='vocab_ar_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʔiˈlaː ʔal ʔaˈmaːm/', pronunciation_en='i-LAA al a-MAAM', pronunciation_zh='yī lā āl a-mā m', updated_at=unixepoch() WHERE id='vocab_ar_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈdawrat ʔal.miˈjaːh/', pronunciation_en='DAW-rat al-mi-YAAH', pronunciation_zh='dáo-rāt al-mī-yāh', updated_at=unixepoch() WHERE id='vocab_ar_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈqaːʔimat ʔatˤ.tˤaˈʕaːm/', pronunciation_en='QAA-i-mat at-ta-AAM', pronunciation_zh='qā-i-māt at-tā-ām', updated_at=unixepoch() WHERE id='vocab_ar_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/maːʔ/', pronunciation_en='MAAʾ', pronunciation_zh='mā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/na.baːˈtiː/', pronunciation_en='na-baa-TEE', pronunciation_zh='na-bā-tī', updated_at=unixepoch() WHERE id='vocab_ar_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʔal.ħiˈsaːb min ˈfadˤ.lik/', pronunciation_en='al-hi-SAAB min FAD-lik', pronunciation_zh='al-hī-sāb min fád-lik', updated_at=unixepoch() WHERE id='vocab_ar_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kam ʔasˈsiʕr/', pronunciation_en='kam as-SEER', pronunciation_zh='kam as-sīr', updated_at=unixepoch() WHERE id='vocab_ar_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈnaqdan/', pronunciation_en='NAQ-dan', pronunciation_zh='náq-dān', updated_at=unixepoch() WHERE id='vocab_ar_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/biˈtˤaːqa/', pronunciation_en='bi-TAA-qa', pronunciation_zh='bī-tā-qā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʔiːˈsˤaːl/', pronunciation_en='ee-SAAL', pronunciation_zh='ī-sā l', updated_at=unixepoch() WHERE id='vocab_ar_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʔan.naj.da/', pronunciation_en='an-NAJ-da', pronunciation_zh='an-nāi-dā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʔaˈnaː ˈtaːʔih/', pronunciation_en='a-NAA TAA-ih', pronunciation_zh='a-nā tā-ih', updated_at=unixepoch() WHERE id='vocab_ar_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/tˤaˈbiːb/', pronunciation_en='ta-BEEB', pronunciation_zh='tā-bī b', updated_at=unixepoch() WHERE id='vocab_ar_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ˈʃur.tˤa/', pronunciation_en='SHUR-ta', pronunciation_zh='shūr-tā', updated_at=unixepoch() WHERE id='vocab_ar_beginner_help_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nə.məsˈteː/', pronunciation_en='nuh-muhs-TAY', pronunciation_zh='nà-mā-sī-tēi', updated_at=unixepoch() WHERE id='vocab_hi_beginner_greetings_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/krɪ.pəˈjaː/', pronunciation_en='krip-uh-YAA', pronunciation_zh='kē-rī-pā-yā', updated_at=unixepoch() WHERE id='vocab_hi_beginner_greetings_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/d̪ʱən.jəˈʋaːd̪/', pronunciation_en='dhun-yuh-VAAD', pronunciation_zh='dūn-yā-wā-tè', updated_at=unixepoch() WHERE id='vocab_hi_beginner_greetings_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/maːf kiːˈd͡ʒi.eː/', pronunciation_en='maaf kee-JEE-ay', pronunciation_zh='māf jī-jī-āi', updated_at=unixepoch() WHERE id='vocab_hi_beginner_greetings_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/meː.raː naːm ... hɛː/', pronunciation_en='MAY-raa naam ... HAI', pronunciation_zh='mēi-lā nām ... hāi', updated_at=unixepoch() WHERE id='vocab_hi_beginner_introductions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mɛ̃ː ... seː ɦũː/', pronunciation_en='MAIN ... say HOON', pronunciation_zh='mēn ... sēi hūn', updated_at=unixepoch() WHERE id='vocab_hi_beginner_introductions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɦɑ̃ː/', pronunciation_en='HAAN', pronunciation_zh='hāng', updated_at=unixepoch() WHERE id='vocab_hi_beginner_introductions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nəˈɦiː̃/', pronunciation_en='nuh-HEEN', pronunciation_zh='nà-hīn', updated_at=unixepoch() WHERE id='vocab_hi_beginner_introductions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɦə.ʋaː.iː əɖːɖaː/', pronunciation_en='huh-vaa-EE uh-DDAA', pronunciation_zh='hā-wā-ī-ā-dā', updated_at=unixepoch() WHERE id='vocab_hi_beginner_transport_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʈɪ.kəʈ/', pronunciation_en='TIK-ut', pronunciation_zh='tī-kā-tè', updated_at=unixepoch() WHERE id='vocab_hi_beginner_transport_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɡeːʈ/', pronunciation_en='GAYT', pronunciation_zh='gēi-tè', updated_at=unixepoch() WHERE id='vocab_hi_beginner_transport_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/... kəˈɦɑ̃ː hɛː/', pronunciation_en='... kuh-HAAN HAI', pronunciation_zh='kā-hān-hāi', updated_at=unixepoch() WHERE id='vocab_hi_beginner_transport_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/bɑːẽː/', pronunciation_en='BAA-en', pronunciation_zh='bā-ēn', updated_at=unixepoch() WHERE id='vocab_hi_beginner_directions_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/d̪ɑːẽː/', pronunciation_en='DAA-en', pronunciation_zh='dā-ēn', updated_at=unixepoch() WHERE id='vocab_hi_beginner_directions_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/siːd̪ʱeː/', pronunciation_en='SEE-dhay', pronunciation_zh='xī-dhé', updated_at=unixepoch() WHERE id='vocab_hi_beginner_directions_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʃɔːtʃaːlaj/', pronunciation_en='SHAW-chaa-lie', pronunciation_zh='shāo-chā-lái', updated_at=unixepoch() WHERE id='vocab_hi_beginner_directions_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/meːnjuː/', pronunciation_en='MAY-nyoo', pronunciation_zh='méi-niū', updated_at=unixepoch() WHERE id='vocab_hi_beginner_restaurant_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/paːniː/', pronunciation_en='PAA-nee', pronunciation_zh='pā-nī', updated_at=unixepoch() WHERE id='vocab_hi_beginner_restaurant_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ʃaːkaːɦaːriː/', pronunciation_en='shaa-kaa-HAA-ree', pronunciation_zh='shā-kā-hā-lī', updated_at=unixepoch() WHERE id='vocab_hi_beginner_restaurant_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/bɪl d̪iːd͡ʒijeː/', pronunciation_en='bil DEE-jee-yay', pronunciation_zh='bǐl-dī-jī-yē', updated_at=unixepoch() WHERE id='vocab_hi_beginner_restaurant_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kɪt̪neː kaː hɛː/', pronunciation_en='KIT-nay kaa HAI', pronunciation_zh='jǐ-tè-kā-hēi', updated_at=unixepoch() WHERE id='vocab_hi_beginner_shopping_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/nəkəd̪/', pronunciation_en='NUH-kud', pronunciation_zh='nà-kè', updated_at=unixepoch() WHERE id='vocab_hi_beginner_shopping_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/kaːɽɖ/', pronunciation_en='KAARD', pronunciation_zh='kā-ěr-d', updated_at=unixepoch() WHERE id='vocab_hi_beginner_shopping_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/rəsiːd̪/', pronunciation_en='ruh-SEED', pronunciation_zh='là-xī-dè', updated_at=unixepoch() WHERE id='vocab_hi_beginner_shopping_4_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/məd̪əd̪/', pronunciation_en='muh-DUD', pronunciation_zh='mà-dèd', updated_at=unixepoch() WHERE id='vocab_hi_beginner_help_1_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/mɛ̃ː raːst̪aː bʱuːl ɡəjaː/', pronunciation_en='MAIN RAA-staa BHOOL guh-YAA', pronunciation_zh='mái rā-sī-tā bǔl gā-yā', updated_at=unixepoch() WHERE id='vocab_hi_beginner_help_2_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/ɖɔːkʈər/', pronunciation_en='DOK-tur', pronunciation_zh='dō-kè-těr', updated_at=unixepoch() WHERE id='vocab_hi_beginner_help_3_v1';
UPDATE smartlingo_vocabulary_items SET target_phonetic='/pʊlɪs/', pronunciation_en='puh-LEES', pronunciation_zh='pǔ-lī-sī', updated_at=unixepoch() WHERE id='vocab_hi_beginner_help_4_v1';

CREATE TRIGGER smartlingo_vocabulary_pronunciation_complete_insert
BEFORE INSERT ON smartlingo_vocabulary_items
WHEN NEW.review_status='published' AND (trim(NEW.target_phonetic)='' OR trim(NEW.pronunciation_en)='' OR trim(NEW.pronunciation_zh)='')
BEGIN
  SELECT RAISE(ABORT, 'published vocabulary requires complete pronunciation guides');
END;

CREATE TRIGGER smartlingo_vocabulary_pronunciation_complete_update
BEFORE UPDATE OF review_status,target_phonetic,pronunciation_en,pronunciation_zh ON smartlingo_vocabulary_items
WHEN NEW.review_status='published' AND (trim(NEW.target_phonetic)='' OR trim(NEW.pronunciation_en)='' OR trim(NEW.pronunciation_zh)='')
BEGIN
  SELECT RAISE(ABORT, 'published vocabulary requires complete pronunciation guides');
END;
