import { getDatabase, getSessionUser } from "@/lib/auth";
import { isPermanentAdmin } from "@/lib/admin-access";
import { allCryptoPaymentSettings, normalizeTokenAmount } from "@/lib/crypto-payments";
const addressPattern=/^0x[a-fA-F0-9]{40}$/;
async function requireAdmin(){const user=await getSessionUser();if(!isPermanentAdmin(user))throw new Response(JSON.stringify({error:"Permanent administrator access required"}),{status:403,headers:{"content-type":"application/json"}});return user;}
function parse(value:unknown){const input=(value||{})as Record<string,unknown>,decimals=Number(input.tokenDecimals);const result={label:String(input.label||"").trim().slice(0,80),chainName:String(input.chainName||"").trim().slice(0,50),chainId:Number(input.chainId),tokenSymbol:String(input.tokenSymbol||"").trim().toUpperCase().slice(0,12),tokenContract:String(input.tokenContract||"").trim().toLowerCase(),tokenDecimals:decimals,receiverWallet:String(input.receiverWallet||"").trim().toLowerCase(),basicTokenAmount:normalizeTokenAmount(input.basicTokenAmount,decimals),intermediateTokenAmount:normalizeTokenAmount(input.intermediateTokenAmount,decimals),advancedTokenAmount:normalizeTokenAmount(input.advancedTokenAmount,decimals),minConfirmations:Number(input.minConfirmations),walletConnectProjectId:String(input.walletConnectProjectId||"").trim(),enabled:input.enabled===false?0:1};if(!result.label||!result.chainName||!result.tokenSymbol||!Number.isInteger(result.chainId)||result.chainId<=0||!addressPattern.test(result.tokenContract)||!addressPattern.test(result.receiverWallet)||!Number.isInteger(decimals)||decimals<0||decimals>18||!Number.isInteger(result.minConfirmations)||result.minConfirmations<1||result.minConfirmations>1000||(result.walletConnectProjectId&&!/^[a-fA-F0-9]{32}$/.test(result.walletConnectProjectId)))throw new Error("INVALID_SETTING");return result;}
async function audit(adminId:string,action:string,settingId:string){await getDatabase().prepare("INSERT INTO crypto_payment_admin_audit(id,admin_user_id,action,setting_id) VALUES(?,?,?,?)").bind(crypto.randomUUID(),adminId,action,settingId).run();}
export async function GET(){try{await requireAdmin();return Response.json({settings:await allCryptoPaymentSettings()});}catch(error){return error instanceof Response?error:Response.json({error:"Unable to load payment rails"},{status:500});}}
export async function POST(request:Request){try{const admin=await requireAdmin(),input=parse(await request.json().catch(()=>null)),id=crypto.randomUUID();await getDatabase().prepare(`INSERT INTO crypto_payment_settings(id,label,chain_type,chain_name,chain_id,token_symbol,token_contract,token_decimals,receiver_wallet,basic_amount_cents,intermediate_amount_cents,advanced_amount_cents,basic_token_amount,intermediate_token_amount,advanced_token_amount,min_confirmations,walletconnect_project_id,enabled,created_by_user_id) VALUES(?,?,'evm',?,?,?,?,?,?,2000,10000,30000,?,?,?,?,?,?,?)`).bind(id,input.label,input.chainName,input.chainId,input.tokenSymbol,input.tokenContract,input.tokenDecimals,input.receiverWallet,input.basicTokenAmount,input.intermediateTokenAmount,input.advancedTokenAmount,input.minConfirmations,input.walletConnectProjectId||null,input.enabled,admin.id).run();await audit(admin.id,"create",id);return Response.json({id},{status:201});}catch(error){return error instanceof Response?error:Response.json({error:"Invalid crypto payment rail"},{status:400});}}
export async function PATCH(request:Request){try{const admin=await requireAdmin(),body=await request.json().catch(()=>null)as(Record<string,unknown>&{id?:string})|null,id=String(body?.id||""),input=parse(body);if(!id)throw new Error("INVALID_SETTING");await getDatabase().prepare(`UPDATE crypto_payment_settings SET label=?,chain_name=?,chain_id=?,token_symbol=?,token_contract=?,token_decimals=?,receiver_wallet=?,basic_amount_cents=2000,intermediate_amount_cents=10000,advanced_amount_cents=30000,basic_token_amount=?,intermediate_token_amount=?,advanced_token_amount=?,min_confirmations=?,walletconnect_project_id=?,enabled=?,updated_at=unixepoch() WHERE id=? AND deleted_at IS NULL`).bind(input.label,input.chainName,input.chainId,input.tokenSymbol,input.tokenContract,input.tokenDecimals,input.receiverWallet,input.basicTokenAmount,input.intermediateTokenAmount,input.advancedTokenAmount,input.minConfirmations,input.walletConnectProjectId||null,input.enabled,id).run();await audit(admin.id,"update",id);return Response.json({updated:true});}catch(error){return error instanceof Response?error:Response.json({error:"Invalid crypto payment rail"},{status:400});}}
export async function DELETE(request:Request){try{const admin=await requireAdmin(),body=await request.json().catch(()=>null)as{id?:string}|null,id=String(body?.id||"");if(!id)return Response.json({error:"Missing rail id"},{status:400});await getDatabase().prepare("UPDATE crypto_payment_settings SET enabled=0,deleted_at=unixepoch(),updated_at=unixepoch() WHERE id=? AND deleted_at IS NULL").bind(id).run();await audit(admin.id,"delete",id);return Response.json({deleted:true});}catch(error){return error instanceof Response?error:Response.json({error:"Unable to remove payment rail"},{status:500});}}
