"use client";
import { useEffect,useState } from "react";
import type { CryptoPaymentSetting } from "@/lib/crypto-contract";
const empty={id:"",label:"",chainName:"",chainId:"137",tokenSymbol:"USDC",tokenContract:"",tokenDecimals:"6",receiverWallet:"",basicTokenAmount:"20",intermediateTokenAmount:"100",advancedTokenAmount:"300",minConfirmations:"12",walletConnectProjectId:"",enabled:true};
export default function AdminCryptoSettings({lang}:{lang:"en"|"zh"}){const zh=lang==="zh",[settings,setSettings]=useState<CryptoPaymentSetting[]>([]),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const response=await fetch("/api/admin/crypto-settings",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setSettings(data.settings||[]);}
 useEffect(()=>{void load().catch(()=>setMessage(zh?"无法读取收款通道。":"Unable to load payment rails."));},[zh]);
 function edit(item:CryptoPaymentSetting){setForm({id:item.id,label:item.label,chainName:item.chainName,chainId:String(item.chainId),tokenSymbol:item.tokenSymbol,tokenContract:item.tokenContract,tokenDecimals:String(item.tokenDecimals),receiverWallet:item.receiverWallet,basicTokenAmount:item.basicTokenAmount,intermediateTokenAmount:item.intermediateTokenAmount,advancedTokenAmount:item.advancedTokenAmount,minConfirmations:String(item.minConfirmations),walletConnectProjectId:item.walletConnectProjectId||"",enabled:Boolean(item.enabled)});}
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),data=await response.json().catch(()=>({}));if(response.ok){setForm(empty);await load();setMessage(zh?"SmartLingo 独立加密收款通道已保存。":"SmartLingo-isolated crypto rail saved.");}else setMessage(data.error||(zh?"保存失败。":"Save failed."));setBusy(false);}
 async function remove(id:string){setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(response.ok){await load();setMessage(zh?"通道已停用，审计记录已保留。":"Rail disabled; audit history retained.");}setBusy(false);}
 const update=(key:keyof typeof empty,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
 return <section className="admin-crypto"><div><p className="section-kicker">CRYPTO PAYMENT</p><h2>{zh?"SmartLingo.net 加密支付配置":"SmartLingo.net crypto payment configuration"}</h2><p>{zh?"价格固定为课程实际月费：基础 $20、中级 $100、高级 $300。每条通道仅属于本站，并独立配置链、ERC-20、收款钱包、确认数与 WalletConnect Project ID。":"Prices use the actual monthly course fees: Basic $20, Intermediate $100, Advanced $300. Every chain, ERC-20, receiver, confirmation policy, and WalletConnect Project ID is isolated to this site."}</p></div>
 <form onSubmit={save}>{[["label",zh?"显示名称":"Label"],["chainName",zh?"链名称":"Chain name"],["chainId","Chain ID"],["tokenSymbol",zh?"代币符号":"Token symbol"],["tokenContract",zh?"代币合约":"Token contract"],["tokenDecimals",zh?"代币小数位":"Token decimals"],["receiverWallet",zh?"收款钱包":"Receiver wallet"],["basicTokenAmount",zh?"基础课程代币数量（$20）":"Basic token amount ($20)"],["intermediateTokenAmount",zh?"中级课程代币数量（$100）":"Intermediate token amount ($100)"],["advancedTokenAmount",zh?"高级课程代币数量（$300）":"Advanced token amount ($300)"],["minConfirmations",zh?"最少确认数":"Minimum confirmations"],["walletConnectProjectId","WalletConnect Project ID"]].map(([key,label])=><label key={key}>{label}<input value={String(form[key as keyof typeof empty])} onChange={e=>update(key as keyof typeof empty,e.target.value)} placeholder={key.includes("Contract")||key.includes("Wallet")?"0x…":""} required={key!=="walletConnectProjectId"}/></label>)}<label className="admin-toggle"><input type="checkbox" checked={form.enabled} onChange={e=>update("enabled",e.target.checked)}/>{zh?"启用此通道":"Enable this rail"}</label><div className="admin-row-actions"><button disabled={busy}>{form.id?(zh?"保存修改":"Save changes"):(zh?"新增通道":"Add rail")}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>{zh?"取消":"Cancel"}</button>}</div></form>
 <div className="admin-setting-list">{settings.map(item=><article key={item.id}><h3>{item.label}</h3><p>{item.chainName} · {item.tokenSymbol} · Chain {item.chainId}</p><p>{item.basicTokenAmount} / {item.intermediateTokenAmount} / {item.advancedTokenAmount} {item.tokenSymbol}</p><div className="admin-row-actions"><button onClick={()=>edit(item)}>{zh?"编辑":"Edit"}</button><button className="danger" onClick={()=>void remove(item.id)} disabled={busy}>{zh?"停用":"Disable"}</button></div></article>)}</div>{message&&<p role="status">{message}</p>}</section>;
}
