"use client";
import { useEffect,useState } from "react";
import type { CryptoPaymentSetting } from "@/lib/crypto-contract";
const empty={id:"",label:"",chainName:"Polygon",chainId:"137",tokenSymbol:"USDT",tokenContract:"",tokenDecimals:"6",receiverWallet:"",basicTokenAmount:"30",intermediateTokenAmount:"60",advancedTokenAmount:"120",minConfirmations:"12",enabled:true};
export default function AdminCryptoSettings({lang}:{lang:"en"|"zh"}){const zh=lang==="zh",[settings,setSettings]=useState<CryptoPaymentSetting[]>([]),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const response=await fetch("/api/admin/crypto-settings",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setSettings(data.settings||[]);}
 useEffect(()=>{let active=true;fetch("/api/admin/crypto-settings",{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(active)setSettings(data.settings||[]);}).catch(()=>{if(active)setMessage(zh?"无法读取收款通道。":"Unable to load payment rails.");});return()=>{active=false;};},[zh]);
 function edit(item:CryptoPaymentSetting){setForm({id:item.id,label:item.label,chainName:item.chainName,chainId:String(item.chainId),tokenSymbol:item.tokenSymbol,tokenContract:item.tokenContract,tokenDecimals:String(item.tokenDecimals),receiverWallet:item.receiverWallet,basicTokenAmount:item.basicTokenAmount,intermediateTokenAmount:item.intermediateTokenAmount,advancedTokenAmount:item.advancedTokenAmount,minConfirmations:String(item.minConfirmations),enabled:Boolean(item.enabled)});}
 async function addStandardRails(){if(!window.confirm(zh?"使用管理员资料中的公开收款钱包，配置 Polygon USDT 与 Polygon GLC 两项三个月课程收款通道？":"Use the public receiver wallet in the administrator profile to configure the Polygon USDT and Polygon GLC three-month course rails?"))return;setBusy(true);setMessage("");const response=await fetch("/api/admin/crypto-settings/presets",{method:"POST"}),data=await response.json().catch(()=>({}));if(response.ok){await load();setMessage(zh?`已配置 ${data.configured||0} 项标准收款通道。合约 secondId 使用所选学习语言。`:`Configured ${data.configured||0} standard rails. The contract secondId is the selected learning language.`);}else setMessage(data.error||(zh?"配置标准通道失败。":"Unable to configure standard rails."));setBusy(false);}
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),data=await response.json().catch(()=>({}));if(response.ok){setForm(empty);await load();setMessage(zh?"SmartLingo 独立加密收款通道已保存。":"SmartLingo-isolated crypto rail saved.");}else setMessage(data.error||(zh?"保存失败。":"Save failed."));setBusy(false);}
 async function remove(id:string){setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(response.ok){await load();setMessage(zh?"通道已停用，审计记录已保留。":"Rail disabled; audit history retained.");}setBusy(false);}
 const update=(key:keyof typeof empty,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
 return <section className="admin-crypto"><div><p className="section-kicker">CRYPTO PAYMENT</p><h2>{zh?"SmartLingo.net 加密支付配置":"SmartLingo.net crypto payment configuration"}</h2><p>{zh?"加密货币仅开放三个月套餐：初期 $30、中级 $60、高级 $120；仅支持 Polygon USDT 与 GLC。付款只启用 secondId 所指定语言的课程。":"Crypto is limited to three-month packages: Beginner $30, Intermediate $60, and Advanced $120, using Polygon USDT or GLC only. Each payment activates the language course named by secondId."}</p><div className="admin-row-actions"><button type="button" onClick={()=>void addStandardRails()} disabled={busy}>{zh?"添加 Polygon 两项收款配置":"Add two Polygon rails"}</button></div></div>
 <form onSubmit={save}>{[["label",zh?"显示名称":"Label"],["chainName",zh?"链名称（仅 Polygon）":"Chain name (Polygon only)"],["chainId",zh?"链编号（137）":"Chain ID (137)"],["tokenSymbol",zh?"代币符号（USDT 或 GLC）":"Token symbol (USDT or GLC)"],["tokenContract",zh?"代币合约":"Token contract"],["tokenDecimals",zh?"代币小数位":"Token decimals"],["receiverWallet",zh?"收款钱包":"Receiver wallet"],["basicTokenAmount",zh?"初期三个月代币数量（$30）":"Beginner three-month token amount ($30)"],["intermediateTokenAmount",zh?"中级三个月代币数量（$60）":"Intermediate three-month token amount ($60)"],["advancedTokenAmount",zh?"高级三个月代币数量（$120）":"Advanced three-month token amount ($120)"],["minConfirmations",zh?"最少确认数":"Minimum confirmations"]].map(([key,label])=><label key={key}>{label}<input value={String(form[key as keyof typeof empty])} onChange={e=>update(key as keyof typeof empty,e.target.value)} placeholder={key.includes("Contract")||key.includes("Wallet")?"0x…":""} required readOnly={key==="chainName"||key==="chainId"}/></label>)}<label className="admin-toggle"><input type="checkbox" checked={form.enabled} onChange={e=>update("enabled",e.target.checked)}/>{zh?"启用此通道":"Enable this rail"}</label><div className="admin-row-actions"><button disabled={busy}>{form.id?(zh?"保存修改":"Save changes"):(zh?"新增通道":"Add rail")}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>{zh?"取消":"Cancel"}</button>}</div></form>
 <div className="admin-setting-list">{settings.map(item=><article key={item.id}><h3>{item.label}</h3><p>{item.chainName} · {item.tokenSymbol} · Chain {item.chainId}</p><p>{item.basicTokenAmount} / {item.intermediateTokenAmount} / {item.advancedTokenAmount} {item.tokenSymbol}</p><div className="admin-row-actions"><button onClick={()=>edit(item)}>{zh?"编辑":"Edit"}</button><button className="danger" onClick={()=>void remove(item.id)} disabled={busy}>{zh?"停用":"Disable"}</button></div></article>)}</div>{message&&<p role="status">{message}</p>}</section>;
}
