"use client";
import { useState } from "react";

export function AdminMemberActions({lang,tab}:{lang:"en"|"zh";tab:"recent"|"subscribers"|"teachers"}){
  const zh=lang==="zh",[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const payload=tab==="recent"?{action:"create",displayName:String(form.get("displayName")??""),email:String(form.get("email")??""),password:String(form.get("password")??"")}:{action:tab==="subscribers"?"grant-subscriber":"grant-teacher",email:String(form.get("email")??"")};const response=await fetch("/api/admin/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({})) as {error?:string};if(!response.ok){setMessage(data.error||(zh?"操作失败。":"Action failed."));setBusy(false);return}window.location.reload()}
  return <section className="admin-add-card"><h2>{zh?"添加":"Add"}</h2><p>{tab==="recent"?(zh?"创建一个可使用邮箱和临时密码登录的新会员。密码只发送到身份服务，不写入本站数据库。":"Create a member with email and a temporary password. The password is sent only to the identity provider."):(tab==="subscribers"?(zh?"输入现有会员邮箱，确认后授予订阅访问权益。":"Enter an existing member email and grant subscriber access."):(zh?"输入现有付费会员邮箱，确认后授予教师课堂创建权限。":"Enter an existing paid member email and grant teacher class-creation access."))}</p><form onSubmit={submit}>{tab==="recent"&&<label>{zh?"用户名":"Name"}<input name="displayName" required minLength={2} maxLength={60}/></label>}<label>{zh?"邮箱":"Email"}<input name="email" type="email" required autoComplete="off"/></label>{tab==="recent"&&<label>{zh?"临时密码":"Temporary password"}<input name="password" type="password" required minLength={8} autoComplete="new-password"/></label>}<button type="submit" disabled={busy}>{busy?(zh?"处理中…":"Working…"):(tab==="recent"?(zh?"添加":"Add"):(zh?"添加教师":"Add Teacher"))}</button>{message&&<p className="admin-form-message" role="alert">{message}</p>}</form></section>}

export function AdminMemberDelete({memberId,lang,locked}:{memberId:string;lang:"en"|"zh";locked:boolean}){const zh=lang==="zh",[busy,setBusy]=useState(false);async function remove(){if(locked||!confirm(zh?"从本站移除此会员？其身份提供商账户不会被删除。":"Remove this member from this site? Their identity-provider account will not be deleted."))return;setBusy(true);const response=await fetch(`/api/admin/members/${encodeURIComponent(memberId)}`,{method:"DELETE"});if(response.ok){window.location.reload();return}const data=await response.json().catch(()=>({})) as {error?:string};alert(data.error||(zh?"移除失败。":"Removal failed."));setBusy(false)}return <button type="button" className="admin-delete" onClick={remove} disabled={locked||busy} title={locked?(zh?"受保护的管理员":"Protected administrator"):undefined}>{busy?(zh?"移除中…":"Removing…"):(zh?"删除":"Delete")}</button>}
