"use client";
import { useEffect,useState } from "react";
import type { CryptoPaymentSetting } from "@/lib/crypto-contract";
const empty={id:"",label:"",chainName:"",chainId:"137",tokenSymbol:"USDC",tokenContract:"",tokenDecimals:"6",receiverWallet:"",basicTokenAmount:"20",intermediateTokenAmount:"100",advancedTokenAmount:"300",minConfirmations:"12",enabled:true};
export default function AdminCryptoSettings({lang}:{lang:"en"|"zh"}){const zh=lang==="zh",[settings,setSettings]=useState<CryptoPaymentSetting[]>([]),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const response=await fetch("/api/admin/crypto-settings",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setSettings(data.settings||[]);}
 useEffect(()=>{let active=true;fetch("/api/admin/crypto-settings",{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(active)setSettings(data.settings||[]);}).catch(()=>{if(active)setMessage(zh?"无法读取收款通道。":"Unable to load payment rails.");});return()=>{active=false;};},[zh]);
 function edit(item:CryptoPaymentSetting){setForm({id:item.id,label:item.label,chainName:item.chainName,chainId:String(item.chainId),tokenSymbol:item.tokenSymbol,tokenContract:item.tokenContract,tokenDecimals:String(item.tokenDecimals),receiverWallet:item.receiverWallet,basicTokenAmount:item.basicTokenAmount,intermediateTokenAmount:item.intermediateTokenAmount,advancedTokenAmount:item.advancedTokenAmount,minConfirmations:String(item.minConfirmations),enabled:Boolean(item.enabled)});}
 async function addStandardRails(){if(!window.confirm(zh?"使用管理员资料中的公开收款钱包，新增 ETH、BSC、Polygon、Base 的 USDT/USDC，以及 Polygon GLC 共 9 项配置？":"Use the public receiver wallet in the administrator profile to add nine standard ETH, BSC, Polygon, Base, and GLC rails?"))return;setBusy(true);setMessage("");const response=await fetch("/api/admin/crypto-settings/presets",{method:"POST"}),data=await response.json().catch(()=>({}));if(response.ok){await load();setMessage(zh?`已新增 ${data.created||0} 项标准收款配置。每笔付款只启用所选语言的单门课程。`:`Added ${data.created||0} standard rails. Each payment activates only the selected language course.`);}else setMessage(data.error||(zh?"新增标准配置失败。":"Unable to add standard rails."));setBusy(false);}
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),data=await response.json().catch(()=>({}));if(response.ok){setForm(empty);await load();setMessage(zh?"SmartLingo 独立加密收款通道已保存。":"SmartLingo-isolated crypto rail saved.");}else setMessage(data.error||(zh?"保存失败。":"Save failed."));setBusy(false);}
 async function remove(id:string){setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(response.ok){await load();setMessage(zh?"通道已停用，审计记录已保留。":"Rail disabled; audit history retained.");}setBusy(false);}
 const update=(key:keyof typeof empty,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
 return <section className="admin-crypto"><div><p className="section-kicker">CRYPTO PAYMENT</p><h2>{zh?"SmartLingo.net 加密支付配置":"SmartLingo.net crypto payment configuration"}</h2><p>{zh?"所有会员均可免费注册。课程价格按级别固定并适用于所有语言：初期 $20、中级 $100、高级 $300。付款只启用所选语言与级别对应的单门课程，不会改变会员等级。":"Every member may register for free. Course prices are fixed across all languages: Beginner $20, Intermediate $100, Advanced $300. Payment activates only the selected language-and-tier course and never changes member level."}</p><div className="admin-row-actions"><button type="button" onClick={()=>void addStandardRails()} disabled={busy}>{zh?"添加标准 9 项收款配置":"Add standard 9 rails"}</button></div></div>
 <form onSubmit={save}>{[["label",zh?"显示名称":"Label"],["chainName",zh?"链名称":"Chain name"],["chainId",zh?"链编号":"Chain ID"],["tokenSymbol",zh?"代币符号":"Token symbol"],["tokenContract",zh?"代币合约":"Token contract"],["tokenDecimals",zh?"代币小数位":"Token decimals"],["receiverWallet",zh?"收款钱包":"Receiver wallet"],["basicTokenAmount",zh?"初期课程代币数量（$20）":"Beginner token amount ($20)"],["intermediateTokenAmount",zh?"中级课程代币数量（$100）":"Intermediate token amount ($100)"],["advancedTokenAmount",zh?"高级课程代币数量（$300）":"Advanced token amount ($300)"],["minConfirmations",zh?"最少确认数":"Minimum confirmations"]].map(([key,label])=><label key={key}>{label}<input value={String(form[key as keyof typeof empty])} onChange={e=>update(key as keyof typeof empty,e.target.value)} placeholder={key.includes("Contract")||key.includes("Wallet")?"0x…":""} required/></label>)}<label className="admin-toggle"><input type="checkbox" checked={form.enabled} onChange={e=>update("enabled",e.target.checked)}/>{zh?"启用此通道":"Enable this rail"}</label><div className="admin-row-actions"><button disabled={busy}>{form.id?(zh?"保存修改":"Save changes"):(zh?"新增通道":"Add rail")}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>{zh?"取消":"Cancel"}</button>}</div></form>
 <div className="admin-setting-list">{settings.map(item=><article key={item.id}><h3>{item.label}</h3><p>{item.chainName} · {item.tokenSymbol} · Chain {item.chainId}</p><p>{item.basicTokenAmount} / {item.intermediateTokenAmount} / {item.advancedTokenAmount} {item.tokenSymbol}</p><div className="admin-row-actions"><button onClick={()=>edit(item)}>{zh?"编辑":"Edit"}</button><button className="danger" onClick={()=>void remove(item.id)} disabled={busy}>{zh?"停用":"Disable"}</button></div></article>)}</div>{message&&<p role="status">{message}</p>}</section>;
}
