"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { DEPARTMENT_LANGUAGES, departmentLanguageName } from "../lib/college-department-languages";
import type { CollegeDepartment } from "../lib/college-departments";

export function CollegeDepartmentManager({lang,collegeCode,departments,quota}:{lang:string;collegeCode:string;departments:CollegeDepartment[];quota:{max:number;used:number}|null}){
  const zh=lang==="zh",router=useRouter(),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const response=await fetch(`/api/colleges/${collegeCode}/departments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});const data=await response.json().catch(()=>({})) as{error?:string};setMessage(response.ok?(zh?"部门已创建，课程与 Webinar 房间已自动配置。":"Department created with courses and its Webinar room."):data.error||"Unable to create department");if(response.ok){event.currentTarget.reset();router.refresh()}setBusy(false)}
  return <section className="college-department-manager"><header><div><p className="section-kicker">DEPARTMENTS</p><h2>{zh?"语言部门与招生":"Language departments & enrollment"}</h2></div><strong>{quota?`${quota.used} / ${quota.max}`:"ADMIN"}</strong></header>
    <p>{zh?"每个部门选择一种界面语言和一种学习语言；系统自动加入平台管理员发布的三个固定价格课程、四项免费学习产品，以及默认的 Webinar Audio 房间。":"Choose an interface language and a learning language. SmartLingo automatically adds the three admin-priced courses, four free learning products, and a Webinar Audio room."}</p>
    <form onSubmit={submit}><label>{zh?"用户语言":"Interface language"}<select name="sourceLanguage" required defaultValue=""><option value="">—</option>{DEPARTMENT_LANGUAGES.map(code=><option key={code} value={code}>{departmentLanguageName(code,zh)}</option>)}</select></label><span>→</span><label>{zh?"学习语言":"Learning language"}<select name="targetLanguage" required defaultValue=""><option value="">—</option>{DEPARTMENT_LANGUAGES.map(code=><option key={code} value={code}>{departmentLanguageName(code,zh)}</option>)}</select></label><button disabled={busy||Boolean(quota&&quota.used>=quota.max)}>{busy?"…":zh?"创建部门":"Create department"}</button></form>{message&&<p role="status">{message}</p>}
    <div>{departments.map(department=><article key={department.id}><small>{department.code} · WEBINAR {department.streamingMode==="audio"?"AUDIO":"A/V"}</small><h3>{zh?department.titleZh:department.titleEn}</h3><p>{department.courseCount} {zh?"门管理员课程 · 四项免费产品":"admin courses · four free products"}</p><a href={`/${lang}/college/${collegeCode}/departments/${department.id}`}>{zh?"打开部门":"Open department"} →</a><a href={`/${lang}/classrooms/${department.roomCode}`}>{zh?"管理房间":"Manage room"} →</a></article>)}</div>
    <style>{`.college-department-manager{margin-top:35px;padding:clamp(22px,4vw,42px);border-radius:24px;background:#123f35;color:#fff}.college-department-manager>header{display:flex;justify-content:space-between;gap:18px;align-items:start}.college-department-manager h2{margin:6px 0;font-size:clamp(30px,4vw,48px)}.college-department-manager>header>strong{padding:11px 14px;border-radius:999px;background:#73e6c4;color:#073f33}.college-department-manager>p{max-width:80ch;color:#c7ded6;line-height:1.65}.college-department-manager>form{margin:26px 0;display:grid;grid-template-columns:1fr auto 1fr auto;gap:12px;align-items:end}.college-department-manager label{display:grid;gap:7px;font-weight:850}.college-department-manager select,.college-department-manager button{min-height:50px;padding:10px 13px;border:1px solid #7da99b;border-radius:11px;background:#fff;color:#123f35;font:inherit}.college-department-manager button{border:0;background:#73e6c4;font-weight:900}.college-department-manager>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.college-department-manager article{padding:20px;border-radius:16px;background:#f1fbf6;color:#123f35}.college-department-manager article small{color:#087d62;font-weight:900}.college-department-manager article h3{font-size:25px}.college-department-manager article a{margin-right:14px;color:#087d62;font-weight:850}@media(max-width:760px){.college-department-manager>form{grid-template-columns:1fr}.college-department-manager>form>span{display:none}.college-department-manager>div{grid-template-columns:1fr}}`}</style></section>
}
