"use client";

import { useEffect, useMemo, useState } from "react";

type Member = { id: string; displayName: string; createdAt: number; imageUrl?: string };
type Reply = { id: string; topicId: string; body: string; createdAt: number; authorId: string; authorName: string };
type Topic = { id: string; category: string; title: string; body: string; createdAt: number; authorId: string; authorName: string };
type Data = { currentUserId: string; members: Member[]; topics: Topic[]; replies: Reply[] };

const channels = ["all", "general", "learning", "projects", "events"] as const;

export function CommunityClient({ lang }: { lang: "en" | "zh" }) {
  const zh = lang === "zh";
  const [data, setData] = useState<Data>({ currentUserId: "", members: [], topics: [], replies: [] });
  const [channel, setChannel] = useState<(typeof channels)[number]>("all");
  const [selected, setSelected] = useState("");
  const [search, setSearch] = useState("");
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [reply, setReply] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [showMembers, setShowMembers] = useState(false);
  const [selectedMember, setSelectedMember] = useState<Member | null>(null); const [tipMessage, setTipMessage] = useState("");

  async function load() { const response = await fetch("/api/community", { cache: "no-store" }); if (!response.ok) throw new Error(); const result = await response.json() as Data; setData(result); setSelected(value => value || result.topics[0]?.id || ""); }
  // The async loader updates state only after the network request resolves.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load().catch(() => setError(zh ? "暂时无法读取社区。" : "Unable to load the community.")); }, [zh]);
  const topics = data.topics.filter(topic => channel === "all" || topic.category === channel);
  const active = data.topics.find(topic => topic.id === selected) || topics[0];
  const members = useMemo(() => data.members.filter(member => member.displayName.toLowerCase().includes(search.toLowerCase())), [data.members, search]);
  async function send(payload: object) { setBusy(true); setError(""); try { const response = await fetch("/api/community", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(result.error || `HTTP ${response.status}`); await load(); return true; } catch (reason) { const detail = reason instanceof Error ? reason.message : ""; const safeDetail = zh && !/[\u3400-\u9fff]/.test(detail) ? "" : detail; setError(`${zh ? "发布失败，请重试。" : "Post failed. Please try again."}${safeDetail ? ` (${safeDetail})` : ""}`); return false; } finally { setBusy(false); } }
  async function createTopic(event: React.FormEvent) { event.preventDefault(); if (!title.trim() || !body.trim()) return; if (await send({ type: "topic", category: channel === "all" ? "general" : channel, title, body })) { setTitle(""); setBody(""); } }
  async function createReply(event: React.FormEvent) { event.preventDefault(); if (!active || !reply.trim()) return; if (await send({ type: "reply", topicId: active.id, body: reply })) setReply(""); }
  async function startLiveChat() { if (!selectedMember || busy) return; setBusy(true); try { const response = await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "start_live", recipientId: selectedMember.id }) }); const result = await response.json(); if (!response.ok) throw new Error(); window.location.href = `/${lang}/messages/live/${encodeURIComponent(result.threadId)}`; } catch { setTipMessage(zh ? "暂时无法开始实时聊天。" : "Live chat could not start."); setBusy(false); } }

  const names = zh ? { all: "全部讨论", general: "综合", learning: "语言学习", projects: "班级与练习", events: "活动与开班" } : { all: "All topics", general: "General", learning: "Language learning", projects: "Classes & practice", events: "Events & class building" };
  return <section className="community-workspace" data-layout-fill="community-workspace" data-layout-ready={data.currentUserId ? "true" : undefined} data-layout-text-fit="community-workspace">
    <aside className="community-rail" data-layout-track="community-rail"><p>{zh ? "频道" : "Channels"}</p>{channels.map(item => <button key={item} className={channel === item ? "active" : ""} onClick={() => setChannel(item)}># {names[item]}</button>)}<div className="community-online"><i/> {zh ? `${data.members.length} 位会员` : `${data.members.length} members`}</div></aside>
    <section className="topic-column" data-layout-track="community-topics"><header><div data-readable-copy="community-heading"><p className="section-kicker">{zh ? "SMARTLINGO 学习与班级社区" : "SMARTLINGO LEARNING & CLASS COMMUNITY"}</p><h1>{names[channel]}</h1></div><span>{topics.length}</span></header><form className="topic-compose" onSubmit={createTopic}><input value={title} onChange={event => setTitle(event.target.value)} placeholder={zh ? "新主题标题" : "New topic title"} maxLength={100}/><textarea value={body} onChange={event => setBody(event.target.value)} placeholder={zh ? "分享语言学习问题、会话练习或开班经验…" : "Share a language question, conversation practice, or class-building experience…"} maxLength={1200}/><button disabled={busy}>{zh ? "发布主题" : "Post topic"}</button></form><div className="topic-list">{topics.map(topic => <button key={topic.id} className={active?.id === topic.id ? "active" : ""} onClick={() => setSelected(topic.id)}><span># {names[topic.category as keyof typeof names] || topic.category}</span><strong>{topic.title}</strong><small>{topic.authorName} · {new Date(topic.createdAt * 1000).toLocaleDateString(lang)}</small></button>)}{topics.length === 0 && <p>{zh ? "这里还没有主题，欢迎第一个发言。" : "No topics yet. Start the conversation."}</p>}</div></section>
    <section className="discussion-column" data-layout-track="community-discussion">{active ? <><header><span># {names[active.category as keyof typeof names]}</span><h2>{active.title}</h2><p>{active.authorName}</p></header><article className="opening-post"><strong>{active.authorName}</strong><p>{active.body}</p></article><div className="reply-list">{data.replies.filter(item => item.topicId === active.id).map(item => <article key={item.id}><strong>{item.authorName}</strong><small>{new Date(item.createdAt * 1000).toLocaleString(lang)}</small><p>{item.body}</p></article>)}</div><form className="reply-compose" onSubmit={createReply}><textarea value={reply} onChange={event => setReply(event.target.value)} placeholder={zh ? "回复讨论…" : "Reply to the discussion…"} maxLength={1200}/><button disabled={busy}>{zh ? "回复" : "Reply"}</button></form></> : <div className="empty-discussion">{zh ? "选择或创建一个主题" : "Select or create a topic"}</div>}</section>
    <button className="floating-community-members" type="button" onClick={() => setShowMembers(true)} aria-label={zh ? "搜索会员" : "Search members"} title={zh ? "搜索会员" : "Search members"}><svg viewBox="0 0 32 32" aria-hidden="true"><circle cx="12" cy="11" r="5"/><circle cx="23" cy="13" r="4"/><path d="M3.5 27c.6-5.2 3.5-8 8.5-8s8 2.8 8.5 8M19 21c1.2-.8 2.6-1.2 4.2-1.2 3.4 0 5.3 2.1 5.8 6.2"/></svg><b>{zh ? "会员" : "Members"}</b></button>
    {showMembers && <div className="community-member-backdrop" onMouseDown={() => setShowMembers(false)}><aside className="community-member-drawer" onMouseDown={event => event.stopPropagation()}><header><h2>{zh ? "搜索会员" : "Find members"}</h2><button onClick={() => setShowMembers(false)}>×</button></header><input autoFocus value={search} onChange={event => setSearch(event.target.value)} placeholder={zh ? "输入会员名称" : "Enter a member name"}/><div>{members.map(member => <button className="member-profile-button" key={member.id} onClick={() => { setShowMembers(false); setSelectedMember(member); setTipMessage(""); }}><span>{member.imageUrl ? <img src={member.imageUrl} alt=""/> : member.displayName.slice(0, 1).toUpperCase()}</span><p><strong>{member.displayName}</strong><small>{zh ? "查看会员资料" : "View member profile"}</small></p><i>→</i></button>)}</div></aside></div>}
    {selectedMember && <div className="community-profile-backdrop" onMouseDown={() => setSelectedMember(null)}><section className="community-profile" onMouseDown={event => event.stopPropagation()}><button className="profile-close" onClick={() => setSelectedMember(null)}>×</button><span className="profile-avatar">{selectedMember.imageUrl ? <img src={selectedMember.imageUrl} alt=""/> : selectedMember.displayName.slice(0,1).toUpperCase()}</span><h2>{selectedMember.displayName}</h2><p>{zh ? `加入于 ${new Date(selectedMember.createdAt * 1000).toLocaleDateString("zh-CN")}` : `Joined ${new Date(selectedMember.createdAt * 1000).toLocaleDateString("en-US")}`}</p><div className="profile-activity"><span><b>{data.topics.filter(item => item.authorId === selectedMember.id).length}</b>{zh ? "主题" : "Topics"}</span><span><b>{data.replies.filter(item => item.authorId === selectedMember.id).length}</b>{zh ? "回复" : "Replies"}</span></div>{selectedMember.id !== data.currentUserId && <><div className="member-contact-actions"><a className="member-message-link" href={"/" + lang + "/messages?member=" + encodeURIComponent(selectedMember.id)}>{zh ? "发送消息" : "Send message"}</a><button type="button" onClick={startLiveChat} disabled={busy}>{zh ? "实时聊天" : "Live Chat"}</button></div>{tipMessage && <small>{tipMessage}</small>}</>}</section></div>}
    {error && <p className="community-error">{error}</p>}
  </section>;
}
