"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { CryptoPaymentSetting, CryptoPlanId } from "@/lib/crypto-contract";
import { explorerUrl } from "@/lib/crypto-contract";

type Provider={request(args:{method:string;params?:unknown[]}):Promise<unknown>};
type Payment={txHash:string;chainName:string;tokenSymbol:string;planId:string;languageCode:string;status:string;entitlementStatus:string;createdAt:string};
type Status={signedIn:boolean;wallet?:string|null;cryptoSettings?:CryptoPaymentSetting[];payments?:Payment[]};
const plans=[{id:"basic" as const,price:"$20",zh:"初期课程",en:"Beginner"},{id:"intermediate" as const,price:"$100",zh:"中级课程",en:"Intermediate"},{id:"advanced" as const,price:"$300",zh:"高级课程",en:"Advanced"}];
const languages=[{code:"zh",zh:"中文",en:"Chinese"},{code:"en",zh:"英语",en:"English"},{code:"es",zh:"西班牙语",en:"Spanish"},{code:"ja",zh:"日语",en:"Japanese"},{code:"ko",zh:"韩语",en:"Korean"},{code:"fr",zh:"法语",en:"French"},{code:"de",zh:"德语",en:"German"},{code:"ru",zh:"俄语",en:"Russian"},{code:"it",zh:"意大利语",en:"Italian"},{code:"pt",zh:"葡萄牙语",en:"Portuguese"},{code:"ar",zh:"阿拉伯语",en:"Arabic"},{code:"hi",zh:"印地语",en:"Hindi"}];
const chainMeta:Record<number,{name:string;currency:string;rpc:string;explorer:string}>={1:{name:"Ethereum",currency:"ETH",rpc:"https://ethereum-rpc.publicnode.com",explorer:"https://etherscan.io"},56:{name:"BNB Smart Chain",currency:"BNB",rpc:"https://bsc-rpc.publicnode.com",explorer:"https://bscscan.com"},137:{name:"Polygon",currency:"POL",rpc:"https://polygon-bor-rpc.publicnode.com",explorer:"https://polygonscan.com"},8453:{name:"Base",currency:"ETH",rpc:"https://base-rpc.publicnode.com",explorer:"https://basescan.org"}};
const amountFor=(setting:CryptoPaymentSetting,plan:CryptoPlanId)=>plan==="basic"?setting.basicTokenAmount:plan==="intermediate"?setting.intermediateTokenAmount:setting.advancedTokenAmount;
function atomic(value:string,decimals:number){const[whole,fraction=""]=value.split(".");return BigInt(`${whole||"0"}${fraction.padEnd(decimals,"0").slice(0,decimals)}`);}

export default function CryptoCheckout({initialPlan,initialLanguageCode="en",lockedCourseId,lang}:{initialPlan:CryptoPlanId;initialLanguageCode?:string;lockedCourseId?:string;lang:"en"|"zh"}){const language=lang;const zh=language==="zh";const[status,setStatus]=useState<Status>({signedIn:false});const[step,setStep]=useState(1);const[plan,setPlan]=useState<CryptoPlanId>(initialPlan);const[settingId,setSettingId]=useState("");const[languageCode,setLanguageCode]=useState(initialLanguageCode);const[wallet,setWallet]=useState("");const[provider,setProvider]=useState<Provider|null>(null);const[direct,setDirect]=useState(false);const[confirmed,setConfirmed]=useState(false);const[balance,setBalance]=useState("");const[txHash,setTxHash]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState("");
  async function load(){const response=await fetch("/api/billing/status",{cache:"no-store"});const data=await response.json();setStatus(data);setWallet(data.wallet||"");}
  useEffect(()=>{let active=true;fetch("/api/billing/status",{cache:"no-store"}).then(response=>response.json()).then(data=>{if(active){setStatus(data);setWallet(data.wallet||"");}}).catch(()=>{if(active)setMessage(zh?"暂时无法读取结账配置。":"Unable to load checkout settings.");});return()=>{active=false;};},[zh]);
  const settings=status.cryptoSettings||[];const selected=settings.find(item=>item.id===(settingId||settings[0]?.id));const selectedPlan=plans.find(item=>item.id===plan)!;
  function requireLogin(){if(status.signedIn)return true;const returnTo=lockedCourseId?`/${language}/classes/${encodeURIComponent(lockedCourseId)}/pay/crypto`:`/${language}/programs`;window.location.assign(`/${language}/auth/login?returnTo=${encodeURIComponent(returnTo)}`);return false;}
  async function saveWallet(value:string){const normalized=value.trim().toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(normalized))throw new Error("INVALID_WALLET");const response=await fetch("/api/billing/crypto/wallet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({wallet:normalized})});if(!response.ok)throw new Error("SAVE_FAILED");setWallet(normalized);await load();}
  async function connectInjected(){if(!selected||!requireLogin())return;const injected=(window as unknown as{ethereum?:Provider}).ethereum;if(!injected){setMessage(zh?"未检测到浏览器钱包；可改用 WalletConnect 二维码或直接转账。":"No browser wallet detected. Use WalletConnect QR or direct transfer.");return;}try{setBusy("connect");await injected.request({method:"wallet_switchEthereumChain",params:[{chainId:`0x${selected.chainId.toString(16)}`}]});const accounts=await injected.request({method:"eth_requestAccounts"}) as string[];await saveWallet(String(accounts[0]||""));setProvider(injected);setDirect(false);setMessage(zh?"钱包已连接。请核对金额并明确确认 ERC-20 转账。":"Wallet connected. Review the amount and explicitly confirm the ERC-20 transfer.");}catch{setMessage(zh?"无法连接浏览器钱包或切换所选网络。":"Could not connect the browser wallet or switch to the selected network.");}finally{setBusy("");}}
  async function connectWalletConnect(){if(!selected||!requireLogin())return;if(!selected.walletConnectProjectId){setMessage(zh?"该通道尚未配置 SmartLingo.net 独立的 WalletConnect 项目标识，请使用浏览器钱包或直接转账。":"This rail does not yet have a SmartLingo-specific WalletConnect Project ID. Use a browser wallet or direct transfer.");return;}try{setBusy("walletconnect");const wcModule=await import("@walletconnect/ethereum-provider");const EthereumProvider=wcModule.default;const meta=chainMeta[selected.chainId];const wc=await EthereumProvider.init({projectId:selected.walletConnectProjectId,chains:[selected.chainId],showQrModal:true,metadata:{name:"SmartLingo.net",description:"SmartLingo.net subscription checkout",url:window.location.origin,icons:[`${window.location.origin}/favicon.svg`]},rpcMap:meta?{[selected.chainId]:meta.rpc}:undefined});await wc.connect();const accounts=await wc.request({method:"eth_accounts"}) as string[];await saveWallet(String(accounts[0]||""));setProvider(wc as Provider);setDirect(false);setMessage(zh?"WalletConnect 已连接。请核对并确认 ERC-20 转账。":"WalletConnect is connected. Review and confirm the ERC-20 transfer.");}catch{setMessage(zh?"WalletConnect 连接未完成，请重新扫描二维码或选择其他方式。":"WalletConnect did not complete. Scan again or choose another method.");}finally{setBusy("");}}
  async function sendPayment(){if(!selected||!provider||!wallet||!confirmed)return;try{setBusy("send");const value=amountFor(selected,plan);const data=`0xa9059cbb${selected.receiverWallet.slice(2).padStart(64,"0")}${atomic(value,selected.tokenDecimals).toString(16).padStart(64,"0")}`;const hash=await provider.request({method:"eth_sendTransaction",params:[{from:wallet,to:selected.tokenContract,data}]});if(typeof hash!=="string")throw new Error("NO_HASH");setTxHash(hash);await verify(hash);}catch{setMessage(zh?"交易未发送；请检查钱包确认、网络和余额。":"Transaction was not sent. Check wallet confirmation, network, and balance.");}finally{setBusy("");}}
  async function refreshBalance(){if(!selected)return;setBusy("balance");const response=await fetch("/api/billing/crypto/balance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({settingId:selected.id})});const data=await response.json().catch(()=>({}));if(response.ok)setBalance(`${data.amount} ${data.symbol}`);else setMessage(data.error||(zh?"无法读取余额。":"Unable to read balance."));setBusy("");}
  async function verify(hashValue=txHash){if(!selected||!wallet||!lockedCourseId)return;setBusy("verify");let hash=hashValue.trim().toLowerCase();if(!/^0x[a-f0-9]{64}$/.test(hash)){const lookup=await fetch("/api/billing/crypto/find-payment",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan,settingId:selected.id})});const found=await lookup.json().catch(()=>({}));if(!lookup.ok||!found.txHash){setMessage(found.error||(zh?"尚未找到匹配的近期付款。":"No matching recent payment was found."));setBusy("");return;}hash=found.txHash;setTxHash(hash);}const response=await fetch("/api/billing/crypto/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan,languageCode,classId:lockedCourseId,settingId:selected.id,txHash:hash})});const data=await response.json().catch(()=>({}));setMessage(data.verified?(zh?"付款已由服务端完成链上验证；课程和学习权益已启用。":"Payment verified on-chain by the server; Course and learning entitlements are active."):(data.error||(zh?"付款验证失败。":"Payment verification failed.")));if(data.verified)await load();setBusy("");}
  async function saveDirect(){try{setBusy("wallet");await saveWallet(wallet);setMessage(zh?"付款钱包已保存，可刷新余额或查询近期付款。":"Payer wallet saved. You can refresh balance or find a recent payment.");}catch{setMessage(zh?"请输入有效的 EVM 钱包地址。":"Enter a valid EVM wallet address.");}finally{setBusy("");}}
  return <section className="crypto-flow"><Link href={lockedCourseId?`/${language}/classes/${encodeURIComponent(lockedCourseId)}`:`/${language}/programs`}>← {zh?"返回课程详情":"Back to course"}</Link><header><p className="eyebrow jade">CRYPTO CHECKOUT</p><h1>{zh?"使用加密货币订阅 SmartLingo.net 课程":"Subscribe to a SmartLingo.net course with crypto"}</h1><p>{zh?"确认本课程、学习语言、链与钱包。我们绝不会要求私钥或助记词。":"Confirm this course, learning language, rail, and wallet. We never request a private key or seed phrase."}</p></header><ol className="payment-steps"><li className={step>=1?"active":""}>1. {zh?"课程":"Course"}</li><li className={step>=2?"active":""}>2. {zh?"链与代币":"Chain & token"}</li><li className={step>=3?"active":""}>3. {zh?"钱包与验证":"Wallet & verify"}</li></ol>
    {step===1&&<section className="crypto-card"><h2>{zh?"步骤 1：确认课程与学习语言":"Step 1: Confirm course and learning language"}</h2><div className="crypto-options">{plans.filter(item=>!lockedCourseId||item.id===initialPlan).map(item=><label key={item.id}><input type="radio" checked={plan===item.id} disabled={Boolean(lockedCourseId)} onChange={()=>setPlan(item.id)}/><span><strong>{item.price}</strong><small>{zh?item.zh:item.en} · {zh?"每月":"monthly"}</small></span></label>)}</div><label>{zh?"学习语言":"Learning language"}<select value={languageCode} disabled={Boolean(lockedCourseId)} onChange={event=>setLanguageCode(event.target.value)}>{languages.filter(item=>!lockedCourseId||item.code===initialLanguageCode).map(item=><option key={item.code} value={item.code}>{zh?item.zh:item.en}</option>)}</select></label><ul><li>{zh?"内置私密小组音视频与沟通中心":"Private group audio/video and communication center"}</li><li>{zh?"公开网络研讨会与 HLS 广播":"Public webinars and HLS broadcasting"}</li><li>{zh?"DeepSeek V4 Flash 默认，可选 OpenAI":"DeepSeek V4 Flash by default, OpenAI optional"}</li></ul><button onClick={()=>setStep(2)}>{zh?"下一步：选择链":"Next: choose chain"} →</button></section>}
    {step===2&&<section className="crypto-card"><button className="text-button" onClick={()=>setStep(1)}>← {zh?"上一步":"Back"}</button><h2>{zh?"步骤 2：选择管理员启用的链与 ERC-20":"Step 2: Choose an administrator-enabled chain and ERC-20"}</h2>{settings.length?<div className="crypto-options">{settings.map(item=><label key={item.id}><input type="radio" checked={(settingId||settings[0]?.id)===item.id} onChange={()=>setSettingId(item.id)}/><span><strong>{item.label}</strong><small>{item.chainName} · {amountFor(item,plan)} {item.tokenSymbol}</small></span></label>)}</div>:<p>{zh?"管理员尚未启用 SmartLingo.net 独立收款通道。":"No SmartLingo-specific payment rail is enabled yet."}</p>}<button disabled={!settings.length} onClick={()=>{if(requireLogin())setStep(3);}}>{zh?"下一步：付款钱包":"Next: payment wallet"} →</button></section>}
    {step===3&&selected&&<section className="crypto-card"><button className="text-button" onClick={()=>setStep(2)}>← {zh?"上一步":"Back"}</button><h2>{zh?"步骤 3：连接钱包或直接转账":"Step 3: Connect a wallet or transfer directly"}</h2><div className="payment-summary"><strong>{selectedPlan.price} · {zh?selectedPlan.zh:selectedPlan.en} · {languages.find(item=>item.code===languageCode)?.[zh?"zh":"en"]}</strong><span>{amountFor(selected,plan)} {selected.tokenSymbol} · {selected.chainName}</span></div><dl><div><dt>{zh?"收款钱包":"Receiver"}</dt><dd>{explorerUrl(selected.chainId,"address",selected.receiverWallet)?<a href={explorerUrl(selected.chainId,"address",selected.receiverWallet)!} target="_blank" rel="noreferrer">{selected.receiverWallet}</a>:selected.receiverWallet}</dd></div><div><dt>{zh?"代币合约":"Token contract"}</dt><dd>{explorerUrl(selected.chainId,"token",selected.tokenContract)?<a href={explorerUrl(selected.chainId,"token",selected.tokenContract)!} target="_blank" rel="noreferrer">{selected.tokenContract}</a>:selected.tokenContract}</dd></div></dl>{!direct?<><div className="wallet-actions"><button onClick={()=>void connectInjected()} disabled={Boolean(busy)}>{busy==="connect"?"…":(zh?"连接钱包":"Connect wallet")}</button><button onClick={()=>void connectWalletConnect()} disabled={Boolean(busy)}>{busy==="walletconnect"?"…":"WalletConnect QR"}</button></div>{provider&&<label className="erc-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{zh?`我确认在 ${selected.chainName} 发送 ${amountFor(selected,plan)} ${selected.tokenSymbol} ERC-20。`:`I confirm sending ${amountFor(selected,plan)} ${selected.tokenSymbol} ERC-20 on ${selected.chainName}.`}</label>}{provider&&<button onClick={()=>void sendPayment()} disabled={!confirmed||Boolean(busy)}>{busy==="send"?"…":(zh?"确认并发送 ERC-20":"Confirm and send ERC-20")}</button>}<button className="text-button" onClick={()=>setDirect(true)}>{zh?"改用直接转账":"Use direct transfer fallback"} →</button></>:<div className="direct-payment"><label>{zh?"付款钱包":"Payer wallet"}<input value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="0x…"/></label><button onClick={()=>void saveDirect()} disabled={busy==="wallet"}>{zh?"保存付款钱包":"Save payer wallet"}</button><p>{balance||(zh?"尚未读取余额":"Balance not loaded")} <button className="inline" onClick={()=>void refreshBalance()} disabled={busy==="balance"}>{zh?"刷新余额":"Refresh balance"}</button></p><label>{zh?"交易哈希（可选）":"Transaction hash (optional)"}<input value={txHash} onChange={e=>setTxHash(e.target.value)} placeholder="0x…"/><small>{zh?"留空将按付款钱包、收款钱包、代币和金额查询近期记录。":"Leave blank to search recent activity by payer, receiver, token, and amount."}</small></label><button onClick={()=>void verify()} disabled={!wallet||busy==="verify"}>{busy==="verify"?"…":(zh?"查询并验证付款":"Find and verify payment")}</button></div>}{message&&<p role="status" className="billing-message">{message}</p>}</section>}
    {status.signedIn&&<section className="crypto-card payment-history"><h2>{zh?"付款记录":"Payment history"}</h2>{status.payments?.length?status.payments.map(item=><article key={item.txHash}><div><strong>{item.languageCode} · {item.planId} · {item.tokenSymbol}</strong><small>{item.chainName} · {item.createdAt}</small></div><a href={explorerUrl(selected?.chainId||0,"tx",item.txHash)||"#"} target="_blank" rel="noreferrer">{item.txHash}</a><span>{item.status} · {item.entitlementStatus}</span></article>):<p>{zh?"暂无链上付款记录。":"No on-chain payments yet."}</p>}</section>}
  </section>;
}
