"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { SentenceBuilderRound } from "./SentenceBuilderRound";
import { useRepeatAfterMePreference } from "./useRepeatAfterMePreference";
import { gradeSprintPlan, type SprintAnswer, type SprintPlan } from "../lib/smartlingo-sprint";

type Stage="vocabulary"|"reading"|"listening"|"writing"|"dialogue"|"complete";
type SprintSpeechRecognition={lang:string;interimResults:boolean;continuous:boolean;start():void;onresult:((event:{results:ArrayLike<{0:{transcript:string}}>})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null};
const LOCALES:Record<string,string>={zh:"zh-CN",en:"en-US",es:"es-ES",ja:"ja-JP",ko:"ko-KR",fr:"fr-FR",de:"de-DE",ru:"ru-RU",it:"it-IT",pt:"pt-PT",ar:"ar-SA",hi:"hi-IN"};
export function DailySprint({lang,classId,durationMinutes,publicPlay=false}:{lang:"zh"|"en";classId:string;durationMinutes:5|10|15|20;publicPlay?:boolean}){
 const zh=lang==="zh";const [runId,setRunId]=useState("");const [plan,setPlan]=useState<SprintPlan|null>(null);const [courseTitle,setCourseTitle]=useState("");const [anonymous,setAnonymous]=useState(false);const [roundIndex,setRoundIndex]=useState(0);const [stage,setStage]=useState<Stage>("vocabulary");const [wordIndex,setWordIndex]=useState(0);const [responses,setResponses]=useState<SprintAnswer[]>([]);const [readingChoice,setReadingChoice]=useState("");const [readingChecked,setReadingChecked]=useState(false);const [dialogueTranscript,setDialogueTranscript]=useState("");const [listening,setListening]=useState(false);const [result,setResult]=useState<{score:number;skillScores:Record<string,number>}|null>(null);const [error,setError]=useState("");const [repeatAfterMe,setRepeatAfterMe]=useRepeatAfterMePreference();
 useEffect(()=>{const zone=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC";fetch(`/api/classes/${encodeURIComponent(classId)}/sprint`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start",durationMinutes,lang,timeZone:zone,source:publicPlay?"play":undefined})}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||(zh?"无法开始今日速成":"Unable to start Today’s Sprint"));return data}).then(data=>{setRunId(data.runId);setPlan(data.plan);setCourseTitle(data.courseTitle);setAnonymous(data.anonymous===true);setResponses(Array.from({length:data.plan.rounds.length},()=>({})));}).catch(cause=>setError(cause.message));},[classId,durationMinutes,lang,publicPlay,zh]);
 const round=plan?.rounds[roundIndex];const word=round?.vocabulary[wordIndex];const totalSteps=(plan?.rounds.length||1)*5;const step=roundIndex*5+["vocabulary","reading","listening","writing","dialogue","complete"].indexOf(stage)+1;const progress=Math.min(100,Math.round(step*100/totalSteps));
 const update=(value:Partial<SprintAnswer>)=>setResponses(current=>current.map((item,index)=>index===roundIndex?{...item,...value}:item));
 function speak(text:string,rate=.78){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=LOCALES[plan?.language||"en"]||"en-US";utterance.rate=rate;window.speechSynthesis.speak(utterance);}
 function nextWord(){if(!round||!word)return;const seen=new Set(responses[roundIndex]?.vocabularySeen||[]);seen.add(word.id);update({vocabularySeen:[...seen]});if(wordIndex+1<round.vocabulary.length){setWordIndex(i=>i+1);if(repeatAfterMe)setTimeout(()=>speak(round.vocabulary[wordIndex+1].form),100);}else{setStage("reading");setWordIndex(0);}}
 function startDialogue(){if(!round)return;speak(round.dialogue.audioText,.72);const browser=window as typeof window&{SpeechRecognition?:new()=>SprintSpeechRecognition;webkitSpeechRecognition?:new()=>SprintSpeechRecognition};const Recognition=browser.SpeechRecognition||browser.webkitSpeechRecognition;if(!Recognition){setError(zh?"当前浏览器不支持语音识别，请使用最新版 Chrome、Edge 或 Safari。":"This browser does not support speech recognition. Use a current Chrome, Edge, or Safari.");return;}const recognition=new Recognition();recognition.lang=LOCALES[plan?.language||"en"]||"en-US";recognition.interimResults=false;recognition.continuous=false;recognition.onresult=event=>{const transcript=String(event.results[0]?.[0]?.transcript||"");setDialogueTranscript(transcript);update({dialogueTranscript:transcript});setListening(false)};recognition.onerror=()=>setListening(false);recognition.onend=()=>setListening(false);setTimeout(()=>{setListening(true);recognition.start()},900);}
 async function nextRound(){if(!plan)return;if(roundIndex+1<plan.rounds.length){setRoundIndex(i=>i+1);setStage("vocabulary");setWordIndex(0);setReadingChoice("");setReadingChecked(false);setDialogueTranscript("");return;}if(anonymous){setResult(gradeSprintPlan(plan,responses));setStage("complete");return;}const response=await fetch(`/api/classes/${encodeURIComponent(classId)}/sprint`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",runId,responses,source:publicPlay?"play":undefined})});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data.error||(zh?"无法保存成绩":"Unable to save score"));return;}setResult(data);setStage("complete");}
 const skillLabels=useMemo(()=>({vocabulary:zh?"词汇":"Vocabulary",reading:zh?"阅读":"Reading",listening:zh?"听力":"Listening",writing:zh?"写作":"Writing",dialogue:zh?"口语":"Speaking"}),[zh]);
 if(error)return <section className="daily-sprint sprint-error"><h1>{zh?"今日速成暂时不可用":"Today’s Sprint is unavailable"}</h1><p role="alert">{error}</p><Link href={`/${lang}/classes/${encodeURIComponent(classId)}/learn`}>{zh?"返回课程":"Back to course"}</Link></section>;
 if(!plan||!round)return <section className="daily-sprint"><p>{zh?"正在编排五技能速成课程…":"Building your five-skill sprint…"}</p></section>;
 return <section className="daily-sprint"><header className="sprint-head"><div><p>TODAY’S SPRINT · {durationMinutes} MIN</p><h1>{zh?"今日速成":"Today’s Sprint"}</h1><span>{courseTitle} · {roundIndex+1}/{plan.rounds.length} {zh?"回合":"rounds"}</span></div><aside><button aria-pressed={repeatAfterMe} onClick={()=>setRepeatAfterMe(!repeatAfterMe)}>{zh?`跟我读：${repeatAfterMe?"开":"关"}`:`Repeat: ${repeatAfterMe?"On":"Off"}`}</button><strong>{progress}%</strong></aside></header><div className="sprint-progress"><span style={{width:`${progress}%`}}/></div>
 {stage==="vocabulary"&&word?<article className="sprint-card"><small>01 · {skillLabels.vocabulary} · {wordIndex+1}/10</small><h2 dir={plan.language==="ar"?"rtl":"ltr"}>{word.form}</h2><b>{word.pronunciation}</b><p>{word.meaning}</p><nav><button onClick={()=>speak(word.form)}>🔊 {zh?"听发音":"Listen"}</button><button onClick={()=>{speak(word.form,.72);}}>{zh?"跟我读":"Repeat after me"}</button><button className="primary-button" onClick={nextWord}>{wordIndex===9?(zh?"进入阅读":"Start reading"):(zh?"下一个词":"Next word")} →</button></nav></article>:null}
 {stage==="reading"?<article className="sprint-card"><small>02 · {skillLabels.reading}</small><h2 dir={plan.language==="ar"?"rtl":"ltr"}>{round.reading.prompt}</h2><p>{zh?"选择这句话的正确意思。":"Choose the correct meaning."}</p><div className="sprint-options">{round.reading.options.map(option=><button className={readingChoice===option.id?"selected":""} disabled={readingChecked} onClick={()=>setReadingChoice(option.id)} key={option.id}>{option.label}</button>)}</div>{readingChecked?<aside className={readingChoice===round.reading.answerId?"correct":"incorrect"}>{readingChoice===round.reading.answerId?(zh?"✓ 回答正确":"✓ Correct"):(zh?"× 再接再厉":"× Keep learning")}</aside>:null}<button className="primary-button" disabled={!readingChoice} onClick={()=>{if(!readingChecked){setReadingChecked(true);update({reading:readingChoice})}else setStage("listening")}}>{readingChecked?(zh?"进入听力":"Start listening"):(zh?"检查":"Check")} →</button></article>:null}
 {stage==="listening"?<article className="sprint-card"><small>03 · {skillLabels.listening}</small><SentenceBuilderRound lang={lang} mode="listening" speechLocale={LOCALES[plan.language]} exercises={[round.listening]} onComplete={answer=>{const parsed=JSON.parse(answer) as string[];update({listening:parsed[0]||""});setStage("writing")}}/></article>:null}
 {stage==="writing"?<article className="sprint-card"><small>04 · {skillLabels.writing}</small><SentenceBuilderRound lang={lang} mode="writing" speechLocale={LOCALES[plan.language]} exercises={[round.writing]} onComplete={answer=>{const parsed=JSON.parse(answer) as string[];update({writing:parsed[0]||""});setStage("dialogue")}}/></article>:null}
 {stage==="dialogue"?<article className="sprint-card sprint-dialogue"><small>05 · {skillLabels.dialogue}</small><h2>{zh?"听完后跟我说":"Listen, then repeat after me"}</h2><blockquote dir={plan.language==="ar"?"rtl":"ltr"}>{round.dialogue.audioText}</blockquote><p>{round.dialogue.prompt}</p><button onClick={startDialogue} disabled={listening}>{listening?(zh?"正在听您说…":"Listening to you…"):(zh?"🔊 播放并开始说":"🔊 Play and speak")}</button>{dialogueTranscript?<aside><b>{zh?"设备听到：":"Device heard: "}</b>{dialogueTranscript}</aside>:null}<button className="primary-button" disabled={!dialogueTranscript} onClick={nextRound}>{roundIndex+1<plan.rounds.length?(zh?"下一回合":"Next round"):(anonymous?(zh?"完成并查看成绩":"Finish and view score"):(zh?"完成并保存成绩":"Finish and save score"))} →</button></article>:null}
 {stage==="complete"&&result?<article className="sprint-result"><span>★</span><h2>{zh?"速成完成！":"Sprint complete!"}</h2><strong>{result.score}<small>/100</small></strong><div>{Object.entries(result.skillScores).map(([skill,score])=><p key={skill}><b>{skillLabels[skill as keyof typeof skillLabels]}</b><span>{score}</span></p>)}</div>{anonymous?<section className="sprint-signup"><h3>{zh?"保存今天的成绩":"Save today’s score"}</h3><p>{zh?"本次匿名学习不会写入账户或数据库。免费注册或登录后，即可保存进度、参加排行榜并继续学习。":"This anonymous session was not written to an account or database. Create a free account or sign in to save progress, join rankings, and keep learning."}</p><nav><Link href={`/${lang}/auth/sign-up?returnTo=${encodeURIComponent(`/${lang}/play?language=${plan.language}`)}`}>{zh?"免费注册":"Create free account"} →</Link><Link href={`/${lang}/auth/login?returnTo=${encodeURIComponent(`/${lang}/play?language=${plan.language}`)}`}>{zh?"登录":"Sign in"}</Link></nav></section>:<nav><Link href={`/${lang}/play/rankings?language=${plan.language}`}>{zh?"查看排行榜":"View rankings"} →</Link><Link href={`/${lang}/classes/${encodeURIComponent(classId)}/learn`}>{zh?"返回课程":"Back to course"}</Link></nav>}</article>:null}
 <style>{`.daily-sprint{width:min(980px,calc(100% - 32px));min-height:70vh;margin:42px auto 90px;color:#17342c}.sprint-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:end}.sprint-head p,.sprint-card>small{color:#087d62;font-size:12px;font-weight:950;letter-spacing:.12em}.sprint-head h1{margin:6px 0;font-size:clamp(40px,6vw,70px)}.sprint-head aside{display:flex;align-items:center;gap:12px}.sprint-head aside button{padding:11px;border:1px solid #afc8be;border-radius:12px;background:#fff}.sprint-head aside strong{font-size:34px}.sprint-progress{height:11px;margin:24px 0;border-radius:99px;background:#dce8e3;overflow:hidden}.sprint-progress span{display:block;height:100%;background:#18bf84}.sprint-card,.sprint-result{padding:clamp(24px,5vw,54px);border:1px solid #bed1c8;border-radius:28px;background:#fff;box-shadow:0 22px 65px #143d3020}.sprint-card>h2{margin:22px 0 10px;font-size:clamp(38px,7vw,76px)}.sprint-card>b{font-size:20px;color:#087d62}.sprint-card>p{font-size:19px;color:#536c63}.sprint-card>nav{display:flex;flex-wrap:wrap;gap:10px;margin-top:35px}.sprint-card button,.sprint-result a{min-height:48px;padding:11px 17px;border:1px solid #b8cbc3;border-radius:13px;background:#fff;color:#17342c;font-weight:850}.sprint-card .primary-button,.sprint-result a:first-child{border:0;background:#0a7d61;color:#fff}.sprint-options{display:grid;gap:9px;margin:25px 0}.sprint-options button{text-align:left}.sprint-options .selected{border-color:#087d62;background:#e2f5ed}.sprint-card>aside{margin:16px 0;padding:14px;border-radius:12px;background:#e1f7ea}.sprint-card>aside.incorrect{background:#ffe3e3;color:#a23232}.sprint-dialogue blockquote{padding:25px;border:0;border-radius:18px;background:#123f35;color:#fff;font-size:clamp(25px,4vw,42px)}.sprint-dialogue>.primary-button{display:block;margin-top:25px}.sprint-result{text-align:center}.sprint-result>span{font-size:70px;color:#f1b629}.sprint-result h2{font-size:42px}.sprint-result>strong{font-size:80px;color:#087d62}.sprint-result>strong small{font-size:20px}.sprint-result>div{max-width:520px;margin:25px auto}.sprint-result p{display:flex;justify-content:space-between;padding:10px;border-bottom:1px solid #dde7e2}.sprint-result nav{display:flex;justify-content:center;flex-wrap:wrap;gap:10px}.sprint-signup{max-width:680px;margin:30px auto 0;padding:24px;border-radius:20px;background:#e5f6ee}.sprint-signup h3{margin:0;font-size:28px}.sprint-signup p{display:block;margin:10px 0 20px;border:0;line-height:1.65}.sprint-signup nav{display:flex;justify-content:center;flex-wrap:wrap;gap:10px}@media(max-width:620px){.sprint-head{grid-template-columns:1fr}.sprint-head aside{justify-content:space-between}.sprint-card>nav>*{width:100%}}`}</style></section>;
}
