import Link from "next/link";
import { SiteFooter } from "./SiteFooter";
import { SiteHeader } from "./SiteHeader";

export type EditorialCard = { label: string; title: string; body: string; date?: string; source?: string; url?: string; status?: string; location?: string };

export function EditorialPage({ lang, eyebrow, title, intro, cards, kind = "news", editionDate }: { lang: "en" | "zh"; eyebrow: string; title: string; intro: string; cards: EditorialCard[]; kind?: "news" | "events"; editionDate?: string }) {
  const zh = lang === "zh";
  return <main className="editorial-page"><SiteHeader lang={lang}/><div className="editorial-main"><section className="editorial-hero"><div><p className="section-kicker">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></div><div className="editorial-stamp"><span>{zh ? (kind === "news" ? "每日版本" : "赛事日历") : (kind === "news" ? "DAILY EDITION" : "EVENT CALENDAR")}<b>{kind === "news" ? (editionDate?.slice(5) ?? "—") : cards.length}</b>{zh ? (kind === "news" ? "动态更新" : "已核实活动") : (kind === "news" ? "LIVE CONTENT" : "VERIFIED EVENTS")}</span></div></section><div className="editorial-section-title"><h2>{zh ? (kind === "news" ? "今日简报" : "活动与赛事") : (kind === "news" ? "Today’s briefing" : "Events and tournaments")}</h2><span>{zh ? `${cards.length} 条已核实来源` : `${cards.length} verified source items`}</span></div><section className={`editorial-grid ${kind}`}>{cards.map((card,index) => <article key={card.title} className={index === 0 ? "featured" : ""}><div className="editorial-meta"><span>{card.label}</span><time>{card.date}</time></div>{kind === "events" && <div className="event-facts"><strong>{card.status}</strong><span>{card.location}</span></div>}<h2>{card.title}</h2><p>{card.body}</p>{card.url ? <a href={card.url} target="_blank" rel="noreferrer">{zh ? `查看 ${card.source ?? "主办方信息"} ↗` : `Open ${card.source ?? "organizer information"} ↗`}</a> : <Link href={`/${lang}/project`}>{zh ? "查看相关进度" : "View related progress"} →</Link>}</article>)}</section><p className="editorial-policy">{zh ? (kind === "events" ? "活动原则：仅收录可核实的赛事与社区活动；时间、地点、报名和赛果均以主办方最新公告为准。" : "编辑原则：摘要公开报道与主办方公告，并链接原始来源；不虚构报名、排名或赛事结果。定时检查不等于必须发布，只有核实后才更新。") : (kind === "events" ? "Events policy: only verifiable tournaments and community events are listed. Dates, venues, registration, and results must be confirmed with the organizer’s latest notice." : "Editorial policy: public reporting and organizer announcements are summarized with original links. Scheduled checks publish only when a meaningful item has been verified.")}</p></div><SiteFooter lang={lang}/></main>;
}
