"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import type { RealtimeCallSession } from "./RealtimeCallStage";
import { usePersistentCall } from "./PersistentCallProvider";

type Member = { id: string; displayName: string; imageUrl?: string; online: boolean; email?: string };
type Attachment = { id: string; name: string; mimeType: string; size: number; url: string };
type CallInvite = { id: string; mode: "audio" | "video"; expiresAt: number };
type ActiveCall = CallInvite & { status: "active" | "ended" | "expired"; startedBy: string };
type ChatMessage = { id: string; body: string; createdAt: number; senderId: string; senderName: string; guru?: boolean; edited?: boolean; attachment?: Attachment | null; call?: CallInvite | null };
type Room = { currentUserId: string; thread: { kind: string; subject?: string }; members: Member[]; messages: ChatMessage[]; activeCall?: ActiveCall | null };
const MAX_ATTACHMENT_BYTES = 900 * 1024;
const URL_PATTERN = /((?:https?:\/\/|www\.)[^\s<]+)/gi;

export function LiveChatRoom({ threadId, lang }: { threadId: string; lang: string }) {
  const zh = lang === "zh";
  const { openCall } = usePersistentCall();
  const [room, setRoom] = useState<Room | null>(null); const [draft, setDraft] = useState(""); const [guruLive, setGuruLive] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [attachOpen, setAttachOpen] = useState(false); const [recording, setRecording] = useState(false); const [memberOpen, setMemberOpen] = useState(false); const [memberQuery, setMemberQuery] = useState(""); const [directory, setDirectory] = useState<Member[]>([]); const [messageMenu, setMessageMenu] = useState(""); const [editingId, setEditingId] = useState(""); const [editDraft, setEditDraft] = useState(""); const [copiedId, setCopiedId] = useState("");
  const logRef = useRef<HTMLDivElement>(null); const lastKeyboardAt = useRef(0); const initialized = useRef(false); const handled = useRef(new Set<string>()); const cameraInput = useRef<HTMLInputElement>(null); const photoInput = useRef<HTMLInputElement>(null); const fileInput = useRef<HTMLInputElement>(null); const recorder = useRef<MediaRecorder | null>(null);
  const load = useCallback(async () => { const response = await fetch(`/api/messages?thread=${encodeURIComponent(threadId)}`, { cache: "no-store" }); if (response.ok) setRoom(await response.json() as Room); }, [threadId]);
  useEffect(() => { lastKeyboardAt.current = Date.now(); const startup = window.setTimeout(load, 0); const timer = window.setInterval(load, 2000); return () => { window.clearTimeout(startup); window.clearInterval(timer); recorder.current?.stream.getTracks().forEach(track => track.stop()); }; }, [load]);
  useEffect(() => { logRef.current?.scrollTo({ top: logRef.current.scrollHeight, behavior: initialized.current ? "smooth" : "auto" }); }, [room?.messages.length]);
  useEffect(() => { if (!room) return; if (!initialized.current) { room.messages.forEach(message => handled.current.add(message.id)); initialized.current = true; return; } if (!guruLive) return; const latest = [...room.messages].reverse().find(message => message.senderId !== room.currentUserId && !message.guru && !message.attachment && !message.call && Boolean(message.body) && !handled.current.has(message.id)); if (!latest) return; let timer = 0; const answerWhenIdle = () => { timer = window.setTimeout(async () => { const remaining = lastKeyboardAt.current + 10000 - Date.now(); if (remaining > 0) { answerWhenIdle(); return; } handled.current.add(latest.id); try { const context = room.messages.filter(message => message.body && !message.call).slice(-10).map(message => ({ role: message.senderId === room.currentUserId ? "assistant" : "user", content: message.body })); const ai = await fetch("/api/assistant", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ feature: "chat_guru", language: lang, messages: context }) }); const answer = await ai.json() as { reply?: string }; if (ai.ok && answer.reply) await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "guru_reply", threadId, body: answer.reply }) }); await load(); } catch { setError(zh ? "智能导师暂时无法回复。" : "Guru could not reply right now."); } }, Math.max(0, lastKeyboardAt.current + 10000 - Date.now())); }; answerWhenIdle(); return () => window.clearTimeout(timer); }, [room, guruLive, lang, threadId, load, zh]);

  async function send() { const body = draft.trim(); if (!body || busy) return; setBusy(true); setError(""); const response = await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "reply", threadId, body }) }); if (response.ok) { setDraft(""); await load(); } else setError(zh ? "消息发送失败。" : "Message could not be sent."); setBusy(false); }
  async function loadDirectory(query = memberQuery) { setError(""); const response = await fetch(`/api/messages?thread=${encodeURIComponent(threadId)}&directory=1&q=${encodeURIComponent(query.trim())}`, { cache: "no-store" }); if (response.ok) setDirectory(((await response.json()) as { members: Member[] }).members); else setError(zh ? "无法加载会员列表。" : "Member list could not be loaded."); }
  async function addMember(memberId: string) { if (busy) return; setBusy(true); const response = await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "add_member", threadId, memberId }) }); if (response.ok) { setMemberOpen(false); setMemberQuery(""); setDirectory([]); await load(); } else setError(zh ? "无法添加该会员。" : "That member could not be added."); setBusy(false); }
  async function saveEdit(messageId: string) { const body = editDraft.trim(); if (!body || busy) return; setBusy(true); const response = await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "edit_message", threadId, messageId, body }) }); if (response.ok) { setEditingId(""); setEditDraft(""); setMessageMenu(""); await load(); } else setError(zh ? "无法编辑消息。" : "Message could not be edited."); setBusy(false); }
  async function deleteMessage(messageId: string) { if (!window.confirm(zh ? "删除这条消息？" : "Delete this message?")) return; setBusy(true); const response = await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "delete_message", threadId, messageId }) }); if (response.ok) { setMessageMenu(""); await load(); } else setError(zh ? "无法删除消息。" : "Message could not be deleted."); setBusy(false); }
  async function copyMessage(message: ChatMessage) { const value = message.body || message.attachment?.url || ""; if (!value) return; await navigator.clipboard.writeText(value); setCopiedId(message.id); window.setTimeout(() => setCopiedId(""), 1400); }
  async function upload(file?: File) { if (!file || busy) return; setAttachOpen(false); setError(""); if (file.size > MAX_ATTACHMENT_BYTES) { setError(zh ? "附件发送失败；文件需小于 900 KB。" : "Attachment failed; files must be under 900 KB."); return; } setBusy(true); const form = new FormData(); form.set("threadId", threadId); form.set("file", file); const response = await fetch("/api/message-media", { method: "POST", body: form }); if (!response.ok) setError(zh ? "附件发送失败；请使用小于 900 KB 的支持文件。" : "Attachment failed; use a supported file under 900 KB."); else await load(); setBusy(false); }
  async function toggleRecording() { if (recording && recorder.current) { recorder.current.stop(); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mediaRecorder = new MediaRecorder(stream); const chunks: Blob[] = []; mediaRecorder.ondataavailable = event => { if (event.data.size) chunks.push(event.data); }; mediaRecorder.onstop = () => { setRecording(false); stream.getTracks().forEach(track => track.stop()); const type = mediaRecorder.mimeType || "audio/webm"; void upload(new File(chunks, `voice-${Date.now()}.webm`, { type })); }; recorder.current = mediaRecorder; mediaRecorder.start(); setRecording(true); } catch { setError(zh ? "无法使用麦克风，请检查浏览器权限。" : "Microphone unavailable. Check browser permission."); } }
  async function call(action: "start" | "join", mode: "audio" | "video", callId?: string) { if (busy || !room) return; setBusy(true); setError(""); const response = await fetch("/api/messages/calls", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(action === "start" ? { action, threadId, mode } : { action, callId }) }); const payload = await response.json().catch(() => null) as (RealtimeCallSession & { error?: string }) | null; if (response.ok && payload?.authToken) { const peers = room.members.filter(member => member.id !== room.currentUserId); const title = room.thread.subject || peers.slice(0, 3).map(member => member.displayName).join(", ") || (zh ? "实时通话" : "Live call"); openCall(payload, { threadId, threadTitle: title, currentUserId: room.currentUserId }); await load(); } else setError(zh ? "暂时无法加入通话，请稍后再试。" : "Could not join the call. Try again shortly."); setBusy(false); }
  function callCard(invite: CallInvite, senderName: string) { const active = room?.activeCall?.id === invite.id && room.activeCall.status === "active"; const label = invite.mode === "video" ? (zh ? "视频通话" : "Video call") : (zh ? "音频通话" : "Audio call"); return <div className={`call-invite-card ${active ? "active" : "ended"}`}><span aria-hidden="true">{invite.mode === "video" ? "▣" : "◖"}</span><div><b>{label}</b><small>{active ? (zh ? `${senderName} 已发起，点击加入` : `${senderName} started this call. Tap to join.`) : (zh ? "通话已结束" : "Call ended")}</small></div>{active && <button type="button" onClick={() => void call("join", invite.mode, invite.id)} disabled={busy}>{zh ? "加入" : "Join"}</button>}</div>; }
  function attachmentView(item: Attachment) { const downloadUrl = `${item.url}&disposition=attachment`; const preview = item.mimeType.startsWith("image/") ? <img className="chat-attachment-image" src={item.url} alt={item.name}/> : item.mimeType.startsWith("audio/") ? <audio className="chat-attachment-player" controls src={item.url}/> : item.mimeType.startsWith("video/") ? <video className="chat-attachment-video" controls src={item.url}/> : <span className="chat-attachment-file">📎 {item.name}</span>; return <div className="chat-attachment-card">{preview}<div className="chat-attachment-actions"><a href={item.url} target="_blank" rel="noreferrer">{zh ? "查看" : "View"}</a><a href={downloadUrl} target="_blank" rel="noreferrer">{zh ? "下载" : "Download"}</a></div></div>; }
  function messageText(body: string) { return body.split(URL_PATTERN).map((part, index) => { if (!/^(?:https?:\/\/|www\.)/i.test(part)) return part; const href = part.toLowerCase().startsWith("www.") ? `https://${part}` : part; return <a className="chat-url-link" key={`${href}-${index}`} href={href} target="_blank" rel="noopener noreferrer">{part}</a>; }); }
  const others = room?.members.filter(member => member.id !== room.currentUserId) || []; const other = others[0]; const classRoom = room?.thread.kind === "class"; const group = Boolean(room && (room.thread.kind === "group" || classRoom || room.members.length > 2)); const roomTitle = group ? (room?.thread.subject || others.slice(0, 3).map(member => member.displayName).join(", ")) : other?.displayName; const groupPresenceZh = `${room?.members.length || 0} 位成员 · ${room?.members.filter(member => member.online).length || 0} 位在线`; const groupPresenceEn = `${room?.members.length || 0} members · ${room?.members.filter(member => member.online).length || 0} online`; const presenceText = group ? (zh ? groupPresenceZh : groupPresenceEn) : other?.online ? (zh ? "在线" : "Online") : (zh ? "离线 · 消息会保留" : "Offline · messages are saved");

  return <><section className="live-chat-shell" data-layout-ready={room ? "true" : undefined} data-layout-text-fit="live-chat-shell">
    <header className="live-chat-header"><Link href={`/${lang}/messages`} aria-label={zh ? "返回消息" : "Back to messages"}>←</Link><span className="live-peer-avatar">{other?.imageUrl ? <img src={other.imageUrl} alt=""/> : group ? `${room?.members.length || 0}` : other?.displayName?.slice(0,1).toUpperCase()}</span><div><h1>{roomTitle || (zh ? "会员" : "Member")}</h1><p className={group ? (room?.members.some(member => member.online) ? "online" : "") : (other?.online ? "online" : "")}><i/>{presenceText}</p></div><div className="live-header-actions"><button className={`live-call-button${classRoom ? " class-audio-join" : ""}`} type="button" aria-label={classRoom ? (zh ? "加入语音通话" : "Join audio call") : (zh ? "发起音频通话" : "Start audio call")} title={zh ? "音频通话" : "Audio call"} onClick={() => void call("start", "audio")} disabled={busy}>{classRoom ? (zh ? "加入语音通话" : "Join audio call") : "◖"}</button>{!classRoom && <button className="live-call-button" type="button" aria-label={zh ? "发起视频通话" : "Start video call"} title={zh ? "视频通话" : "Video call"} onClick={() => void call("start", "video")} disabled={busy}>▣</button>}{!classRoom && <button className="live-add-members" type="button" aria-label={zh ? "添加成员" : "Add members"} onClick={() => { const next = !memberOpen; setMemberOpen(next); if (next) void loadDirectory(""); }}>＋</button>}<label className="guru-live-toggle"><input type="checkbox" checked={guruLive} onChange={event => setGuruLive(event.target.checked)}/><span>{zh ? "智能导师实时辅助" : "Guru Live"}</span></label></div></header>
    {memberOpen && <aside className="member-picker" aria-label={zh ? "添加聊天室成员" : "Add chat members"}><div className="member-picker-title"><div><b>{zh ? "添加成员" : "Add members"}</b><small>{zh ? "从会员列表选择，或输入完整邮箱查找。" : "Choose from the member list or enter an exact email."}</small></div><button type="button" onClick={() => setMemberOpen(false)} aria-label={zh ? "关闭" : "Close"}>×</button></div><form onSubmit={event => { event.preventDefault(); void loadDirectory(); }}><input type="search" value={memberQuery} onChange={event => setMemberQuery(event.target.value)} placeholder={zh ? "姓名或完整邮箱" : "Name or exact email"}/><button type="submit">{zh ? "查找" : "Find"}</button></form><div className="member-picker-list">{directory.length ? directory.map(member => <button type="button" key={member.id} onClick={() => void addMember(member.id)} disabled={busy}><span className="picker-avatar">{member.imageUrl ? <img src={member.imageUrl} alt=""/> : member.displayName.slice(0,1).toUpperCase()}</span><span><b>{member.displayName}</b>{member.email && <small>{member.email}</small>}<small className={member.online ? "online" : ""}>{member.online ? (zh ? "在线" : "Online") : (zh ? "离线" : "Offline")}</small></span><i>＋</i></button>) : <p>{zh ? "没有可添加的会员。" : "No members available to add."}</p>}</div></aside>}
    <div className="live-chat-log" ref={logRef}>{room?.messages.length ? room.messages.map(message => { const mine = message.senderId === room.currentUserId; const editable = mine && Boolean(message.body) && !message.guru && !message.attachment && !message.call; return <article key={message.id} className={`${mine ? "mine" : "theirs"}${message.guru ? " guru" : ""}${message.call ? " call-message" : ""}`}><small>{message.guru ? (zh ? "智能导师" : "Guru") : message.senderName}</small>{message.attachment && attachmentView(message.attachment)}{message.call && callCard(message.call, message.senderName)}{editingId === message.id ? <div className="message-edit"><textarea value={editDraft} onChange={event => setEditDraft(event.target.value)} autoFocus/><div><button type="button" onClick={() => { setEditingId(""); setEditDraft(""); }}>{zh ? "取消" : "Cancel"}</button><button type="button" onClick={() => void saveEdit(message.id)} disabled={!editDraft.trim() || busy}>{zh ? "保存" : "Save"}</button></div></div> : message.body && <p>{messageText(message.body)}</p>}<div className="message-meta"><time>{message.edited && <span>{zh ? "已编辑 · " : "Edited · "}</span>}{new Date(message.createdAt * 1000).toLocaleTimeString(zh ? "zh-CN" : "en-US", { hour: "numeric", minute: "2-digit" })}</time><div className="message-tools">{!message.call && <button type="button" onClick={() => void copyMessage(message)} aria-label={zh ? "复制" : "Copy"}>{copiedId === message.id ? "✓" : "▣"}</button>}{editable && <span className="message-more"><button type="button" onClick={() => setMessageMenu(value => value === message.id ? "" : message.id)} aria-label={zh ? "更多" : "More"}>…</button>{messageMenu === message.id && <span className="message-menu"><button type="button" onClick={() => { setEditingId(message.id); setEditDraft(message.body); setMessageMenu(""); }}>{zh ? "编辑" : "Edit"}</button><button type="button" className="danger" onClick={() => void deleteMessage(message.id)}>{zh ? "删除" : "Delete"}</button></span>}</span>}</div></div></article>; }) : <div className="live-empty"><b>{zh ? "开始实时聊天" : "Start your live chat"}</b><p>{zh ? "这里的消息会保留，方便以后继续交流。" : "Messages stay here so you can continue later."}</p></div>}</div>
    <div className="live-chat-compose">{guruLive && <p className="guru-live-note">{zh ? "收到新消息后，如您 10 秒未输入，智能导师会协助回复。" : "After a new message, Guru can respond when you have not typed for 10 seconds."}</p>}<div className="live-compose-row"><div className="attach-control"><button className="compose-icon add-attachment" type="button" aria-label={zh ? "添加附件" : "Add attachment"} onClick={() => setAttachOpen(value => !value)}>+</button>{attachOpen && <div className="attachment-menu"><button type="button" onClick={() => cameraInput.current?.click()}>{zh ? "拍照" : "Take photo"}</button><button type="button" onClick={() => photoInput.current?.click()}>{zh ? "选择照片" : "Photo library"}</button><button type="button" onClick={() => fileInput.current?.click()}>{zh ? "选择文件" : "Choose file"}</button></div>}<input ref={cameraInput} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={event => { void upload(event.target.files?.[0]); event.target.value = ""; }}/><input ref={photoInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event => { void upload(event.target.files?.[0]); event.target.value = ""; }}/><input ref={fileInput} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,audio/mpeg,audio/mp4,audio/ogg,audio/wav,audio/webm,video/mp4,video/webm" onChange={event => { void upload(event.target.files?.[0]); event.target.value = ""; }}/></div><textarea value={draft} onChange={event => { setDraft(event.target.value); lastKeyboardAt.current = Date.now(); }} onKeyDown={event => { lastKeyboardAt.current = Date.now(); if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder={zh ? "输入消息…" : "Write a message…"}/><button className={`compose-icon voice-record${recording ? " recording" : ""}`} type="button" aria-label={recording ? (zh ? "停止并发送录音" : "Stop and send recording") : (zh ? "录音" : "Record voice")} onClick={toggleRecording}><span/></button><button className="compose-icon live-send" onClick={send} disabled={busy || !draft.trim()} aria-label={zh ? "发送" : "Send"}>↑</button></div>{recording && <p className="recording-status">● {zh ? "正在录音，点击麦克风发送" : "Recording — tap the microphone to send"}</p>}{error && <p className="live-chat-error">{error}</p>}</div>
  </section></>;
}
