"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Room={id:string;code:string;title:string;description:string;subject:string;classType:"public"|"trial"|"private";streamingMode:"audio"|"video";startsAt:number;hostName:string;streamActive:number;tuitionCents:number;trialMinutes:number};
export function LiveClassDirectory({lang="en",initialView="public",basePath="/classrooms"}:{lang?:"zh"|"en";initialView?:string;basePath?:string}){
  const zh=lang==="zh",[view,setView]=useState(initialView),[joinedView,setJoinedView]=useState<"public"|"trial"|"private">("public"),[rooms,setRooms]=useState<Room[]>([]),[joinedRooms,setJoinedRooms]=useState<Room[]>([]),[canCreate,setCanCreate]=useState(false),[quota,setQuota]=useState<{used:number;max:number|null}>({used:0,max:5}),[loading,setLoading]=useState(true);
  useEffect(()=>{setLoading(true);const managed=fetch(`/api/classrooms?view=${encodeURIComponent(view)}`,{cache:"no-store"}).then(r=>r.json());const joined=view==="mine"?fetch(`/api/classrooms?view=joined_${joinedView}`,{cache:"no-store"}).then(r=>r.json()):Promise.resolve({classes:[]});Promise.all([managed,joined]).then(([data,joinedData])=>{if(view==="mine"&&!data.signedIn){window.location.assign(`/${lang}/auth/login?returnTo=${encodeURIComponent(`${basePath}?view=mine`)}`);return;}setRooms(data.classes||[]);setJoinedRooms(joinedData.classes||[]);setCanCreate(Boolean(data.canCreate));setQuota({used:Number(data.used||0),max:data.max===null?null:Number(data.max||5)});}).finally(()=>setLoading(false));},[view,joinedView,lang,basePath]);
  const cards=(items:Room[])=>items.length?<section className="class-card-list">{items.map(room=><article className="class-card" key={room.id}><div><p>{room.subject||(zh?"实时课堂":"LIVE CLASS")}</p><h2>{room.title}</h2><span>{room.description||(zh?"教师尚未添加课程介绍。":"The Teacher has not added a description.")}</span><small>{new Date(room.startsAt*1000).toLocaleString(zh?"zh-CN":"en-US")} · {room.hostName} · {room.streamingMode==="audio"?(zh?"音频":"Audio"):(zh?"音视频":"A/V")}</small></div><div><i className={room.streamActive?"live":""}>{room.streamActive?(zh?"直播中":"LIVE"):(zh?"待开始":"READY")}</i>{room.classType==="trial"&&<b>$${(room.tuitionCents/100).toFixed(2)}</b>}<Link href={`${basePath}/${room.code}`}>{zh?"进入 →":"Enter →"}</Link></div></article>)}</section>:<div className="class-empty compact"><h2>{zh?"这里暂时还没有课程":"No classes here yet"}</h2><p>{zh?"请选择其他课堂类型或稍后再来。":"Check another class type or return later."}</p></div>;
  return <main className="class-directory-page"><section className="class-directory-hero"><p>{view==="mine"?(zh?"我的课程":"MY CLASSES"):"LIVE CLASSES"}</p><h1>{view==="mine"?(zh?"创建、管理与加入的课程":"Classes you create, manage, and join"):(zh?"与社区一起学习":"Learn with the community")}</h1><span>{view==="mine"?(quota.max===null?(zh?"平台管理员可无限创建课程。":"Platform administrators can create unlimited classes."):(zh?`教师课程额度：${quota.used} / ${quota.max}`:`Teacher class quota: ${quota.used} / ${quota.max}`)):(zh?"进入公课、先试课再加入，或通过邀请参加私课。":"Enter a public class, try a course, or join a private class by invitation.")}</span>{canCreate&&<Link className="class-create-link" href={`${basePath}/create`}>{zh?"创建课程":"Create class"}</Link>}</section><nav className="class-tabs" aria-label={zh?"课堂目录":"Class directory"}><button className={view==="public"?"active":""} onClick={()=>setView("public")}>{zh?"公课":"Public"}</button><button className={view==="trial"?"active":""} onClick={()=>setView("trial")}>{zh?"试课":"Trial"}</button><button className={view==="private"?"active":""} onClick={()=>setView("private")}>{zh?"私课":"Private"}</button><button className={view==="mine"?"active":""} onClick={()=>setView("mine")}>{zh?"我的课程":"My classes"}</button></nav>{loading?<div className="class-empty">{zh?"正在加载课程…":"Loading classes…"}</div>:view==="mine"?<><section className="my-class-section"><h2>{zh?"我创建或管理的课程":"Classes I create or manage"}</h2><p>{zh?"教师与联合教师可以在这里管理课程。":"Teachers and Co-teachers can manage classes here."}</p>{cards(rooms)}</section><section className="my-class-section"><h2>{zh?"我加入的课程":"Classes I joined"}</h2><nav className="class-tabs joined-tabs"><button className={joinedView==="public"?"active":""} onClick={()=>setJoinedView("public")}>{zh?"公课":"Public"}</button><button className={joinedView==="trial"?"active":""} onClick={()=>setJoinedView("trial")}>{zh?"试课":"Trial"}</button><button className={joinedView==="private"?"active":""} onClick={()=>setJoinedView("private")}>{zh?"私课":"Private"}</button></nav>{cards(joinedRooms)}</section></>:cards(rooms)}</main>;
}
