"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Card = { id: string; form: string; pronunciation: string; meaningEn: string; meaningZh: string; sceneKey: string };
type Question = { id: string; mode: "recognition" | "listening" | "recall" | "typing"; promptEn: string; promptZh: string; audioText?: string; options?: { value: string; labelEn: string; labelZh: string }[] };
type Payload = { deck?: { title: string; ownerName: string; targetLanguage: string; cards: Card[] }; challenge?: Question[]; signedIn?: boolean; provisionalPoints?: number; error?: string };

export function PublicSmartCardChallenge({ lang, token }: { lang: "en" | "zh"; token: string }) {
  const zh = lang === "zh"; const [data, setData] = useState<Payload | null>(null); const [index, setIndex] = useState(0);
  const [flipped, setFlipped] = useState(false); const [answers, setAnswers] = useState<Record<string, string>>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/smartcards/${encodeURIComponent(token)}`, { cache: "no-store" }); const payload = await response.json().catch(() => ({})) as Payload; if (!response.ok) throw new Error(payload.error); setData(payload); }, [token]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch(() => setMessage(zh ? "找不到这套 SmartCard。" : "This SmartCard deck is unavailable.")); }, 0); return () => window.clearTimeout(timer); }, [load, zh]);
  const cards = data?.deck?.cards || []; const card = cards[index] || null;
  const questions = data?.challenge || [];
  function play(text: string) { if (!("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(text)); }
  async function submit(action: "challenge" | "claim") {
    setBusy(true); setMessage("");
    const response = await fetch(`/api/smartcards/${encodeURIComponent(token)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, answers, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }) });
    const payload = await response.json().catch(() => ({})) as { error?: string; score?: number; earnedPoints?: number; provisionalPoints?: number; claimRequired?: boolean; claimedPoints?: number };
    if (!response.ok) {
      setMessage(payload.error || (zh ? "暂时无法完成。" : "Unable to complete this action."));
      setBusy(false); return;
    }
    if (action === "claim") {
      setMessage(zh ? `已将 ${payload.claimedPoints || 0} 点安全存入课程积分。` : `${payload.claimedPoints || 0} points were added to your course credit.`);
    } else if (data?.signedIn && (payload.provisionalPoints || 0) > 0) {
      const claimResponse = await fetch(`/api/smartcards/${encodeURIComponent(token)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "claim" }) });
      const claim = await claimResponse.json().catch(() => ({})) as { error?: string; claimedPoints?: number };
      setMessage(claimResponse.ok
        ? (zh ? `得分 ${payload.score}/100；${claim.claimedPoints || 0} 点已自动存入课程积分。` : `Score ${payload.score}/100; ${claim.claimedPoints || 0} points were added to your course credit automatically.`)
        : (zh ? `得分 ${payload.score}/100；积分仍保存在此设备，请稍后点击领取。` : `Score ${payload.score}/100; points remain on this device, so please claim them again later.`));
    } else {
      setMessage(zh ? `得分 ${payload.score}/100，本次获得 ${payload.earnedPoints || 0} 点，待领取共 ${payload.provisionalPoints || 0} 点。` : `Score ${payload.score}/100. Earned ${payload.earnedPoints || 0}; ${payload.provisionalPoints || 0} provisional points await claim.`);
    }
    await load(); setBusy(false);
  }
  return <main className="public-smartcards"><section className="public-smartcards-hero"><Link href={`/${lang}/smartcards`}>← {zh ? "选择其他语言" : "Choose another language"}</Link><p>SMARTLINGO SMARTCARDS</p><h1>{data?.deck?.title || (zh ? "免费智能词卡挑战" : "Free SmartCard challenge")}</h1><p>{zh ? "无需登录即可学习和挑战。达到 80 分可获得待领取积分；登录后积分才会安全入账并用于抵扣初级课程月费。" : "Learn and challenge without signing in. Score 80 to earn provisional points; sign in later to secure them and offset a Beginner monthly fee."}</p><div><strong>{data?.provisionalPoints || 0}</strong><span>{zh ? "待领取积分" : "provisional points"}</span><small>100 {zh ? "点抵 1 美元" : "points offset $1"}</small></div></section>
    {card ? <section className="public-card-stage"><div className={`public-card ${flipped ? "flipped" : ""}`} onClick={() => setFlipped(value => !value)} role="button" tabIndex={0} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") setFlipped(value => !value); }}><small>{index + 1} / {cards.length} · {card.sceneKey}</small><strong>{flipped ? card.form : (zh ? card.meaningZh : card.meaningEn)}</strong>{flipped && card.pronunciation ? <span>{card.pronunciation}</span> : null}<b>{flipped ? (zh ? "再点一次看提示" : "Tap for prompt") : (zh ? "点击翻卡" : "Tap to flip")}</b></div><nav><button disabled={index === 0} onClick={() => { setIndex(value => value - 1); setFlipped(false); }}>← {zh ? "上一张" : "Previous"}</button><button disabled={index >= cards.length - 1} onClick={() => { setIndex(value => value + 1); setFlipped(false); }}>{zh ? "下一张" : "Next"} →</button></nav></section> : null}
    {questions.length ? <section className="public-card-quiz"><h2>{zh ? "完成混合挑战" : "Take the mixed-mode challenge"}</h2><p>{zh ? "题目混合词义识别、听辨、主动回忆和一次书写；速度不会影响积分。可先翻卡学习，再一次提交。" : "Questions mix recognition, listening, active recall, and one typing task. Speed never changes points. Study first, then submit once."}</p><div>{questions.map((question, itemIndex) => <fieldset key={question.id}><legend>{itemIndex + 1}. {zh ? question.promptZh : question.promptEn}</legend>{question.audioText ? <button type="button" onClick={() => play(question.audioText || "")}>▶ {zh ? "播放发音" : "Play audio"}</button> : null}{question.options ? <div>{question.options.map(option => <label key={option.value}><input type="radio" name={question.id} value={option.value} checked={answers[question.id] === option.value} onChange={() => setAnswers(current => ({ ...current, [question.id]: option.value }))}/><span>{zh ? option.labelZh : option.labelEn}</span></label>)}</div> : <input aria-label={zh ? "目标语言答案" : "Target-language answer"} value={answers[question.id] || ""} autoComplete="off" maxLength={120} onChange={event => setAnswers(current => ({ ...current, [question.id]: event.target.value }))}/>}</fieldset>)}</div><button disabled={busy || questions.some(question => !answers[question.id]?.trim())} onClick={() => void submit("challenge")}>{busy ? "…" : (zh ? "提交挑战并计算积分" : "Submit challenge and calculate points")}</button></section> : null}
    <section className="public-card-claim"><h2>{zh ? "保留您的学习成果" : "Keep your learning progress"}</h2><p>{data?.signedIn ? (zh ? "当前已登录，可以将此设备尚未领取的合格积分存入课程积分账户。" : "You are signed in and can secure eligible points earned on this device.") : (zh ? "访客积分只保存在此设备。登录或免费注册后返回本页，即可领取；不会自动订阅或启用免费月。" : "Guest points stay on this device. Sign in or create a free account, then return to claim. This never starts a subscription or free month.")}</p>{data?.signedIn ? <button disabled={busy || !(data.provisionalPoints || 0)} onClick={() => void submit("claim")}>{zh ? "领取课程积分" : "Claim course points"}</button> : <Link href={`/${lang}/auth/sign-up?returnTo=${encodeURIComponent(`/${lang}/smartcards/${token}`)}`}>{zh ? "免费注册并保留积分" : "Create a free account to keep points"} →</Link>}</section>
    {message ? <p className="public-card-message" role="status">{message}</p> : null}
    <style>{`.public-smartcards{min-height:100vh;padding:clamp(24px,5vw,72px);display:grid;gap:24px;background:radial-gradient(circle at top right,#d9fff0,transparent 34%),#f6f2e8;color:#152d27}.public-smartcards>*{width:min(980px,100%);margin-inline:auto}.public-smartcards-hero>a{color:#087d62;font-weight:850}.public-smartcards-hero>p:first-of-type{margin-top:46px;color:#087d62;font-size:12px;font-weight:950;letter-spacing:.1em}.public-smartcards-hero h1{max-width:900px;margin:8px 0 15px;font-size:clamp(42px,7vw,82px);line-height:1}.public-smartcards-hero>p:last-of-type{max-width:72ch;color:#536760;font-size:18px;line-height:1.65}.public-smartcards-hero>div{margin-top:20px;display:flex;align-items:baseline;gap:10px}.public-smartcards-hero strong{font-size:38px;color:#087d62}.public-card-stage,.public-card-quiz,.public-card-claim{padding:clamp(20px,4vw,38px);border:1px solid #b7d2c7;border-radius:24px;background:#fff}.public-card{min-height:310px;padding:30px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;border-radius:21px;background:linear-gradient(145deg,#123f35,#17604f);color:#fff;text-align:center;cursor:pointer}.public-card strong{font-size:clamp(33px,6vw,63px)}.public-card span{font-size:20px;color:#c8ece0}.public-card b{margin-top:22px;color:#8ce8ca}.public-card-stage nav{margin-top:13px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.public-card-stage button,.public-card-quiz>button,.public-card-claim button,.public-card-claim a{min-height:48px;padding:11px 17px;border:0;border-radius:999px;background:#087d62;color:#fff;font-weight:850;text-align:center;text-decoration:none}.public-card-stage button:disabled,.public-card-quiz>button:disabled,.public-card-claim button:disabled{opacity:.4}.public-card-quiz>div{display:grid;gap:10px}.public-card-quiz fieldset{min-width:0;margin:0;padding:15px;border:1px solid #cedbd5;border-radius:14px}.public-card-quiz legend{padding:0 5px;font-weight:850}.public-card-quiz fieldset>button{margin:8px 0;padding:8px 12px;border:0;border-radius:999px;background:#e0f4eb;color:#076b55;font-weight:800}.public-card-quiz fieldset>div{display:grid;grid-template-columns:1fr 1fr;gap:7px}.public-card-quiz label{padding:10px;display:flex;align-items:center;gap:8px;border-radius:10px;background:#f2f7f4;font-weight:750}.public-card-quiz input:not([type=radio]){width:100%;padding:11px;border:1px solid #a8bbb3;border-radius:8px;font:16px inherit}.public-card-quiz>button{width:100%;margin-top:16px}.public-card-claim{background:#fff9e9}.public-card-claim a{display:inline-flex;align-items:center}.public-card-message{padding:14px;border-radius:12px;background:#123f35;color:#fff;font-weight:800}@media(max-width:650px){.public-smartcards{padding-inline:16px}.public-card-quiz fieldset>div{grid-template-columns:1fr}.public-card-stage nav{grid-template-columns:1fr}.public-smartcards-hero h1{font-size:44px}}`}</style>
  </main>;
}
