"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Day={date:string;topScore:number;winnerName:string;players:number;rewardPoints:number};
type Rank={rank:number;name:string;score:number};
type Celebration={date:string;winnerName:string;score:number;rewardPoints:number};

export function SmartCardChallengeCalendar({lang,targetLanguage}:{lang:"en"|"zh";targetLanguage:string}){
  const zh=lang==="zh";const today=new Date().toISOString().slice(0,10);
  const [month,setMonth]=useState(today.slice(0,7));const [days,setDays]=useState<Day[]>([]);const [selected,setSelected]=useState("");const [ranking,setRanking]=useState<Rank[]>([]);const [celebrations,setCelebrations]=useState<Celebration[]>([]);const [error,setError]=useState("");
  useEffect(()=>{void fetch(`/api/smartcards/leaderboard?month=${month}&language=${encodeURIComponent(targetLanguage)}`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error();setDays(body.days||[]);setCelebrations(body.celebrated||[]);setSelected("");setRanking([]);setError("");}).catch(()=>setError(zh?"暂时无法读取排行榜。":"Leaderboard is temporarily unavailable."));},[month,targetLanguage,zh]);
  const cells=useMemo(()=>{const [year,number]=month.split("-").map(Number);const first=new Date(year,number-1,1);const count=new Date(year,number,0).getDate();return [...Array(first.getDay()).fill(null),...Array.from({length:count},(_,index)=>`${month}-${String(index+1).padStart(2,"0")}`)];},[month]);
  function move(delta:number){const [year,number]=month.split("-").map(Number);const next=new Date(year,number-1+delta,1);setMonth(`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,"0")}`);}
  async function show(date:string){setSelected(date);const response=await fetch(`/api/smartcards/leaderboard?month=${month}&date=${date}&language=${encodeURIComponent(targetLanguage)}`);const body=await response.json().catch(()=>({}));setRanking(response.ok?body.ranking||[]:[]);}
  return <section className="challenge-calendar">
    {celebrations.map(item=><aside className="winner-celebration" key={item.date} role="status"><span>🏆</span><div><small>{item.date} · {zh?"冠军已结算":"WINNER SETTLED"}</small><h2>{zh?`恭喜 ${item.winnerName}！`:`Congratulations, ${item.winnerName}!`}</h2><p>{zh?`冠军成绩 ${item.score}，已奖励 ${item.rewardPoints} 课程积分。`:`Winning score ${item.score}; ${item.rewardPoints} course points awarded.`}</p></div></aside>)}
    <header><button onClick={()=>move(-1)} aria-label={zh?"上个月":"Previous month"}>←</button><h2>{month}</h2><button onClick={()=>move(1)} disabled={month>=today.slice(0,7)} aria-label={zh?"下个月":"Next month"}>→</button></header>
    <div className="week">{(zh?["日","一","二","三","四","五","六"]:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]).map(day=><b key={day}>{day}</b>)}</div>
    <div className="days">{cells.map((date,index)=>date?(()=>{const result=days.find(item=>item.date===date);const future=date>today;const current=date===today;return current?<Link key={date} className="today" href={`/${lang}/smartcards/starter-${targetLanguage}?mode=challenge&language=${targetLanguage}`}><strong>{Number(date.slice(-2))}</strong><span>{zh?"今日挑战":"Play today"}</span></Link>:<button key={date} className={selected===date?"selected":""} disabled={future||!result} onClick={()=>void show(date)}><strong>{Number(date.slice(-2))}</strong>{result?<><span>★ {result.topScore}</span><small>{result.winnerName}{result.rewardPoints?` · +${result.rewardPoints}`:""}</small></>:<small>{future?(zh?"即将开放":"Coming soon"):(zh?"暂无成绩":"No result")}</small>}</button>})():<i key={`blank-${index}`}/>)}</div>
    {selected?<aside><h2>{selected} · {zh?"排行榜":"Ranking"}</h2>{ranking.length?<ol>{ranking.map(item=><li key={`${item.rank}-${item.name}`}><b>{item.rank}</b><span>{item.name}</span><strong>{item.score}</strong></li>)}</ol>:<p>{zh?"这一天还没有可显示的成绩。":"No published results for this day."}</p>}</aside>:null}{error?<p role="alert">{error}</p>:null}
    <style>{`.challenge-calendar{width:min(1080px,calc(100% - 32px));margin:0 auto 100px;padding:clamp(18px,4vw,38px);border:1px solid #c9d8d2;border-radius:28px;background:#fff}.winner-celebration{margin:0 0 28px;padding:22px;display:flex;gap:18px;align-items:center;border-radius:20px;background:linear-gradient(135deg,#fff0a9,#fff8dc);box-shadow:0 12px 35px #b9852228;animation:winner-in .7s ease both}.winner-celebration>span{font-size:54px}.winner-celebration small{color:#825b00;font-weight:950;letter-spacing:.08em}.winner-celebration h2{margin:4px 0}.winner-celebration p{margin:0;color:#6f5b27}.challenge-calendar>header{display:flex;align-items:center;justify-content:center;gap:25px}.challenge-calendar>header h2{min-width:150px;text-align:center}.challenge-calendar>header button{width:44px;height:44px;border:1px solid #c6d7d0;border-radius:50%;background:#f3f8f6}.week,.days{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.week{margin:25px 0 8px;color:#6b7c75;text-align:center;font-size:12px}.days>*{min-width:0;min-height:112px;padding:10px;display:flex;flex-direction:column;align-items:flex-start;gap:8px;border:1px solid #dce6e2;border-radius:14px;background:#f8fbf9;color:#18322a;text-decoration:none}.days strong{font-size:20px}.days span{color:#087d62;font-weight:900}.days small{max-width:100%;overflow:hidden;color:#687b73;text-overflow:ellipsis;white-space:nowrap}.days button:disabled{opacity:.45}.days .today{border-color:#087d62;background:#087d62;color:#fff}.days .today span{color:#bffff0}.days .selected{box-shadow:0 0 0 3px #087d6233}.challenge-calendar aside:not(.winner-celebration){margin-top:28px;padding:24px;border-radius:20px;background:#f0f8f4}.challenge-calendar ol{padding:0;list-style:none}.challenge-calendar li{padding:12px;display:grid;grid-template-columns:42px 1fr auto;align-items:center;border-bottom:1px solid #d6e4de}.challenge-calendar li>b{width:31px;height:31px;display:grid;place-items:center;border-radius:50%;background:#123f35;color:#fff}.challenge-calendar li>strong{color:#087d62;font-size:22px}@keyframes winner-in{from{opacity:0;transform:scale(.92) rotate(-1deg)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.winner-celebration{animation:none}}@media(max-width:650px){.days>*{min-height:76px;padding:7px}.days small{display:none}.days span{font-size:10px}.week,.days{gap:3px}.winner-celebration{align-items:flex-start}.winner-celebration>span{font-size:38px}}`}</style>
  </section>;
}
