"use client";
import { useEffect, useState } from "react";

type Row = { rank: number; name: string; score: number; durationMinutes: number; roundCount: number; localDate: string };
export function SprintLeaderboard({ lang, language }: { lang: "zh"|"en"; language: string }) {
  const zh=lang==="zh"; const [range,setRange]=useState<"today"|"week">("week"); const [rows,setRows]=useState<Row[]>([]); const [myBest,setMyBest]=useState<{rank:number;score:number}|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{fetch(`/api/sprints/leaderboard?language=${encodeURIComponent(language)}&range=${range}`,{cache:"no-store"}).then(r=>r.json()).then(data=>{setRows(data.rankings||[]);setMyBest(data.myBest||null);}).finally(()=>setLoading(false));},[language,range]);
  function chooseRange(value:"today"|"week"){if(value===range)return;setLoading(true);setRange(value)}
  return <section className="sprint-rank"><header><div><p>TODAY’S SPRINT RANKINGS</p><h2>{zh?"今日速成排行榜":"Today’s Sprint Rankings"}</h2><span>{zh?"完整完成后才计分；同分时较多回合优先，再按完成时间排序。":"Only completed sprints rank. Ties favor more rounds, then earlier completion."}</span></div>{myBest?<aside><small>{zh?"我的最佳":"My best"}</small><strong>#{myBest.rank}</strong><b>{myBest.score} / 100</b></aside>:null}</header><nav><button className={range==="today"?"active":""} onClick={()=>chooseRange("today")}>{zh?"今日":"Today"}</button><button className={range==="week"?"active":""} onClick={()=>chooseRange("week")}>{zh?"本周":"This week"}</button></nav>{loading?<p>{zh?"正在读取排行榜…":"Loading rankings…"}</p>:rows.length?<ol>{rows.map(row=><li key={`${row.rank}:${row.name}:${row.localDate}`}><b>{row.rank}</b><strong>{row.name}</strong><span>{row.durationMinutes} {zh?"分钟":"min"} · {row.roundCount} {zh?"回合":"rounds"}</span><em>{row.score}</em></li>)}</ol>:<p>{zh?"还没有完成记录。完成今日速成后成为第一名。":"No completed scores yet. Finish Today’s Sprint to take first place."}</p>}<style>{`.sprint-rank{width:min(1040px,calc(100% - 32px));margin:0 auto 100px;padding:clamp(22px,4vw,42px);border:1px solid #bfd1c9;border-radius:28px;background:#fff}.sprint-rank>header{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px}.sprint-rank header p{color:#087d62;font-size:12px;font-weight:950;letter-spacing:.12em}.sprint-rank h2{margin:8px 0;font-size:clamp(34px,5vw,58px)}.sprint-rank header span{color:#60716b}.sprint-rank aside{min-width:150px;padding:18px;border-radius:18px;background:#123f35;color:#fff;display:grid}.sprint-rank aside strong{font-size:38px}.sprint-rank nav{display:flex;gap:8px;margin:28px 0 15px}.sprint-rank nav button{padding:10px 18px;border:1px solid #bfd1c9;border-radius:999px;background:#fff}.sprint-rank nav .active{background:#123f35;color:#fff}.sprint-rank ol{margin:0;padding:0;list-style:none}.sprint-rank li{min-width:0;padding:15px 10px;display:grid;grid-template-columns:42px minmax(0,1fr) auto 64px;gap:12px;align-items:center;border-top:1px solid #e1e8e4}.sprint-rank li>b{font-size:20px}.sprint-rank li>span{color:#687a74}.sprint-rank li>em{text-align:right;color:#087d62;font-size:25px;font-style:normal;font-weight:950}@media(max-width:620px){.sprint-rank>header{grid-template-columns:1fr}.sprint-rank aside{grid-template-columns:1fr auto;align-items:center}.sprint-rank aside strong{grid-row:1/3;grid-column:2}.sprint-rank li{grid-template-columns:34px minmax(0,1fr) 54px}.sprint-rank li>span{grid-column:2;font-size:13px}.sprint-rank li>em{grid-column:3;grid-row:1/3}}`}</style></section>;
}
