import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteFooter } from "../../../components/SiteFooter";
import { SiteHeader } from "../../../components/SiteHeader";
import { SmartCardDirectoryGrid } from "../../../components/SmartCardDirectoryGrid";

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> {
  const { lang } = await params;
  return { title: lang === "zh" ? "SmartCard 21 天学习" : "SmartCard 21-day learning" };
}

export default async function SmartCardsPage({ params, searchParams }: { params: Promise<{ lang: string }>; searchParams: Promise<{ mode?: string }> }) {
  const { lang } = await params;
  if (!["en","zh","es","ja","ko","fr","de","ru","it","pt","ar","hi"].includes(lang)) notFound();
  const zh = lang === "zh", challenge = (await searchParams).mode === "challenge";
  return <main className="smartcard-directory"><SiteHeader lang={lang as any}/>
    <section className="smartcard-directory-hero"><p>{challenge ? "DAILY SMART CARD CHALLENGE" : "SMART CARD PRACTICE"}</p><h1>{challenge ? (zh ? "选择今天要挑战的语言。" : "Choose today's challenge language.") : (zh ? "从 21 天渐进词汇开始练习。" : "Practice a progressive 21-day vocabulary path.")}</h1><p>{zh ? "每级都有 500 道高频题库。每张卡只显示一个目标词：看图选择、听正常或真正慢速发音，再按需开口跟读。" : "Every level has a 500-item frequent-word pool. See one target word, choose by picture, hear normal or truly slow speech, and optionally repeat aloud."}</p><div><strong>500</strong><span>{zh ? "每级题库" : "items per level"}</span><strong>20</strong><span>{zh ? "每天" : "per day"}</span><strong>21</strong><span>{zh ? "学习日" : "learning days"}</span></div></section>
    <SmartCardDirectoryGrid lang={zh?"zh":"en"} challenge={challenge}/>
    <section className="smartcard-directory-policy"><h2>{zh ? "成绩、学习日与奖励都由服务器记录。" : "Scores, learning days, and rewards are recorded by the server."}</h2><p>{zh ? "访客可直接练习并用独立 Cookie 暂存本功能进度；登录后会按语言和级别保存 21 天路径。挑战每天首次打开时从 500 题库固化同一套 20 题，所有学习者当天一致。" : "Guests can practice with feature-specific cookie progress. Signed-in members keep a 21-day path by language and level. The first challenge open each day fixes the same 20 questions from the 500-item pool for everyone."}</p></section>
    <SiteFooter lang={lang as any}/><style>{`.smartcard-directory{min-height:100vh;background:#f7f3ea;color:var(--ink)}.smartcard-directory-hero,.smartcard-language-grid,.smartcard-directory-policy{width:min(1280px,calc(100% - 40px));margin-inline:auto}.smartcard-directory-hero{padding:110px 0 70px}.smartcard-directory-hero>p:first-child{color:#087d62;font-size:12px;font-weight:950;letter-spacing:.11em}.smartcard-directory-hero h1{max-width:1100px;margin:12px 0 22px;font:600 clamp(46px,7vw,90px)/.98 "Iowan Old Style","Noto Serif SC",serif}.smartcard-directory-hero>p:nth-of-type(2){max-width:78ch;color:#586b64;font-size:18px;line-height:1.7}.smartcard-directory-hero>div{margin-top:30px;display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}.smartcard-directory-hero strong{margin-left:22px;color:#087d62;font-size:33px}.smartcard-directory-hero strong:first-child{margin-left:0}.smartcard-language-grid{padding-bottom:80px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.smartcard-language-grid article>a{padding:27px;border:1px solid #b9d2c8;border-radius:19px;background:#fff;color:inherit;text-decoration:none;transition:transform .2s,box-shadow .2s}.smartcard-language-grid article>a:hover{transform:translateY(-3px);box-shadow:0 14px 35px rgba(20,55,45,.12)}.smartcard-language-grid span{color:#087d62;font-size:11px;font-weight:950;letter-spacing:.1em}.smartcard-language-grid h2{margin:15px 0 8px;font-size:29px}.smartcard-language-grid p{color:#60716b}.smartcard-language-grid b{display:block;margin-top:24px;color:#087d62}.smartcard-directory-policy{margin-bottom:100px;padding:clamp(24px,5vw,55px);border-radius:25px;background:#123f35;color:#fff}.smartcard-directory-policy h2{font-size:clamp(30px,4vw,50px)}.smartcard-directory-policy p{max-width:76ch;color:#c7ded6;line-height:1.7}@media(max-width:850px){.smartcard-language-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.smartcard-directory-hero,.smartcard-language-grid,.smartcard-directory-policy{width:min(100% - 28px,1280px)}.smartcard-language-grid{grid-template-columns:1fr}.smartcard-directory-hero{padding-top:70px}}`}</style>
  </main>;
}
