import { getDatabase, type SessionUser } from "@/lib/auth";
import { isAdminUser } from "@/lib/admin-access";
import type { ClassRoom } from "@/lib/live-classrooms";
const TRIAL_SECONDS=7*24*60*60;
export async function isClassCoHost(roomId:string,user:SessionUser|null){if(!user)return false;return Boolean(await getDatabase().prepare("SELECT 1 FROM live_class_cohosts WHERE room_id=? AND user_id=? LIMIT 1").bind(roomId,user.id).first());}
export async function canManageClass(room:Pick<ClassRoom,"id"|"hostUserId">,user:SessionUser|null){return Boolean(user&&user.emailVerified===1&&user.identityCheckedAt>Math.floor(Date.now()/1000)-5*60&&(user.id===room.hostUserId||await isAdminUser(user)||await isClassCoHost(room.id,user)));}
async function registered(emailValue:string){const email=emailValue.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error("INVALID_EMAIL");const target=await getDatabase().prepare("SELECT id,email,display_name AS displayName,email_verified AS emailVerified,clerk_identity_checked_at AS identityCheckedAt FROM users WHERE lower(email)=lower(?) LIMIT 1").bind(email).first<{id:string;email:string;displayName:string;emailVerified:number;identityCheckedAt:number}>();if(!target)throw new Error("MEMBER_NOT_FOUND");if(!target.emailVerified||target.identityCheckedAt<=Math.floor(Date.now()/1000)-5*60)throw new Error("VERIFIED_MEMBER_REQUIRED");return target;}
export async function classCoHosts(roomId:string){return (await getDatabase().prepare("SELECT u.id,u.email,u.display_name AS displayName FROM live_class_cohosts c JOIN users u ON u.id=c.user_id WHERE c.room_id=? ORDER BY c.created_at").bind(roomId).run<{id:string;email:string;displayName:string}>()).results||[];}
export async function addClassCoHost(room:Pick<ClassRoom,"id"|"hostUserId">,actor:SessionUser,email:string){const target=await registered(email);if(target.id===room.hostUserId)throw new Error("ALREADY_HOST");await getDatabase().prepare("INSERT OR IGNORE INTO live_class_cohosts(room_id,user_id,added_by_user_id,created_at) VALUES(?,?,?,?)").bind(room.id,target.id,actor.id,Math.floor(Date.now()/1000)).run();}
export async function removeClassCoHost(roomId:string,userId:string){await getDatabase().prepare("DELETE FROM live_class_cohosts WHERE room_id=? AND user_id=?").bind(roomId,userId).run();}
export async function classSubscribers(roomId:string){return (await getDatabase().prepare("SELECT u.id,u.email,u.display_name AS displayName FROM live_class_subscriptions s JOIN users u ON u.id=s.user_id WHERE s.room_id=? AND s.status='active' ORDER BY s.updated_at DESC").bind(roomId).run<{id:string;email:string;displayName:string}>()).results||[];}
export async function addClassSubscriber(roomId:string,actor:SessionUser,email:string){const target=await registered(email),now=Math.floor(Date.now()/1000);await getDatabase().prepare("INSERT INTO live_class_subscriptions(room_id,user_id,status,added_by_user_id,created_at,updated_at) VALUES(?,?,'active',?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET status='active',added_by_user_id=excluded.added_by_user_id,updated_at=excluded.updated_at").bind(roomId,target.id,actor.id,now,now).run();}
export async function removeClassSubscriber(roomId:string,userId:string){await getDatabase().prepare("UPDATE live_class_subscriptions SET status='cancelled',updated_at=? WHERE room_id=? AND user_id=?").bind(Math.floor(Date.now()/1000),roomId,userId).run();}
export async function paidClassAccess(room:Pick<ClassRoom,"id"|"classType"|"tuitionCents">,user:SessionUser|null,startTrial=false){if(room.classType!=="trial"||room.tuitionCents<=0)return{allowed:true as const,status:"free" as const};if(!user)return{allowed:false as const,reason:"SIGN_IN_REQUIRED" as const};const db=getDatabase(),now=Math.floor(Date.now()/1000),current=await db.prepare("SELECT status,trial_ends_at AS trialEndsAt FROM live_class_subscriptions WHERE room_id=? AND user_id=? LIMIT 1").bind(room.id,user.id).first<{status:string;trialEndsAt:number|null}>();if(current?.status==="active")return{allowed:true as const,status:"active" as const};if(current?.status==="trial"&&Number(current.trialEndsAt||0)>now)return{allowed:true as const,status:"trial" as const};if(current){await db.prepare("UPDATE live_class_subscriptions SET status='expired',updated_at=? WHERE room_id=? AND user_id=?").bind(now,room.id,user.id).run();return{allowed:false as const,reason:"PAYMENT_REQUIRED" as const};}if(!startTrial)return{allowed:false as const,reason:"TRIAL_AVAILABLE" as const};await db.prepare("INSERT INTO live_class_subscriptions(room_id,user_id,status,trial_started_at,trial_ends_at,created_at,updated_at) VALUES(?,?,'trial',?,?,?,?)").bind(room.id,user.id,now,now+TRIAL_SECONDS,now,now).run();return{allowed:true as const,status:"trial" as const};}
