import { getDatabase, type SessionUser } from "@/lib/auth";
import { isAdminUser } from "@/lib/admin-access";
import type { ClassRoom } from "@/lib/live-classrooms";
import {
  BIND_VERIFIED_CLASS_COHOSTS_SQL,
  BIND_VERIFIED_CLASS_INVITES_SQL,
  BIND_VERIFIED_CLASS_SUBSCRIPTIONS_SQL,
  BIND_VERIFIED_STAGE_SPEAKERS_SQL,
  DELETE_ALREADY_BOUND_CLASS_INVITES_SQL,
  DELETE_ALREADY_BOUND_STAGE_SPEAKERS_SQL,
  DELETE_DUPLICATE_CLASS_INVITES_SQL,
  DELETE_DUPLICATE_STAGE_SPEAKERS_SQL,
  VERIFIED_REGISTERED_CLASS_USER_SQL,
} from "@/lib/class-grant-binding";

export const CLASS_TRIAL_SECONDS=7*24*60*60;

export async function bindVerifiedClassCoHosts(user:SessionUser|null){if(!user?.emailVerified)return;await getDatabase().prepare(BIND_VERIFIED_CLASS_COHOSTS_SQL).bind(Math.floor(Date.now()/1000),user.id,user.email).run();}
export async function bindVerifiedClassInvites(user:SessionUser|null){if(!user?.emailVerified)return;const db=getDatabase();await db.prepare(DELETE_ALREADY_BOUND_CLASS_INVITES_SQL).bind(user.email,user.id).run();await db.prepare(DELETE_DUPLICATE_CLASS_INVITES_SQL).bind(user.email,user.email).run();await db.prepare(BIND_VERIFIED_CLASS_INVITES_SQL).bind(user.id,user.email,user.id).run();}
export async function bindVerifiedClassSubscriptions(user:SessionUser|null){if(!user?.emailVerified)return;await getDatabase().prepare(BIND_VERIFIED_CLASS_SUBSCRIPTIONS_SQL).bind(Math.floor(Date.now()/1000),user.id,user.email).run();}
export async function bindVerifiedStageSpeakers(user:SessionUser|null){if(!user?.emailVerified)return;const db=getDatabase();await db.prepare(DELETE_ALREADY_BOUND_STAGE_SPEAKERS_SQL).bind(user.email,user.id).run();await db.prepare(DELETE_DUPLICATE_STAGE_SPEAKERS_SQL).bind(user.email,user.email).run();await db.prepare(BIND_VERIFIED_STAGE_SPEAKERS_SQL).bind(user.id,user.email,user.id).run();}

export async function isClassCoHost(roomId:string,user:SessionUser|null){if(!user)return false;await bindVerifiedClassCoHosts(user);return Boolean(await getDatabase().prepare("SELECT 1 FROM live_class_cohosts WHERE room_id=? AND user_id=? AND identity_bound_at>0 LIMIT 1").bind(roomId,user.id).first());}
export async function canManageClass(room:Pick<ClassRoom,"id"|"hostUserId">,user:SessionUser|null){return Boolean(user&&user.emailVerified===1&&user.identityCheckedAt>Math.floor(Date.now()/1000)-5*60&&(user.id===room.hostUserId||await isAdminUser(user)||await isClassCoHost(room.id,user)));}
export async function verifiedRegisteredUser(emailValue:string){const email=emailValue.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error("INVALID_EMAIL");const target=await getDatabase().prepare(VERIFIED_REGISTERED_CLASS_USER_SQL).bind(email,Math.floor(Date.now()/1000)-5*60).first<{id:string;email:string;displayName:string}>();if(!target)throw new Error("MEMBER_NOT_FOUND");return target;}
export async function classCoHosts(roomId:string){return (await getDatabase().prepare("SELECT u.id,u.email,u.display_name AS displayName FROM live_class_cohosts c JOIN users u ON u.id=c.user_id WHERE c.room_id=? AND c.identity_bound_at>0 ORDER BY c.created_at").bind(roomId).run<{id:string;email:string;displayName:string}>()).results||[];}
export async function addClassCoHost(room:Pick<ClassRoom,"id"|"hostUserId">,actor:SessionUser,email:string){const target=await verifiedRegisteredUser(email);if(target.id===room.hostUserId)throw new Error("ALREADY_HOST");const now=Math.floor(Date.now()/1000);await getDatabase().prepare(`INSERT INTO live_class_cohosts(room_id,user_id,added_by_user_id,created_at,granted_email,identity_bound_at) VALUES(?,?,?,?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET added_by_user_id=excluded.added_by_user_id,granted_email=excluded.granted_email,identity_bound_at=excluded.identity_bound_at`).bind(room.id,target.id,actor.id,now,target.email,now).run();}
export async function removeClassCoHost(roomId:string,userId:string){await getDatabase().prepare("DELETE FROM live_class_cohosts WHERE room_id=? AND user_id=?").bind(roomId,userId).run();}
export async function classSubscribers(roomId:string){return (await getDatabase().prepare("SELECT u.id,u.email,u.display_name AS displayName FROM live_class_subscriptions s JOIN users u ON u.id=s.user_id WHERE s.room_id=? AND s.status='active' AND s.identity_bound_at>0 ORDER BY s.updated_at DESC").bind(roomId).run<{id:string;email:string;displayName:string}>()).results||[];}
export async function addClassSubscriber(roomId:string,actor:SessionUser,email:string){const target=await verifiedRegisteredUser(email),now=Math.floor(Date.now()/1000);await getDatabase().prepare("INSERT INTO live_class_subscriptions(room_id,user_id,email,status,added_by_user_id,created_at,updated_at,identity_bound_at) VALUES(?,?,?,'active',?,?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET email=excluded.email,status='active',added_by_user_id=excluded.added_by_user_id,updated_at=excluded.updated_at,identity_bound_at=excluded.identity_bound_at").bind(roomId,target.id,target.email,actor.id,now,now,now).run();}
export async function removeClassSubscriber(roomId:string,userId:string){await getDatabase().prepare("UPDATE live_class_subscriptions SET status='cancelled',updated_at=? WHERE room_id=? AND user_id=?").bind(Math.floor(Date.now()/1000),roomId,userId).run();}
export async function paidClassAccess(room:Pick<ClassRoom,"id"|"classType"|"tuitionCents">,user:SessionUser|null,startTrial=false){if(room.classType!=="trial"||room.tuitionCents<=0)return{allowed:true as const,status:"free" as const};if(!user)return{allowed:false as const,reason:"SIGN_IN_REQUIRED" as const};const db=getDatabase(),now=Math.floor(Date.now()/1000);await bindVerifiedClassSubscriptions(user);const current=await db.prepare("SELECT status,trial_ends_at AS trialEndsAt,identity_bound_at AS identityBoundAt FROM live_class_subscriptions WHERE room_id=? AND user_id=? LIMIT 1").bind(room.id,user.id).first<{status:string;trialEndsAt:number|null;identityBoundAt:number}>();if(current?.status==="active")return current.identityBoundAt>0?{allowed:true as const,status:"active" as const}:{allowed:false as const,reason:"VERIFIED_EMAIL_REQUIRED" as const};if(current?.status==="trial"&&Number(current.trialEndsAt||0)>now)return{allowed:true as const,status:"trial" as const};if(current){await db.prepare("UPDATE live_class_subscriptions SET status='expired',updated_at=? WHERE room_id=? AND user_id=?").bind(now,room.id,user.id).run();return{allowed:false as const,reason:"PAYMENT_REQUIRED" as const};}if(!startTrial)return{allowed:false as const,reason:"TRIAL_AVAILABLE" as const};await db.prepare("INSERT INTO live_class_subscriptions(room_id,user_id,email,status,trial_started_at,trial_ends_at,created_at,updated_at,identity_bound_at) VALUES(?,?,?,'trial',?,?,?,?,0)").bind(room.id,user.id,user.email,now,now+CLASS_TRIAL_SECONDS,now,now).run();return{allowed:true as const,status:"trial" as const};}
