import type { InterfaceLanguage } from "./interface-locale";

type Copy={menu:string;supervisor:string;enter:string;save:string;checking:string;saved:string;fixed:string;optional:string;invalid:string;shareTitle:string;shareText:string;shareButton:string;copied:string;shareBlurb:string;title:string;intro:string;language:string;allLanguages:string;subscriptions:string;student:string;course:string;languageLevel:string;expires:string;reward:string;eligible:string;empty:string;loadError:string};
const en:Copy={menu:"My Students",supervisor:"Supervisor",enter:"Enter VIP RefID",save:"Save",checking:"Checking…",saved:"Supervisor saved. This course relationship is now fixed.",fixed:"Assigned once and cannot be changed.",optional:"Optional. The RefID must belong to a VIP member or administrator.",invalid:"Invalid Supervisor RefID",shareTitle:"Share this course",shareText:"Learn this SmartLingo course with me.",shareButton:"Copy or share link",copied:"Copied",shareBlurb:"Your RefID is securely carried to checkout. A completed subscription becomes one of your students and creates a separate VIP reward-eligibility record.",title:"My Students",intro:"Course subscriptions assigned to your Supervisor RefID are listed here.",language:"Learning language",allLanguages:"All languages",subscriptions:"subscriptions",student:"Student",course:"Course",languageLevel:"Language / level",expires:"Expires",reward:"Reward",eligible:"Eligible",empty:"No course subscriptions match this language yet.",loadError:"Unable to load students right now."};
export const courseSupervisorCopies:Record<InterfaceLanguage,Copy>={
 en,
 zh:{menu:"我的学生",supervisor:"Supervisor",enter:"输入 VIP RefID",save:"保存",checking:"验证中…",saved:"Supervisor 已保存；该课程关系现已固定。",fixed:"只绑定一次，之后不可更改。",optional:"可选；RefID 必须属于 VIP 会员或管理员。",invalid:"Supervisor RefID 无效",shareTitle:"分享这门课程",shareText:"和我一起学习这门 SmartLingo 课程。",shareButton:"复制或分享链接",copied:"已复制",shareBlurb:"您的 RefID 会安全传递至结账；完成订阅后，学员会归入“我的学生”，并建立独立的 VIP 奖励资格记录。",title:"我的学生",intro:"这里列出归属于您 Supervisor RefID 的课程订阅。",language:"学习语言",allLanguages:"全部语言",subscriptions:"项订阅",student:"学生",course:"课程",languageLevel:"语言 / 等级",expires:"到期时间",reward:"奖励",eligible:"符合资格",empty:"目前没有符合该语言的课程订阅。",loadError:"暂时无法读取学生资料。"},
 ja:{...en,menu:"受講生",supervisor:"スーパーバイザー",enter:"VIP RefIDを入力",save:"保存",checking:"確認中…",saved:"スーパーバイザーを保存しました。この関係は固定されました。",fixed:"一度割り当てると変更できません。",optional:"任意。VIP会員または管理者のRefIDが必要です。",invalid:"無効なスーパーバイザーRefID",shareTitle:"このコースを共有",shareText:"SmartLingoのこのコースを一緒に学びましょう。",shareButton:"リンクをコピーまたは共有",copied:"コピー済み",title:"受講生",intro:"あなたのスーパーバイザーRefIDに割り当てられたコース購読です。",language:"学習言語",allLanguages:"すべての言語",subscriptions:"件の購読",student:"受講生",course:"コース",languageLevel:"言語 / レベル",expires:"有効期限",reward:"報酬",eligible:"対象",empty:"この言語の購読はまだありません。",loadError:"受講生を読み込めません。"},
 ko:{...en,menu:"내 학생",supervisor:"감독자",enter:"VIP RefID 입력",save:"저장",checking:"확인 중…",saved:"감독자가 저장되어 이 관계가 고정되었습니다.",fixed:"한 번 지정하면 변경할 수 없습니다.",optional:"선택 사항이며 VIP 회원 또는 관리자의 RefID여야 합니다.",invalid:"유효하지 않은 감독자 RefID",shareTitle:"이 과정 공유",shareButton:"링크 복사 또는 공유",copied:"복사됨",title:"내 학생",intro:"감독자 RefID에 지정된 과정 구독입니다.",language:"학습 언어",allLanguages:"모든 언어",subscriptions:"개 구독",student:"학생",course:"과정",languageLevel:"언어 / 수준",expires:"만료",reward:"보상",eligible:"대상",empty:"이 언어의 구독이 아직 없습니다.",loadError:"학생을 불러올 수 없습니다."},
 es:{...en,menu:"Mis estudiantes",supervisor:"Supervisor",enter:"Introduce RefID VIP",save:"Guardar",checking:"Comprobando…",saved:"Supervisor guardado. Esta relación queda fija.",fixed:"Se asigna una sola vez y no puede cambiarse.",optional:"Opcional. El RefID debe pertenecer a un miembro VIP o administrador.",invalid:"RefID de supervisor no válido",shareTitle:"Compartir este curso",shareButton:"Copiar o compartir enlace",copied:"Copiado",title:"Mis estudiantes",intro:"Aquí aparecen las suscripciones asignadas a tu RefID de supervisor.",language:"Idioma de aprendizaje",allLanguages:"Todos los idiomas",subscriptions:"suscripciones",student:"Estudiante",course:"Curso",languageLevel:"Idioma / nivel",expires:"Vence",reward:"Recompensa",eligible:"Elegible",empty:"Aún no hay suscripciones para este idioma.",loadError:"No se pueden cargar los estudiantes."},
 fr:{...en,menu:"Mes élèves",supervisor:"Superviseur",enter:"Saisir le RefID VIP",save:"Enregistrer",checking:"Vérification…",saved:"Superviseur enregistré. Cette relation est désormais fixe.",fixed:"Attribué une fois et non modifiable.",optional:"Facultatif. Le RefID doit appartenir à un membre VIP ou administrateur.",invalid:"RefID de superviseur non valide",shareTitle:"Partager ce cours",shareButton:"Copier ou partager le lien",copied:"Copié",title:"Mes élèves",intro:"Abonnements attribués à votre RefID de superviseur.",language:"Langue apprise",allLanguages:"Toutes les langues",subscriptions:"abonnements",student:"Élève",course:"Cours",languageLevel:"Langue / niveau",expires:"Expire",reward:"Récompense",eligible:"Éligible",empty:"Aucun abonnement pour cette langue.",loadError:"Impossible de charger les élèves."},
 de:{...en,menu:"Meine Lernenden",supervisor:"Betreuer",enter:"VIP-RefID eingeben",save:"Speichern",checking:"Prüfung…",saved:"Betreuer gespeichert. Diese Zuordnung ist jetzt fest.",fixed:"Einmal zugewiesen und nicht änderbar.",optional:"Optional. Die RefID muss einem VIP-Mitglied oder Administrator gehören.",invalid:"Ungültige Betreuer-RefID",shareTitle:"Diesen Kurs teilen",shareButton:"Link kopieren oder teilen",copied:"Kopiert",title:"Meine Lernenden",intro:"Hier stehen die Ihrer Betreuer-RefID zugeordneten Kursabos.",language:"Lernsprache",allLanguages:"Alle Sprachen",subscriptions:"Abonnements",student:"Lernende",course:"Kurs",languageLevel:"Sprache / Stufe",expires:"Läuft ab",reward:"Prämie",eligible:"Berechtigt",empty:"Noch keine Abos für diese Sprache.",loadError:"Lernende können nicht geladen werden."},
 ru:{...en,menu:"Мои ученики",supervisor:"Куратор",enter:"Введите VIP RefID",save:"Сохранить",checking:"Проверка…",saved:"Куратор сохранён. Связь теперь зафиксирована.",fixed:"Назначается один раз и не меняется.",optional:"Необязательно. RefID должен принадлежать VIP-участнику или администратору.",invalid:"Недействительный RefID куратора",shareTitle:"Поделиться курсом",shareButton:"Копировать или поделиться",copied:"Скопировано",title:"Мои ученики",intro:"Здесь показаны подписки, назначенные вашему RefID куратора.",language:"Язык обучения",allLanguages:"Все языки",subscriptions:"подписок",student:"Ученик",course:"Курс",languageLevel:"Язык / уровень",expires:"Истекает",reward:"Награда",eligible:"Доступна",empty:"Подписок на этом языке пока нет.",loadError:"Не удалось загрузить учеников."},
 it:{...en,menu:"I miei studenti",supervisor:"Supervisore",enter:"Inserisci RefID VIP",save:"Salva",checking:"Verifica…",saved:"Supervisore salvato. Il rapporto è ora definitivo.",fixed:"Assegnato una volta e non modificabile.",optional:"Facoltativo. Il RefID deve appartenere a un membro VIP o amministratore.",invalid:"RefID supervisore non valido",shareTitle:"Condividi questo corso",shareButton:"Copia o condividi link",copied:"Copiato",title:"I miei studenti",intro:"Abbonamenti assegnati al tuo RefID supervisore.",language:"Lingua di studio",allLanguages:"Tutte le lingue",subscriptions:"abbonamenti",student:"Studente",course:"Corso",languageLevel:"Lingua / livello",expires:"Scadenza",reward:"Premio",eligible:"Idoneo",empty:"Nessun abbonamento per questa lingua.",loadError:"Impossibile caricare gli studenti."},
 pt:{...en,menu:"Meus alunos",supervisor:"Supervisor",enter:"Insira o RefID VIP",save:"Salvar",checking:"Verificando…",saved:"Supervisor salvo. Esta relação agora é fixa.",fixed:"Atribuído uma vez e não pode ser alterado.",optional:"Opcional. O RefID deve pertencer a membro VIP ou administrador.",invalid:"RefID de supervisor inválido",shareTitle:"Compartilhar este curso",shareButton:"Copiar ou compartilhar link",copied:"Copiado",title:"Meus alunos",intro:"Assinaturas atribuídas ao seu RefID de supervisor.",language:"Idioma de aprendizagem",allLanguages:"Todos os idiomas",subscriptions:"assinaturas",student:"Aluno",course:"Curso",languageLevel:"Idioma / nível",expires:"Expira",reward:"Recompensa",eligible:"Elegível",empty:"Ainda não há assinaturas neste idioma.",loadError:"Não foi possível carregar os alunos."},
 ar:{...en,menu:"طلابي",supervisor:"المشرف",enter:"أدخل RefID لكبار الأعضاء",save:"حفظ",checking:"جارٍ التحقق…",saved:"تم حفظ المشرف وتثبيت العلاقة.",fixed:"يُعيّن مرة واحدة ولا يمكن تغييره.",optional:"اختياري. يجب أن يخص RefID عضوًا مميزًا أو مسؤولًا.",invalid:"RefID المشرف غير صالح",shareTitle:"مشاركة هذه الدورة",shareButton:"نسخ الرابط أو مشاركته",copied:"تم النسخ",title:"طلابي",intro:"اشتراكات الدورات المرتبطة بمعرّف المشرف الخاص بك.",language:"لغة التعلم",allLanguages:"كل اللغات",subscriptions:"اشتراكات",student:"الطالب",course:"الدورة",languageLevel:"اللغة / المستوى",expires:"تنتهي",reward:"المكافأة",eligible:"مؤهل",empty:"لا توجد اشتراكات بهذه اللغة بعد.",loadError:"تعذر تحميل الطلاب."},
 hi:{...en,menu:"मेरे विद्यार्थी",supervisor:"पर्यवेक्षक",enter:"VIP RefID दर्ज करें",save:"सहेजें",checking:"जाँच जारी…",saved:"पर्यवेक्षक सहेजा गया। यह संबंध अब स्थायी है।",fixed:"एक बार असाइन होने के बाद बदला नहीं जा सकता।",optional:"वैकल्पिक। RefID VIP सदस्य या प्रशासक का होना चाहिए।",invalid:"अमान्य पर्यवेक्षक RefID",shareTitle:"यह पाठ्यक्रम साझा करें",shareButton:"लिंक कॉपी या साझा करें",copied:"कॉपी किया गया",title:"मेरे विद्यार्थी",intro:"आपके पर्यवेक्षक RefID को सौंपे गए पाठ्यक्रम सदस्यता।",language:"सीखने की भाषा",allLanguages:"सभी भाषाएँ",subscriptions:"सदस्यताएँ",student:"विद्यार्थी",course:"पाठ्यक्रम",languageLevel:"भाषा / स्तर",expires:"समाप्ति",reward:"पुरस्कार",eligible:"पात्र",empty:"इस भाषा की कोई सदस्यता अभी नहीं है।",loadError:"विद्यार्थियों को लोड नहीं किया जा सका।"},
};
export const courseSupervisorCopy=(lang:InterfaceLanguage)=>courseSupervisorCopies[lang];
