import { getDatabase } from "@/lib/auth";
import { CRYPTO_PLANS, type CryptoPaymentSetting, type CryptoPlanId } from "./crypto-contract";
export { CRYPTO_PLANS } from "./crypto-contract";
export type { CryptoPaymentSetting, CryptoPlanId } from "./crypto-contract";
const fields=`id,label,chain_type AS chainType,chain_name AS chainName,chain_id AS chainId,token_symbol AS tokenSymbol,token_contract AS tokenContract,token_decimals AS tokenDecimals,receiver_wallet AS receiverWallet,smartpay4_contract AS smartPay4Contract,smartpay4_usdt_percent AS smartPay4UsdtPercent,basic_amount_cents AS basicAmountCents,intermediate_amount_cents AS intermediateAmountCents,advanced_amount_cents AS advancedAmountCents,basic_token_amount AS basicTokenAmount,intermediate_token_amount AS intermediateTokenAmount,advanced_token_amount AS advancedTokenAmount,min_confirmations AS minConfirmations,walletconnect_project_id AS walletConnectProjectId,enabled`;
export async function activeCryptoPaymentSettings(){const result=await getDatabase().prepare(`SELECT ${fields} FROM crypto_payment_settings WHERE enabled=1 AND deleted_at IS NULL ORDER BY chain_id,label`).run<CryptoPaymentSetting>();return result.results??[];}
export async function allCryptoPaymentSettings(){const result=await getDatabase().prepare(`SELECT ${fields} FROM crypto_payment_settings WHERE deleted_at IS NULL ORDER BY chain_id,label`).run<CryptoPaymentSetting>();return result.results??[];}
export async function cryptoPaymentSettingById(id:string){return getDatabase().prepare(`SELECT ${fields} FROM crypto_payment_settings WHERE id=? AND enabled=1 AND deleted_at IS NULL LIMIT 1`).bind(id).first<CryptoPaymentSetting>();}
export function cryptoPlan(id:unknown){return CRYPTO_PLANS.find((plan)=>plan.id===id)??null;}
export function tokenAmountFor(setting:CryptoPaymentSetting,planId:CryptoPlanId){return planId==="basic"?setting.basicTokenAmount:planId==="intermediate"?setting.intermediateTokenAmount:setting.advancedTokenAmount;}
export function normalizeTokenAmount(value:unknown,decimals:number){const raw=String(value??"").trim();if(!/^\d+(?:\.\d+)?$/.test(raw))throw new Error("INVALID_TOKEN_AMOUNT");const[wholeRaw,fractionRaw=""]=raw.split(".");if(fractionRaw.length>decimals)throw new Error("INVALID_TOKEN_AMOUNT");const whole=wholeRaw.replace(/^0+(?=\d)/,"")||"0";const fraction=fractionRaw.replace(/0+$/,"");if(whole==="0"&&!fraction)throw new Error("INVALID_TOKEN_AMOUNT");return fraction?`${whole}.${fraction}`:whole;}
export function tokenAmountToAtomic(value:string,decimals:number){const normalized=normalizeTokenAmount(value,decimals);const[whole,fraction=""]=normalized.split(".");return BigInt(whole)*BigInt(10)**BigInt(decimals)+BigInt(`${fraction}${"0".repeat(decimals)}`.slice(0,decimals)||"0");}
