import type { InterfaceLanguage } from "./interface-locale";

type Copy = { active: string; inactive: string; until: string; ended: string; extend: string; getMax: string; findLevel: string; webinar: string; score: string; certificates: string; signOut: string; saveError: string };

export const learningUiCopy: Record<InterfaceLanguage, Copy> = {
  en: { active: "Max is active", inactive: "Max is not active", until: "Until", ended: "Ended", extend: "Extend Max", getMax: "Get Max", findLevel: "Find your starting point", webinar: "Language webinar", score: "Score history", certificates: "Certificates", signOut: "Sign out", saveError: "Could not save this language. Please try again." },
  zh: { active: "Max 已生效", inactive: "Max 尚未生效", until: "到期日", ended: "已于此日结束", extend: "延长 Max", getMax: "开通 Max", findLevel: "测一测起点", webinar: "语言直播教室", score: "成绩记录", certificates: "结业证书", signOut: "退出登录", saveError: "暂时无法保存语言，请重试。" },
  es: { active: "Max está activo", inactive: "Max no está activo", until: "Hasta", ended: "Finalizó", extend: "Ampliar Max", getMax: "Activar Max", findLevel: "Descubre tu nivel", webinar: "Seminario de idiomas", score: "Historial de resultados", certificates: "Certificados", signOut: "Cerrar sesión", saveError: "No se pudo guardar el idioma. Inténtalo de nuevo." },
  ja: { active: "Max 利用中", inactive: "Max 未利用", until: "有効期限", ended: "終了日", extend: "Max を延長", getMax: "Max を始める", findLevel: "開始レベルを調べる", webinar: "言語ウェビナー", score: "成績履歴", certificates: "修了証", signOut: "ログアウト", saveError: "言語を保存できませんでした。再試行してください。" },
  ko: { active: "Max 사용 중", inactive: "Max 미사용", until: "만료일", ended: "종료일", extend: "Max 연장", getMax: "Max 시작", findLevel: "시작 수준 찾기", webinar: "언어 웨비나", score: "점수 기록", certificates: "수료증", signOut: "로그아웃", saveError: "언어를 저장하지 못했습니다. 다시 시도하세요." },
  fr: { active: "Max est actif", inactive: "Max n’est pas actif", until: "Jusqu’au", ended: "Terminé le", extend: "Prolonger Max", getMax: "Activer Max", findLevel: "Trouver votre niveau", webinar: "Webinaire de langue", score: "Historique des scores", certificates: "Certificats", signOut: "Déconnexion", saveError: "Impossible d’enregistrer cette langue. Réessayez." },
  de: { active: "Max ist aktiv", inactive: "Max ist nicht aktiv", until: "Bis", ended: "Beendet am", extend: "Max verlängern", getMax: "Max starten", findLevel: "Einstiegsniveau finden", webinar: "Sprach-Webinar", score: "Punkteverlauf", certificates: "Zertifikate", signOut: "Abmelden", saveError: "Sprache konnte nicht gespeichert werden. Bitte erneut versuchen." },
  ru: { active: "Max активен", inactive: "Max не активен", until: "До", ended: "Завершился", extend: "Продлить Max", getMax: "Подключить Max", findLevel: "Определить свой уровень", webinar: "Языковой вебинар", score: "История результатов", certificates: "Сертификаты", signOut: "Выйти", saveError: "Не удалось сохранить язык. Попробуйте снова." },
  it: { active: "Max è attivo", inactive: "Max non è attivo", until: "Fino al", ended: "Terminato il", extend: "Estendi Max", getMax: "Attiva Max", findLevel: "Trova il tuo livello", webinar: "Webinar linguistico", score: "Cronologia punteggi", certificates: "Certificati", signOut: "Esci", saveError: "Impossibile salvare la lingua. Riprova." },
  pt: { active: "Max está ativo", inactive: "Max não está ativo", until: "Até", ended: "Terminou em", extend: "Estender Max", getMax: "Ativar Max", findLevel: "Descubra seu nível", webinar: "Webinar de idiomas", score: "Histórico de pontuação", certificates: "Certificados", signOut: "Sair", saveError: "Não foi possível salvar o idioma. Tente novamente." },
  ar: { active: "Max نشط", inactive: "Max غير نشط", until: "حتى", ended: "انتهى في", extend: "مدّد Max", getMax: "ابدأ Max", findLevel: "اكتشف مستواك", webinar: "ندوة اللغة", score: "سجل الدرجات", certificates: "الشهادات", signOut: "تسجيل الخروج", saveError: "تعذّر حفظ اللغة. حاول مرة أخرى." },
  hi: { active: "Max सक्रिय है", inactive: "Max सक्रिय नहीं है", until: "तक", ended: "समाप्त हुआ", extend: "Max बढ़ाएँ", getMax: "Max शुरू करें", findLevel: "अपना स्तर जानें", webinar: "भाषा वेबिनार", score: "अंक इतिहास", certificates: "प्रमाणपत्र", signOut: "साइन आउट", saveError: "भाषा सहेज नहीं सके। फिर कोशिश करें।" },
};
