import { translateTraditionalCopy, type BaseInterfaceLanguage, type InterfaceLanguage } from "./interface-locale";

type LearningExperienceCopy = {
  homeTitle: string;
  homeIntro: string;
  flashAudience: string;
  flashBody: string;
  maxAudience: string;
  maxBody: string;
  guruBody: string;
  flashIntro: string;
  maxIntro: string;
  yourLanguages: string;
  addLanguage: string;
  noLanguages: string;
  trialStatus: string;
  trialUsed: string;
  languageIntro: string;
  webinarBody: string;
  roomSignIn: string;
  continueLearning: string;
};

const baseLearningExperienceCopy: Record<BaseInterfaceLanguage, LearningExperienceCopy> = {
  en: { homeTitle: "Two ways to learn. One language at a time.", homeIntro: "Choose relaxed practice with Flash or a focused path with Max. Ask Guru whenever you need a starting point.", flashAudience: "For casual learners", flashBody: "Free, playful language practice. Start without signing in.", maxAudience: "For committed learners", maxBody: "A focused path, one-to-one AI role tutor, and all learning levels.", guruBody: "Ask a question and find your next step before choosing a path.", flashIntro: "Play, speak, and revisit useful language at your own pace. No sign-in is needed to start.", maxIntro: "A focused learning space with personal progress and an AI role tutor. Sign in to begin your one-time seven-day trial.", yourLanguages: "Your learning languages", addLanguage: "Add a language", noLanguages: "Choose a language to begin.", trialStatus: "One-time seven-day Max trial", trialUsed: "Your trial has ended. Extend Max to continue.", languageIntro: "Your next steps in one language.", webinarBody: "Enter the webinar to listen to the host, review recordings and files, and message the host team.", roomSignIn: "Sign in and join this language to enter the webinar.", continueLearning: "Continue learning" },
  zh: { homeTitle: "两种学习方式，从一门语言开始。", homeIntro: "想轻松练习，选快捷版；想认真提升，选旗舰版。不知道从哪里开始，随时问 Guru。", flashAudience: "适合休闲学习者", flashBody: "免费、好玩的语言练习，不登录也能开始。", maxAudience: "适合认真学习者", maxBody: "专注的学习路径、一对一 AI 角色导师，以及全部学习阶段。", guruBody: "先问一个问题，再找到适合自己的下一步。", flashIntro: "按自己的节奏玩、说、复习实用语言；无需登录即可开始。", maxIntro: "按计划学习、查看个人进度，并与 AI 角色导师一对一练习。登录后开始一次性七天试用。", yourLanguages: "我的学习语言", addLanguage: "添加语言", noLanguages: "选择一种语言开始。", trialStatus: "一次性七天旗舰版试用", trialUsed: "试用已经结束；延长旗舰版后可继续。", languageIntro: "一门语言，所有下一步都在这里。", webinarBody: "进入网络研讨会聆听主持人，查看录音与附件，并给主持团队留言。", roomSignIn: "登录并加入这门语言后即可进入网络研讨会。", continueLearning: "继续学习" },
  es: { homeTitle: "Dos formas de aprender. Un idioma a la vez.", homeIntro: "Practica sin presión con Flash o sigue un camino enfocado con Max. Pregunta a Guru por dónde empezar.", flashAudience: "Para aprender por placer", flashBody: "Práctica gratuita y divertida, sin iniciar sesión.", maxAudience: "Para aprender en serio", maxBody: "Un camino enfocado, tutor de IA individual y todos los niveles.", guruBody: "Haz una pregunta y descubre tu siguiente paso.", flashIntro: "Juega, habla y repasa a tu ritmo. Empieza sin iniciar sesión.", maxIntro: "Aprende con un plan, sigue tu progreso y practica con un tutor de IA. Inicia sesión para activar tu prueba única de siete días.", yourLanguages: "Tus idiomas de aprendizaje", addLanguage: "Añadir idioma", noLanguages: "Elige un idioma para empezar.", trialStatus: "Prueba única de Max de siete días", trialUsed: "Tu prueba terminó. Amplía Max para continuar.", languageIntro: "Tus próximos pasos en un idioma.", webinarBody: "Entra al seminario para escuchar al anfitrión, ver grabaciones y archivos, y escribir al equipo.", roomSignIn: "Inicia sesión y únete a este idioma para entrar.", continueLearning: "Seguir aprendiendo" },
  ja: { homeTitle: "学び方は二つ。言語は一つずつ。", homeIntro: "気軽な練習は Flash、集中学習は Max。始め方に迷ったら Guru に相談できます。", flashAudience: "気軽に学ぶ方へ", flashBody: "無料で楽しい言語練習。ログインなしで始められます。", maxAudience: "本格的に学ぶ方へ", maxBody: "集中できる学習経路、1対1の AI 講師、すべてのレベル。", guruBody: "質問して、次の一歩を見つけましょう。", flashIntro: "自分のペースで遊び、話し、復習しましょう。ログインは不要です。", maxIntro: "計画的に学び、進捗を確認し、AI 講師と1対1で練習。ログインすると一度限りの7日間体験が始まります。", yourLanguages: "学習中の言語", addLanguage: "言語を追加", noLanguages: "まず言語を選んでください。", trialStatus: "一度限りの7日間 Max 体験", trialUsed: "体験期間は終了しました。Max を延長してください。", languageIntro: "一つの言語の次のステップ。", webinarBody: "ウェビナーで主催者の音声を聞き、録音や資料を確認し、主催チームに連絡できます。", roomSignIn: "ログインしてこの言語に参加すると入室できます。", continueLearning: "学習を続ける" },
  ko: { homeTitle: "두 가지 학습법. 한 번에 한 언어씩.", homeIntro: "가볍게 연습하려면 Flash, 집중해서 배우려면 Max를 선택하세요. 시작이 어렵다면 Guru에게 물어보세요.", flashAudience: "가볍게 배우는 분께", flashBody: "무료로 즐겁게 연습하세요. 로그인 없이 시작할 수 있습니다.", maxAudience: "진지하게 배우는 분께", maxBody: "집중 학습 경로, 일대일 AI 튜터, 모든 단계.", guruBody: "질문하고 다음 단계를 찾아보세요.", flashIntro: "자신의 속도로 놀고 말하고 복습하세요. 로그인은 필요 없습니다.", maxIntro: "계획에 따라 배우고 진도를 확인하며 AI 튜터와 일대일로 연습하세요. 로그인하면 일회성 7일 체험이 시작됩니다.", yourLanguages: "내 학습 언어", addLanguage: "언어 추가", noLanguages: "시작할 언어를 선택하세요.", trialStatus: "일회성 Max 7일 체험", trialUsed: "체험이 끝났습니다. Max를 연장해 계속하세요.", languageIntro: "한 언어의 다음 단계가 한곳에.", webinarBody: "웨비나에서 진행자의 음성을 듣고 녹음과 파일을 확인하며 진행팀에 메시지를 보내세요.", roomSignIn: "로그인하고 이 언어에 참여하면 입장할 수 있습니다.", continueLearning: "학습 계속하기" },
  fr: { homeTitle: "Deux façons d’apprendre. Une langue à la fois.", homeIntro: "Pratiquez librement avec Flash ou progressez avec Max. Demandez à Guru par où commencer.", flashAudience: "Pour apprendre à son rythme", flashBody: "Une pratique gratuite et ludique, sans connexion.", maxAudience: "Pour apprendre sérieusement", maxBody: "Un parcours ciblé, un tuteur IA individuel et tous les niveaux.", guruBody: "Posez une question et trouvez votre prochaine étape.", flashIntro: "Jouez, parlez et révisez à votre rythme. Aucune connexion nécessaire.", maxIntro: "Apprenez avec un plan, suivez vos progrès et pratiquez avec un tuteur IA. Connectez-vous pour commencer votre essai unique de sept jours.", yourLanguages: "Vos langues d’apprentissage", addLanguage: "Ajouter une langue", noLanguages: "Choisissez une langue pour commencer.", trialStatus: "Essai Max unique de sept jours", trialUsed: "Votre essai est terminé. Prolongez Max pour continuer.", languageIntro: "Vos prochaines étapes dans une langue.", webinarBody: "Entrez dans le webinaire pour écouter l’animateur, consulter enregistrements et fichiers, et écrire à l’équipe.", roomSignIn: "Connectez-vous et rejoignez cette langue pour entrer.", continueLearning: "Continuer à apprendre" },
  de: { homeTitle: "Zwei Lernwege. Eine Sprache nach der anderen.", homeIntro: "Übe entspannt mit Flash oder lerne gezielt mit Max. Frage Guru nach deinem Einstieg.", flashAudience: "Für entspanntes Lernen", flashBody: "Kostenlos und spielerisch üben, ohne Anmeldung.", maxAudience: "Für ernsthaftes Lernen", maxBody: "Ein klarer Lernweg, persönlicher KI-Tutor und alle Stufen.", guruBody: "Stelle eine Frage und finde deinen nächsten Schritt.", flashIntro: "Spiele, sprich und wiederhole in deinem Tempo. Keine Anmeldung nötig.", maxIntro: "Lerne mit Plan, verfolge Fortschritte und übe einzeln mit einem KI-Tutor. Nach der Anmeldung beginnt deine einmalige siebentägige Probezeit.", yourLanguages: "Deine Lernsprachen", addLanguage: "Sprache hinzufügen", noLanguages: "Wähle zuerst eine Sprache.", trialStatus: "Einmalige siebentägige Max-Probezeit", trialUsed: "Deine Probezeit ist vorbei. Verlängere Max.", languageIntro: "Deine nächsten Schritte in einer Sprache.", webinarBody: "Im Webinar hörst du den Gastgeber, siehst Aufnahmen und Dateien und schreibst dem Team.", roomSignIn: "Melde dich an und tritt dieser Sprache bei.", continueLearning: "Weiterlernen" },
  ru: { homeTitle: "Два способа учиться. По одному языку за раз.", homeIntro: "Учитесь легко с Flash или целенаправленно с Max. Спросите Guru, с чего начать.", flashAudience: "Для свободного обучения", flashBody: "Бесплатная игровая практика без входа.", maxAudience: "Для серьёзного обучения", maxBody: "План занятий, личный ИИ-наставник и все уровни.", guruBody: "Задайте вопрос и найдите следующий шаг.", flashIntro: "Играйте, говорите и повторяйте в своём темпе. Вход не нужен.", maxIntro: "Учитесь по плану, следите за прогрессом и занимайтесь с ИИ-наставником. Войдите, чтобы начать единственный семидневный пробный период.", yourLanguages: "Языки, которые вы изучаете", addLanguage: "Добавить язык", noLanguages: "Выберите язык для начала.", trialStatus: "Единственный пробный период Max — 7 дней", trialUsed: "Пробный период закончился. Продлите Max.", languageIntro: "Следующие шаги для одного языка.", webinarBody: "Откройте вебинар, чтобы слушать ведущего, просматривать записи и файлы и писать команде.", roomSignIn: "Войдите и присоединитесь к этому языку.", continueLearning: "Продолжить обучение" },
  it: { homeTitle: "Due modi di imparare. Una lingua alla volta.", homeIntro: "Esercitati senza pressione con Flash o segui un percorso mirato con Max. Chiedi a Guru da dove iniziare.", flashAudience: "Per chi impara per piacere", flashBody: "Pratica gratuita e divertente, senza accesso.", maxAudience: "Per chi studia seriamente", maxBody: "Un percorso mirato, tutor IA individuale e tutti i livelli.", guruBody: "Fai una domanda e trova il prossimo passo.", flashIntro: "Gioca, parla e ripassa al tuo ritmo. Non serve accedere.", maxIntro: "Studia con un piano, segui i progressi e pratica con un tutor IA. Accedi per iniziare la prova unica di sette giorni.", yourLanguages: "Le lingue che stai imparando", addLanguage: "Aggiungi lingua", noLanguages: "Scegli una lingua per iniziare.", trialStatus: "Prova Max unica di sette giorni", trialUsed: "La prova è terminata. Estendi Max per continuare.", languageIntro: "I prossimi passi in una lingua.", webinarBody: "Entra nel webinar per ascoltare chi conduce, vedere registrazioni e file e scrivere al team.", roomSignIn: "Accedi e unisciti a questa lingua per entrare.", continueLearning: "Continua a imparare" },
  pt: { homeTitle: "Duas formas de aprender. Um idioma de cada vez.", homeIntro: "Pratique sem pressão com Flash ou siga um caminho focado com Max. Pergunte ao Guru por onde começar.", flashAudience: "Para aprender por diversão", flashBody: "Prática grátis e divertida, sem entrar na conta.", maxAudience: "Para quem leva a sério", maxBody: "Um caminho focado, tutor de IA individual e todos os níveis.", guruBody: "Faça uma pergunta e descubra o próximo passo.", flashIntro: "Brinque, fale e revise no seu ritmo. Não precisa entrar na conta.", maxIntro: "Aprenda com um plano, acompanhe seu progresso e pratique com um tutor de IA. Entre para começar seu teste único de sete dias.", yourLanguages: "Seus idiomas de aprendizagem", addLanguage: "Adicionar idioma", noLanguages: "Escolha um idioma para começar.", trialStatus: "Teste único de Max por sete dias", trialUsed: "Seu teste terminou. Estenda o Max para continuar.", languageIntro: "Seus próximos passos em um idioma.", webinarBody: "Entre no webinar para ouvir o anfitrião, ver gravações e arquivos e escrever à equipe.", roomSignIn: "Entre na conta e participe deste idioma.", continueLearning: "Continuar aprendendo" },
  ar: { homeTitle: "طريقتان للتعلم، لغة واحدة كل مرة.", homeIntro: "تدرّب بسهولة مع Flash أو اتبع مسارًا مركزًا مع Max. اسأل Guru من أين تبدأ.", flashAudience: "للتعلم في وقت الفراغ", flashBody: "تدريب مجاني وممتع دون تسجيل الدخول.", maxAudience: "للمتعلمين الجادين", maxBody: "مسار مركز ومعلّم ذكاء اصطناعي فردي وجميع المستويات.", guruBody: "اطرح سؤالًا وحدد خطوتك التالية.", flashIntro: "العب وتحدث وراجع وفق وتيرتك، دون تسجيل الدخول.", maxIntro: "تعلّم وفق خطة وتابع تقدمك وتدرّب مع معلّم ذكاء اصطناعي. سجّل الدخول لبدء تجربة واحدة مدتها سبعة أيام.", yourLanguages: "لغاتك التي تتعلمها", addLanguage: "أضف لغة", noLanguages: "اختر لغة لتبدأ.", trialStatus: "تجربة Max واحدة لمدة سبعة أيام", trialUsed: "انتهت التجربة. مدّد Max للمتابعة.", languageIntro: "خطواتك التالية في لغة واحدة.", webinarBody: "ادخل الندوة للاستماع إلى المضيف ومراجعة التسجيلات والملفات ومراسلة فريق الاستضافة.", roomSignIn: "سجّل الدخول وانضم إلى هذه اللغة للدخول.", continueLearning: "تابع التعلم" },
  hi: { homeTitle: "सीखने के दो तरीके। एक समय में एक भाषा।", homeIntro: "आराम से अभ्यास के लिए Flash या केंद्रित अध्ययन के लिए Max चुनें। शुरुआत के लिए Guru से पूछें।", flashAudience: "आराम से सीखने वालों के लिए", flashBody: "मुफ़्त और मज़ेदार अभ्यास, बिना साइन इन किए।", maxAudience: "गंभीर शिक्षार्थियों के लिए", maxBody: "केंद्रित मार्ग, निजी AI शिक्षक और सभी स्तर।", guruBody: "सवाल पूछें और अगला कदम जानें।", flashIntro: "अपनी गति से खेलें, बोलें और दोहराएँ। साइन इन ज़रूरी नहीं है।", maxIntro: "योजना से सीखें, प्रगति देखें और AI शिक्षक से अकेले अभ्यास करें। साइन इन पर एक बार की सात दिन की ट्रायल शुरू होगी।", yourLanguages: "आपकी सीखने की भाषाएँ", addLanguage: "भाषा जोड़ें", noLanguages: "शुरू करने के लिए भाषा चुनें।", trialStatus: "एक बार की सात दिन की Max ट्रायल", trialUsed: "ट्रायल समाप्त हो गई। जारी रखने के लिए Max बढ़ाएँ।", languageIntro: "एक भाषा में आपके अगले कदम।", webinarBody: "मेज़बान को सुनने, रिकॉर्डिंग और फ़ाइलें देखने और टीम को संदेश भेजने के लिए वेबिनार खोलें।", roomSignIn: "अंदर जाने के लिए साइन इन करें और इस भाषा से जुड़ें।", continueLearning: "सीखना जारी रखें" },
};
export const learningExperienceCopy: Record<InterfaceLanguage, LearningExperienceCopy> = {
  ...baseLearningExperienceCopy,
  "zh-tw": translateTraditionalCopy(baseLearningExperienceCopy.zh),
};

export function learningPathDisplayName(lang: InterfaceLanguage, path: "flash" | "max") {
  return lang === "zh" || lang === "zh-tw" ? (path === "flash" ? "快捷版" : lang === "zh-tw" ? "旗艦版" : "旗舰版") : (path === "flash" ? "Flash" : "Max");
}
