import { getClassRuntimeBindings as getBindings } from "@/lib/live-class-runtime";
export type ClassParticipantRole="viewer"|"member"|"host";
export type ClassRealtimeMode="group_call"|"webinar"|"livestream";
type Envelope<T>={success?:boolean;result?:T;data?:T;errors?:Array<{message?:string}>};
type ProviderPreset={id?:string;name?:string;config?:{max_screenshare_count?:number};permissions?:{media?:{screenshare?:{can_produce?:string}}}};
const screenShareReadyPresets=new Set<string>();

async function config(){
  const env=getBindings() as ReturnType<typeof getBindings>&Record<string,string|undefined>;
  const value={token:env.CLOUDFLARE_REALTIME_API_TOKEN||"",accountId:env.CLOUDFLARE_ACCOUNT_ID||"",appId:env.REALTIMEKIT_APP_ID||"",guest:env.REALTIMEKIT_GUEST_PRESET||"",member:env.REALTIMEKIT_MEMBER_PRESET||"",host:env.REALTIMEKIT_HOST_PRESET||"",viewer:env.REALTIMEKIT_VIEWER_PRESET||env.REALTIMEKIT_GUEST_PRESET||"",webinarHost:env.REALTIMEKIT_WEBINAR_HOST_PRESET||"webinar_presenter",webinarSpeaker:env.REALTIMEKIT_WEBINAR_SPEAKER_PRESET||"webinar_presenter",webinarViewer:env.REALTIMEKIT_WEBINAR_VIEWER_PRESET||"webinar_viewer",livestreamHost:env.REALTIMEKIT_LIVESTREAM_HOST_PRESET||"livestream_host",livestreamSpeaker:env.REALTIMEKIT_LIVESTREAM_SPEAKER_PRESET||"livestream_host",livestreamViewer:env.REALTIMEKIT_LIVESTREAM_VIEWER_PRESET||"livestream_viewer"};
  if(!value.token||!value.accountId||!value.appId||value.appId.includes("REQUIRED")||!value.member||!value.host||!value.viewer)throw new Error("REALTIME_NOT_CONFIGURED");
  return value;
}
async function call<T>(path:string,init:RequestInit){const value=await config();const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(value.accountId)}/realtime/kit/${encodeURIComponent(value.appId)}${path}`,{...init,headers:{authorization:`Bearer ${value.token}`,"content-type":"application/json",...(init.headers||{})}});const payload=await response.json().catch(()=>null)as Envelope<T>|null;const data=payload?.data??payload?.result;if(!response.ok||!payload?.success||!data)throw new Error(payload?.errors?.[0]?.message||`REALTIME_${response.status}`);return data;}
async function ensureHostScreenSharePreset(name:string){if(screenShareReadyPresets.has(name))return;const presets=await call<ProviderPreset[]>("/presets?per_page=100",{method:"GET"}),preset=presets.find(item=>item.name===name);if(!preset?.id)throw new Error(`REALTIME_PRESET_NOT_FOUND:${name}`);const permissionReady=preset.permissions?.media?.screenshare?.can_produce==="ALLOWED",countReady=Number(preset.config?.max_screenshare_count||0)>=1;if(!permissionReady||!countReady)await call<ProviderPreset>(`/presets/${encodeURIComponent(preset.id)}`,{method:"PATCH",body:JSON.stringify({...(!countReady?{config:{max_screenshare_count:1}}:{}),...(!permissionReady?{permissions:{media:{screenshare:{can_produce:"ALLOWED"}}}}:{})})});screenShareReadyPresets.add(name);}
export async function createClassProviderRoom(title:string){return call<{id:string}>("/meetings",{method:"POST",body:JSON.stringify({title:title.slice(0,120)})});}
export async function createClassParticipant(meetingId:string,identity:string,name:string,role:ClassParticipantRole,mode:ClassRealtimeMode){const value=await config();const preset=mode==="webinar"?(role==="viewer"?value.webinarViewer:role==="host"?value.webinarHost:value.webinarSpeaker):mode==="livestream"?(role==="viewer"?value.livestreamViewer:role==="host"?value.livestreamHost:value.livestreamSpeaker):(role==="host"?value.host:role==="member"?value.member:value.viewer);if(role==="host")await ensureHostScreenSharePreset(preset);return call<{id:string;token:string}>(`/meetings/${encodeURIComponent(meetingId)}/participants`,{method:"POST",body:JSON.stringify({name:name.slice(0,80)||"Guest",preset_name:preset,custom_participant_id:`${identity}:${crypto.randomUUID()}`})});}
