import type { InterfaceLanguage } from "./interface-locale";

export type SmartLingoTutorialCopy = {
  metaTitle: string;
  homeAction: string;
  eyebrow: string;
  title: string;
  intro: string;
  duration: string;
  visitorLabel: string;
  visitorTitle: string;
  visitorBody: string;
  memberLabel: string;
  memberTitle: string;
  memberBody: string;
  watchLabel: string;
  mediaNote: string;
  captionsNote: string;
  accountTitle: string;
  accountBody: string;
  privacyTitle: string;
  privacyBody: string;
  homeLink: string;
  startLink: string;
};

const en: SmartLingoTutorialCopy = {
  metaTitle: "First-time video tour",
  homeAction: "Watch the 10-minute first-time tour",
  eyebrow: "SMARTLINGO · FIRST-TIME TOUR",
  title: "See the complete visitor and member journey in ten minutes.",
  intro: "Start without an account, explore every core learning path, then see how a signed-in member saves progress, scores, courses, community activity, and account settings.",
  duration: "10 minutes · English narration · captions included",
  visitorLabel: "PART ONE · VISITOR",
  visitorTitle: "Try SmartLingo before joining",
  visitorBody: "Tour Learn, Today's Sprint, SmartCards, Challenge, Everyday speaking, Community, courses, colleges, and both sign-up choices without exposing any real credentials.",
  memberLabel: "PART TWO · MEMBER",
  memberTitle: "Continue with saved progress",
  memberBody: "See the Dashboard, score history, learning calendar, My Courses, Community, messages, and the password-safe account workflow using a dedicated masked test member.",
  watchLabel: "Play the SmartLingo first-time tour",
  mediaNote: "The Chinese page uses the Chinese recording. All other interface languages use this English recording.",
  captionsNote: "The video includes spoken narration, burned-in key captions, and a selectable WebVTT caption track.",
  accountTitle: "Two continuing account choices",
  accountBody: "Join with an email verification code or switch to an eight-character password. Both methods remain available for the same account; password recovery uses a one-time reset code.",
  privacyTitle: "Safe tutorial recording",
  privacyBody: "No real email address, password, or verification code appears. Member identity is masked and microphone access remains off unless a learner intentionally enables speaking practice.",
  homeLink: "Back to home",
  startLink: "Start learning free",
};

export const smartLingoTutorialCopies = {
  en,
  zh: {
    metaTitle: "新手视频教程",
    homeAction: "观看 10 分钟新手教程",
    eyebrow: "SMARTLINGO · 新手导览",
    title: "十分钟看懂访客与登录会员的完整使用流程。",
    intro: "先在无需账户的状态体验核心学习路径，再查看登录会员如何保存进度、成绩、课程、社区互动与账户设置。",
    duration: "10 分钟 · 中文语音 · 包含字幕",
    visitorLabel: "第一部分 · 未登录访客",
    visitorTitle: "注册前先完整体验",
    visitorBody: "依次了解学习、今日速成、智慧卡、挑战、生活口语、社区、课程、学院，以及两种注册方式；全程不展示任何真实凭据。",
    memberLabel: "第二部分 · 登录会员",
    memberTitle: "保存进度并跨设备继续",
    memberBody: "通过已隐藏身份的专用测试会员，查看用户面板、成绩历史、学习日历、我的课程、社区、消息和安全密码流程。",
    watchLabel: "播放 SmartLingo 新手导览",
    mediaNote: "中文页面播放中文版本；其他界面语言统一播放英文版本。",
    captionsNote: "视频包含中文语音、画面重点字幕，以及可在播放器中选择的 WebVTT 字幕轨。",
    accountTitle: "两种登录方式长期共存",
    accountBody: "可以使用邮箱验证码加入，也可以切换到至少八位的密码。两种方式进入同一账户；忘记密码时使用一次性重置代码。",
    privacyTitle: "安全录制，不暴露账户资料",
    privacyBody: "视频不显示真实邮箱、密码或验证码；会员身份已遮挡，麦克风也只会在学习者主动开启口语练习后使用。",
    homeLink: "返回首页",
    startLink: "免费开始学习",
  },
  es: {
    ...en,
    metaTitle: "Vídeo de primeros pasos",
    homeAction: "Ver el recorrido de 10 minutos",
    eyebrow: "SMARTLINGO · PRIMEROS PASOS",
    title: "Descubre en diez minutos la experiencia completa de visitante y miembro.",
    intro: "Prueba las rutas esenciales sin cuenta y descubre cómo un miembro guarda progreso, resultados, cursos, comunidad y ajustes.",
    duration: "10 minutos · narración en inglés · subtítulos incluidos",
    visitorLabel: "PARTE UNO · VISITANTE",
    visitorTitle: "Prueba SmartLingo antes de registrarte",
    visitorBody: "Recorre Aprender, Sprint de hoy, SmartCards, Desafío, conversación cotidiana, Comunidad, cursos, academias y las dos opciones de registro.",
    memberLabel: "PARTE DOS · MIEMBRO",
    memberTitle: "Continúa con el progreso guardado",
    memberBody: "Consulta el panel, historial de puntos, calendario, cursos, comunidad, mensajes y seguridad con una cuenta de prueba protegida.",
    watchLabel: "Reproducir el recorrido de SmartLingo",
    mediaNote: "La página china usa el vídeo chino. Los demás idiomas de interfaz usan esta versión en inglés.",
    captionsNote: "Incluye narración, subtítulos clave en pantalla y una pista WebVTT seleccionable.",
    accountTitle: "Dos formas de acceso permanentes",
    accountBody: "Usa un código de correo o una contraseña de ocho caracteres. Ambas opciones sirven para la misma cuenta.",
    privacyTitle: "Grabación segura",
    privacyBody: "No aparecen correos, contraseñas ni códigos reales. La identidad de prueba está oculta.",
    homeLink: "Volver al inicio",
    startLink: "Empezar gratis",
  },
  ja: {
    ...en,
    metaTitle: "初めての動画ガイド",
    homeAction: "10分の初回ガイドを見る",
    eyebrow: "SMARTLINGO · 初回ガイド",
    title: "訪問者と会員の流れを10分で確認できます。",
    intro: "アカウントなしで主要な学習機能を試し、ログイン後の進捗、スコア、コース、コミュニティ、設定を確認します。",
    duration: "10分 · 英語音声 · 字幕付き",
    visitorLabel: "前半 · 訪問者",
    visitorTitle: "登録前に SmartLingo を体験",
    visitorBody: "学習、今日の速習、SmartCard、チャレンジ、日常会話、コミュニティ、コース、カレッジ、2つの登録方法を紹介します。",
    memberLabel: "後半 · 会員",
    memberTitle: "保存した進捗から再開",
    memberBody: "匿名化したテスト会員で、ダッシュボード、スコア履歴、学習カレンダー、コース、メッセージ、アカウント設定を確認します。",
    watchLabel: "SmartLingo 初回ガイドを再生",
    mediaNote: "中国語ページは中国語版、その他の表示言語は英語版を使用します。",
    captionsNote: "音声解説、画面内字幕、選択可能な WebVTT 字幕が含まれます。",
    accountTitle: "2つのログイン方法",
    accountBody: "メールコードまたは8文字以上のパスワードを利用でき、どちらも同じアカウントにつながります。",
    privacyTitle: "安全なチュートリアル",
    privacyBody: "実際のメール、パスワード、確認コードは表示されず、テスト会員の識別情報も隠されています。",
    homeLink: "ホームに戻る",
    startLink: "無料で学習を開始",
  },
  ko: {
    ...en,
    metaTitle: "첫 사용자 동영상 안내",
    homeAction: "10분 첫 사용자 안내 보기",
    eyebrow: "SMARTLINGO · 첫 사용자 안내",
    title: "방문자와 회원의 전체 여정을 10분 안에 확인하세요.",
    intro: "계정 없이 핵심 학습을 체험하고 로그인 회원의 진도, 점수, 과정, 커뮤니티와 설정을 확인합니다.",
    duration: "10분 · 영어 음성 · 자막 포함",
    visitorLabel: "1부 · 방문자",
    visitorTitle: "가입 전에 SmartLingo 체험",
    visitorBody: "학습, 오늘의 스프린트, SmartCard, 챌린지, 생활 회화, 커뮤니티, 과정, 칼리지와 두 가지 가입 방식을 둘러봅니다.",
    memberLabel: "2부 · 회원",
    memberTitle: "저장된 진도에서 계속",
    memberBody: "보호된 테스트 회원으로 대시보드, 점수 기록, 학습 달력, 내 과정, 메시지와 계정 보안을 확인합니다.",
    watchLabel: "SmartLingo 첫 사용자 안내 재생",
    mediaNote: "중국어 페이지는 중국어 영상을, 그 밖의 표시 언어는 영어 영상을 사용합니다.",
    captionsNote: "음성 설명, 화면 핵심 자막, 선택 가능한 WebVTT 자막이 포함됩니다.",
    accountTitle: "계속 사용할 수 있는 두 가지 로그인",
    accountBody: "이메일 코드나 8자 이상 비밀번호를 같은 계정에서 사용할 수 있습니다.",
    privacyTitle: "안전한 녹화",
    privacyBody: "실제 이메일, 비밀번호, 확인 코드는 표시되지 않으며 테스트 회원 정보도 가려집니다.",
    homeLink: "홈으로",
    startLink: "무료 학습 시작",
  },
  fr: {
    ...en,
    metaTitle: "Guide vidéo de démarrage",
    homeAction: "Voir le guide de 10 minutes",
    eyebrow: "SMARTLINGO · PREMIERS PAS",
    title: "Découvrez le parcours visiteur et membre en dix minutes.",
    intro: "Essayez les fonctions essentielles sans compte, puis découvrez la progression, les scores, les cours, la communauté et les réglages d’un membre.",
    duration: "10 minutes · narration anglaise · sous-titres inclus",
    visitorLabel: "PREMIÈRE PARTIE · VISITEUR",
    visitorTitle: "Essayez SmartLingo avant de vous inscrire",
    visitorBody: "Découvrez Apprendre, le Sprint du jour, SmartCards, Défi, conversation quotidienne, Communauté, cours, académies et les deux méthodes d’inscription.",
    memberLabel: "DEUXIÈME PARTIE · MEMBRE",
    memberTitle: "Reprenez votre progression enregistrée",
    memberBody: "Consultez le tableau de bord, les scores, le calendrier, les cours, la communauté, les messages et la sécurité avec un membre test masqué.",
    watchLabel: "Lire le guide SmartLingo",
    mediaNote: "La page chinoise utilise la vidéo chinoise. Toutes les autres langues utilisent cette version anglaise.",
    captionsNote: "La vidéo comprend une narration, des légendes intégrées et une piste WebVTT sélectionnable.",
    accountTitle: "Deux modes d’accès durables",
    accountBody: "Utilisez un code e-mail ou un mot de passe de huit caractères pour le même compte.",
    privacyTitle: "Enregistrement sécurisé",
    privacyBody: "Aucun e-mail, mot de passe ni code réel n’apparaît et l’identité test est masquée.",
    homeLink: "Retour à l’accueil",
    startLink: "Commencer gratuitement",
  },
  de: {
    ...en,
    metaTitle: "Video-Einführung",
    homeAction: "10-Minuten-Einführung ansehen",
    eyebrow: "SMARTLINGO · ERSTE SCHRITTE",
    title: "Die gesamte Besucher- und Mitgliederreise in zehn Minuten.",
    intro: "Testen Sie die Kernfunktionen ohne Konto und sehen Sie anschließend gespeicherten Fortschritt, Punkte, Kurse, Community und Einstellungen.",
    duration: "10 Minuten · englische Sprachausgabe · mit Untertiteln",
    visitorLabel: "TEIL EINS · BESUCHER",
    visitorTitle: "SmartLingo vor der Anmeldung testen",
    visitorBody: "Lernen, Tages-Sprint, SmartCards, Challenge, Alltagssprechen, Community, Kurse, Akademien und beide Registrierungswege kennenlernen.",
    memberLabel: "TEIL ZWEI · MITGLIED",
    memberTitle: "Mit gespeichertem Fortschritt fortfahren",
    memberBody: "Dashboard, Punkteverlauf, Lernkalender, Kurse, Community, Nachrichten und Kontosicherheit mit einem geschützten Testkonto ansehen.",
    watchLabel: "SmartLingo-Einführung abspielen",
    mediaNote: "Die chinesische Seite nutzt das chinesische Video. Alle anderen Oberflächensprachen nutzen diese englische Version.",
    captionsNote: "Enthält Sprachausgabe, eingeblendete Kernaussagen und eine auswählbare WebVTT-Untertitelspur.",
    accountTitle: "Zwei dauerhafte Anmeldewege",
    accountBody: "E-Mail-Code oder Passwort mit mindestens acht Zeichen führen zum selben Konto.",
    privacyTitle: "Sichere Aufzeichnung",
    privacyBody: "Es erscheinen keine echten E-Mails, Passwörter oder Codes; die Testidentität ist verdeckt.",
    homeLink: "Zur Startseite",
    startLink: "Kostenlos starten",
  },
  ru: {
    ...en,
    metaTitle: "Видео для первого знакомства",
    homeAction: "Посмотреть 10-минутный обзор",
    eyebrow: "SMARTLINGO · ПЕРВОЕ ЗНАКОМСТВО",
    title: "Весь путь гостя и участника за десять минут.",
    intro: "Попробуйте основные функции без аккаунта, затем посмотрите сохранение прогресса, баллов, курсов, сообщества и настроек.",
    duration: "10 минут · английская озвучка · с субтитрами",
    visitorLabel: "ЧАСТЬ ПЕРВАЯ · ГОСТЬ",
    visitorTitle: "Попробуйте SmartLingo до регистрации",
    visitorBody: "Обзор обучения, Спринта дня, SmartCards, испытания, разговорной практики, сообщества, курсов, колледжей и двух способов регистрации.",
    memberLabel: "ЧАСТЬ ВТОРАЯ · УЧАСТНИК",
    memberTitle: "Продолжайте с сохранённого места",
    memberBody: "Панель, история баллов, календарь, курсы, сообщество, сообщения и безопасность показаны через скрытый тестовый аккаунт.",
    watchLabel: "Воспроизвести обзор SmartLingo",
    mediaNote: "На китайской странице используется китайское видео, на остальных языках интерфейса — английское.",
    captionsNote: "Есть озвучка, ключевые подписи на экране и выбираемая дорожка WebVTT.",
    accountTitle: "Два постоянных способа входа",
    accountBody: "Код из письма и пароль от восьми символов работают с одним аккаунтом.",
    privacyTitle: "Безопасная запись",
    privacyBody: "Настоящие адреса, пароли и коды не показываются; тестовая личность скрыта.",
    homeLink: "На главную",
    startLink: "Начать бесплатно",
  },
  it: {
    ...en,
    metaTitle: "Video guida iniziale",
    homeAction: "Guarda il tour di 10 minuti",
    eyebrow: "SMARTLINGO · PRIMI PASSI",
    title: "Scopri in dieci minuti il percorso completo di visitatore e membro.",
    intro: "Prova le funzioni principali senza account, poi scopri progressi, punteggi, corsi, comunità e impostazioni salvati.",
    duration: "10 minuti · narrazione inglese · sottotitoli inclusi",
    visitorLabel: "PRIMA PARTE · VISITATORE",
    visitorTitle: "Prova SmartLingo prima di iscriverti",
    visitorBody: "Esplora apprendimento, Sprint di oggi, SmartCards, sfida, conversazione quotidiana, comunità, corsi, college e due metodi di registrazione.",
    memberLabel: "SECONDA PARTE · MEMBRO",
    memberTitle: "Continua dai progressi salvati",
    memberBody: "Guarda dashboard, storico punti, calendario, corsi, comunità, messaggi e sicurezza con un account di prova protetto.",
    watchLabel: "Riproduci il tour SmartLingo",
    mediaNote: "La pagina cinese usa il video cinese; tutte le altre lingue dell’interfaccia usano questa versione inglese.",
    captionsNote: "Include narrazione, didascalie chiave integrate e una traccia WebVTT selezionabile.",
    accountTitle: "Due modalità di accesso permanenti",
    accountBody: "Codice e-mail o password di otto caratteri accedono allo stesso account.",
    privacyTitle: "Registrazione sicura",
    privacyBody: "Non compaiono e-mail, password o codici reali e l’identità di prova è nascosta.",
    homeLink: "Torna alla home",
    startLink: "Inizia gratis",
  },
  pt: {
    ...en,
    metaTitle: "Vídeo de primeiros passos",
    homeAction: "Ver o tour de 10 minutos",
    eyebrow: "SMARTLINGO · PRIMEIROS PASSOS",
    title: "Veja a jornada completa de visitante e membro em dez minutos.",
    intro: "Teste os recursos essenciais sem conta e veja como um membro salva progresso, pontuações, cursos, comunidade e configurações.",
    duration: "10 minutos · narração em inglês · legendas incluídas",
    visitorLabel: "PARTE UM · VISITANTE",
    visitorTitle: "Teste o SmartLingo antes de entrar",
    visitorBody: "Conheça Aprender, Sprint de hoje, SmartCards, Desafio, conversação diária, Comunidade, cursos, academias e as duas opções de cadastro.",
    memberLabel: "PARTE DOIS · MEMBRO",
    memberTitle: "Continue com o progresso salvo",
    memberBody: "Veja painel, histórico, calendário, cursos, comunidade, mensagens e segurança com um membro de teste protegido.",
    watchLabel: "Reproduzir o tour do SmartLingo",
    mediaNote: "A página chinesa usa o vídeo chinês; os demais idiomas da interface usam esta versão em inglês.",
    captionsNote: "Inclui narração, textos principais na tela e uma faixa WebVTT selecionável.",
    accountTitle: "Duas formas permanentes de acesso",
    accountBody: "Código por e-mail ou senha de oito caracteres levam à mesma conta.",
    privacyTitle: "Gravação segura",
    privacyBody: "Nenhum e-mail, senha ou código real aparece; a identidade de teste está oculta.",
    homeLink: "Voltar ao início",
    startLink: "Começar grátis",
  },
  ar: {
    ...en,
    metaTitle: "فيديو البدء لأول مرة",
    homeAction: "شاهد الجولة في 10 دقائق",
    eyebrow: "SMARTLINGO · دليل البداية",
    title: "تعرّف إلى رحلة الزائر والعضو كاملة خلال عشر دقائق.",
    intro: "جرّب أدوات التعلم دون حساب، ثم شاهد كيف يحفظ العضو التقدم والنتائج والدورات والمجتمع والإعدادات.",
    duration: "10 دقائق · تعليق صوتي إنجليزي · ترجمة متاحة",
    visitorLabel: "الجزء الأول · زائر",
    visitorTitle: "جرّب SmartLingo قبل التسجيل",
    visitorBody: "استكشف التعلم وسباق اليوم وSmartCards والتحدي والمحادثة اليومية والمجتمع والدورات والكليات وطريقتي التسجيل.",
    memberLabel: "الجزء الثاني · عضو",
    memberTitle: "تابع من التقدم المحفوظ",
    memberBody: "شاهد لوحة التحكم وسجل النقاط والتقويم والدورات والمجتمع والرسائل والأمان من خلال حساب اختبار محمي.",
    watchLabel: "تشغيل جولة SmartLingo",
    mediaNote: "تستخدم الصفحة الصينية الفيديو الصيني، وتستخدم بقية لغات الواجهة النسخة الإنجليزية.",
    captionsNote: "يتضمن الفيديو تعليقًا صوتيًا ونصوصًا أساسية ومسار WebVTT قابلًا للاختيار.",
    accountTitle: "طريقتان دائمتان للدخول",
    accountBody: "رمز البريد أو كلمة مرور من ثمانية أحرف يصلان إلى الحساب نفسه.",
    privacyTitle: "تسجيل آمن",
    privacyBody: "لا يظهر بريد أو كلمة مرور أو رمز حقيقي، كما تُخفى هوية الاختبار.",
    homeLink: "العودة للرئيسية",
    startLink: "ابدأ مجانًا",
  },
  hi: {
    ...en,
    metaTitle: "पहली बार का वीडियो मार्गदर्शन",
    homeAction: "10 मिनट का शुरुआती टूर देखें",
    eyebrow: "SMARTLINGO · शुरुआती मार्गदर्शन",
    title: "दस मिनट में विज़िटर और सदस्य की पूरी यात्रा देखें।",
    intro: "बिना खाते के मुख्य सीखने के साधन आज़माएँ, फिर सदस्य की सहेजी प्रगति, अंक, पाठ्यक्रम, समुदाय और सेटिंग देखें।",
    duration: "10 मिनट · अंग्रेज़ी आवाज़ · कैप्शन सहित",
    visitorLabel: "भाग एक · विज़िटर",
    visitorTitle: "जुड़ने से पहले SmartLingo आज़माएँ",
    visitorBody: "सीखना, आज का स्प्रिंट, SmartCards, चुनौती, दैनिक बोलचाल, समुदाय, पाठ्यक्रम, कॉलेज और दोनों साइन-अप विकल्प देखें।",
    memberLabel: "भाग दो · सदस्य",
    memberTitle: "सहेजी प्रगति से आगे बढ़ें",
    memberBody: "सुरक्षित टेस्ट सदस्य से डैशबोर्ड, अंक इतिहास, कैलेंडर, पाठ्यक्रम, समुदाय, संदेश और खाता सुरक्षा देखें।",
    watchLabel: "SmartLingo शुरुआती टूर चलाएँ",
    mediaNote: "चीनी पेज चीनी वीडियो चलाता है; बाकी इंटरफ़ेस भाषाएँ अंग्रेज़ी संस्करण चलाती हैं।",
    captionsNote: "वीडियो में आवाज़, स्क्रीन पर मुख्य कैप्शन और चुनने योग्य WebVTT ट्रैक है।",
    accountTitle: "दो स्थायी साइन-इन विकल्प",
    accountBody: "ईमेल कोड या कम से कम आठ अक्षरों का पासवर्ड एक ही खाते में काम करता है।",
    privacyTitle: "सुरक्षित रिकॉर्डिंग",
    privacyBody: "कोई असली ईमेल, पासवर्ड या कोड नहीं दिखता और टेस्ट पहचान छिपी रहती है।",
    homeLink: "होम पर लौटें",
    startLink: "मुफ़्त सीखना शुरू करें",
  },
} satisfies Record<InterfaceLanguage, SmartLingoTutorialCopy>;

export function smartLingoTutorialCopyFor(language: InterfaceLanguage) {
  return smartLingoTutorialCopies[language];
}

export function smartLingoTutorialMediaFor(language: InterfaceLanguage) {
  const narrationLanguage = language === "zh" ? "zh" : "en";
  return {
    narrationLanguage,
    video: `/tutorials/smartlingo-first-time-tour-${narrationLanguage}.mp4`,
    poster: `/tutorials/smartlingo-first-time-tour-${narrationLanguage}-poster.png`,
    captions: `/tutorials/smartlingo-first-time-tour-${narrationLanguage}.vtt`,
  } as const;
}
