/** Scene-specific source briefs for the nine remaining everyday places. */
export type EverydayExtraBriefPair = readonly [questionEn: string, answerEn: string, questionZh: string, answerZh: string];

export const SMARTLINGO_EVERYDAY_EXTRA_LEVEL_BRIEFS: Record<
  "airport" | "hotel" | "restaurant" | "hospital" | "school" | "library" | "pharmacy" | "bank" | "police",
  Record<"intermediate" | "advanced", readonly EverydayExtraBriefPair[]>
> = {
  airport: {
    intermediate: [
      ["Where are you flying, and do you have a booking reference?", "I am flying to Rome. The reference is on my phone.", "您飞往哪里？有订票编号吗？", "我飞往罗马，订票编号在手机里。"],
      ["May I see the passport that matches the booking?", "Yes, here it is. My surname is Lee.", "可以看一下与订票信息一致的护照吗？", "可以，在这里。我姓李。"],
      ["You have one checked bag. Would you like to add another?", "No, just this suitcase. Is it within the weight limit?", "您有一件托运行李，还要增加吗？", "不用，就这个行李箱。它没有超重吧？"],
      ["It is within the limit. Do you have any liquids in your carry-on?", "Yes, a small bottle. Should I put it in a separate bag?", "没有超重。您的随身行李里有液体吗？", "有一小瓶，需要单独装袋吗？"],
      ["Please check the security rules before you join the line. Do you need directions?", "Yes. Where is the security entrance for this terminal?", "排队前请查看安检规定。需要指路吗？", "需要。这个航站楼的安检入口在哪里？"],
      ["Your boarding gate is B12. Would you like an aisle or window seat?", "An aisle seat, if one is available without an extra fee.", "您的登机口是 B12。想要靠过道还是靠窗的座位？", "如果不用加钱，我想要靠过道的座位。"],
      ["An aisle seat is available. Should I print the boarding pass?", "Yes, please. Could you also show me the boarding time?", "有靠过道的座位。要打印登机牌吗？", "要，谢谢。也请告诉我登机时间。"],
      ["Boarding begins at six ten. Do you have enough time to reach the gate?", "I think so. About how long is the walk from security?", "六点十分开始登机，您有足够时间走到登机口吗？", "应该有。过了安检还要走多久？"],
      ["It is about fifteen minutes. Would you like the quickest route?", "Yes, please point out the signs I should follow.", "大约十五分钟。需要知道最快的路线吗？", "需要，请指出我该跟着哪些指示牌走。"],
      ["Your bag tag and boarding pass are ready. Is the destination correct?", "Yes, both say Rome. Thank you; I will go to security now.", "行李牌和登机牌都好了，目的地正确吗？", "对，两个都写着罗马。谢谢，我现在去安检。"],
    ],
    advanced: [
      ["Your flight to Rome has been canceled. Would you like us to look for another flight?", "Yes. I need to arrive tomorrow morning if possible.", "您飞往罗马的航班取消了，要帮您找别的航班吗？", "要。如果可能，我需要明天早上到达。"],
      ["There is a flight tonight with a connection in Paris. Would that work?", "Possibly. How long is the connection, and is my checked bag transferred?", "今晚有一班在巴黎转机的航班，可以吗？", "有可能。转机时间多久？我的托运行李会直挂吗？"],
      ["The connection is only forty minutes. Would you prefer a longer one?", "Yes. I do not want to risk missing the second flight.", "转机只有四十分钟，您想换一班转机时间更长的吗？", "想。我不想冒险错过第二段航班。"],
      ["A later connection gives you two hours but arrives at noon. Which option do you want?", "I will take the two-hour connection. Please confirm the arrival time.", "另一班有两小时转机时间，但中午才到。您选哪班？", "我选两小时转机的那班。请确认到达时间。"],
      ["It arrives at twelve fifteen. Do you still want us to rebook you?", "Yes. Will there be any additional fare for this change?", "十二点十五分到达。仍要改签吗？", "要。这样改签需要补票价吗？"],
      ["I will check the fare rules before you agree. Can you wait a moment?", "Of course. Please do not cancel my original booking until the replacement is confirmed.", "我先核对票价规则，您稍等一下好吗？", "当然。新航班确认前，请不要取消我原来的预订。"],
      ["There is no extra fare. Shall I confirm the new itinerary?", "Yes. Please include both flight numbers in the confirmation.", "不用补差价，要确认新行程吗？", "要，请在确认信息里列出两段航班号。"],
      ["Your bag is already checked. Shall I verify its new routing?", "Yes. Please make sure the bag tag shows Rome as the final destination.", "您的行李已经托运了，要核对新的行李路线吗？", "要，请确认行李牌的最终目的地是罗马。"],
      ["The bag tag is correct, and the first flight leaves from gate C4. Need directions?", "Yes. Please show me where to collect the new boarding passes first.", "行李牌正确，第一段从 C4 登机口出发。需要指路吗？", "需要。请先告诉我到哪里领取新的登机牌。"],
      ["Here are both boarding passes. Is there anything else to verify?", "No. I have the itinerary, bag tag, and both boarding passes. Thank you.", "两张登机牌在这里。还有什么需要核对吗？", "没有了。行程、行李牌和两张登机牌我都有了，谢谢。"],
    ],
  },
  hotel: {
    intermediate: [
      ["Welcome. What name is the reservation under?", "It is under Lee for three nights, starting today.", "欢迎，预订用的是什么姓名？", "姓李，从今天开始住三晚。"],
      ["I found your reservation. Would you like one bed or two?", "One bed, please. Is a quiet room available?", "找到预订了。您要一张床还是两张床？", "一张床。还有安静一点的房间吗？"],
      ["We have a room away from the elevator. Would you like it?", "Yes. Does it cost the same as my booking?", "有一间远离电梯的房间，您要吗？", "要。价格和我预订的一样吗？"],
      ["The price is the same. When do you plan to check out?", "On Friday morning. What time is checkout?", "价格一样。您计划什么时候退房？", "周五早上。退房时间是几点？"],
      ["Checkout is at eleven. Do you need breakfast tomorrow?", "Yes. Is breakfast included in my room rate?", "十一点退房。明早要吃早餐吗？", "要。房费包含早餐吗？"],
      ["It is included. Would you like two room keys?", "Yes, two keys, please. Where is the breakfast room?", "包含早餐。需要两张房卡吗？", "需要两张。早餐厅在哪里？"],
      ["It is on the ground floor. Do you need help with your luggage?", "No, thank you. Is there an elevator near my room?", "早餐厅在一楼。需要帮您搬行李吗？", "不用，谢谢。我的房间附近有电梯吗？"],
      ["Yes. Your room is 406. Would you like directions?", "Yes, please. I have not been to this hotel before.", "有。您的房间是 406。需要指路吗？", "需要，我以前没来过这家酒店。"],
      ["Take the elevator to floor four, then turn left. Is that clear?", "Yes. If I need another towel, should I call reception?", "乘电梯到四楼再左转，清楚吗？", "清楚。如果还需要毛巾，我该打电话给前台吗？"],
      ["Yes, call reception at any time. Anything else before you go up?", "No, thank you. My room and breakfast are confirmed.", "是的，随时可以打给前台。上楼前还有事吗？", "没有了，谢谢。房间和早餐都确认好了。"],
    ],
    advanced: [
      ["I am sorry, the quiet room you reserved is not ready yet. Would you like another room?", "Maybe. How is the other room different, and when will mine be ready?", "抱歉，您订的安静房间还没准备好。要换一间吗？", "也许。另一间有什么不同？我订的房间何时能好？"],
      ["The other room is beside the elevator. Your room should be ready in an hour. Which do you prefer?", "I will wait an hour. Can you store my suitcase meanwhile?", "另一间在电梯旁；您的房间预计一小时后就好。您选哪种？", "我等一小时。这段时间能帮我寄存行李箱吗？"],
      ["Yes. May I attach a claim tag to your suitcase?", "Yes, and please give me the matching claim ticket.", "可以。能给您的行李箱挂一张寄存牌吗？", "可以，也请给我对应的取件凭证。"],
      ["The room is ready now, but the air conditioner has been reported as noisy. Shall we check it?", "Yes. I would rather check before accepting the room.", "房间现在好了，但空调有人反映有噪音。要先检查吗？", "要。我想验看后再接受这间房。"],
      ["You are right; it is noisy. Would you accept a quieter room on another floor?", "Yes, if it has the same bed type and does not cost more.", "您说得对，确实有噪音。换到另一层的安静房间可以吗？", "可以，条件是床型一样，而且不加价。"],
      ["That room has the same bed and price. Would you like me to move your booking?", "Yes. Please keep my original checkout date and included breakfast.", "那间床型和价格都一样。要改到那间吗？", "要。请保留原来的退房日期和含早餐的安排。"],
      ["I have updated the booking. Can I confirm the new room number?", "Yes, please. I also need to know whether my old key was canceled.", "预订已经更新，可以核对新房号吗？", "可以。也请确认旧房卡是否已经停用。"],
      ["Your new room is 518, and the old key is disabled. Do you need a new key?", "Yes, two new keys, please. I will return the old ones.", "新房号是 518，旧房卡已停用。需要新房卡吗？", "需要两张新房卡。我会交回旧卡。"],
      ["Would you like us to deliver your stored suitcase to room 518?", "Yes. Could you confirm it using my claim ticket first?", "需要我们把寄存的行李送到 518 房吗？", "需要。能先用我的取件凭证核对吗？"],
      ["The suitcase and updated receipt are ready. Is everything correct?", "Yes. The room, price, checkout date, and luggage are all correct.", "行李和更新后的收据都好了，内容正确吗？", "正确。房间、价格、退房日期和行李都对了。"],
    ],
  },
  restaurant: {
    intermediate: [
      ["Do you have a reservation, or would you like a table now?", "A table for two now, if one is available.", "您有预订，还是现在需要座位？", "如果有位子，现在要两人桌。"],
      ["We have a table by the window. Does that suit you?", "Yes, thank you. Could we see the menu?", "窗边有一桌，可以吗？", "可以，谢谢。能给我们看看菜单吗？"],
      ["The lunch special comes with soup or salad. Which would you like?", "Soup, please. What kind is it today?", "午间套餐配汤或沙拉，您选哪种？", "要汤。今天是什么汤？"],
      ["It is tomato soup. Are you ready to order the main dish?", "Almost. Does the chicken dish contain peanuts?", "是番茄汤。主菜可以点了吗？", "快好了。鸡肉这道菜里有花生吗？"],
      ["I will check with the kitchen. Do you need to avoid peanuts entirely?", "Yes. Please ask about the ingredients and preparation before I order.", "我去问厨房。您需要完全避开花生吗？", "是的。点菜前请确认食材和制作方式。"],
      ["The kitchen cannot confirm that dish is peanut-free. Would you like another option?", "Yes. Please show me a dish the kitchen can confirm for me.", "厨房无法确认那道菜不含花生。要换一道吗？", "要。请推荐厨房能够确认的菜。"],
      ["They can prepare the plain grilled fish separately. Would you like that?", "Yes, with rice and no sauce, please.", "他们可以单独制作原味烤鱼，您要吗？", "要，请配米饭，不要酱汁。"],
      ["Would you like drinks while you wait?", "Two glasses of water without ice, please.", "等餐时要喝点什么吗？", "请给我们两杯不加冰的水。"],
      ["Here are the fish and rice. Is this what you ordered?", "Yes, thank you. Could we have the bill after the meal?", "烤鱼和米饭来了，是您点的吗？", "是的，谢谢。吃完后能给我们账单吗？"],
      ["Of course. Will you pay together or separately?", "Together by card, please. An itemized bill would help.", "当然。一起付还是分开付？", "一起刷卡。请给我们明细账单。"],
    ],
    advanced: [
      ["I am sorry; the kitchen served you the dish with sauce. Should I take it back?", "Yes, please. I ordered it without sauce because of an allergy concern.", "抱歉，厨房给您的菜加了酱汁。要我撤走吗？", "要。我因过敏顾虑要求不加酱汁。"],
      ["Would you like us to remove the sauce and return the same plate?", "No. Please ask the kitchen whether they can prepare a new dish separately.", "要我们把酱汁去掉，再把这盘送回来吗？", "不要。请问厨房能否单独重新做一份。"],
      ["The kitchen can make a new plate, but it will take twenty minutes. Is that acceptable?", "Yes. Please confirm the ingredients again before starting.", "厨房可以重做，但要二十分钟。可以吗？", "可以。开始做之前请再核对一次食材。"],
      ["They confirmed the ingredients. Do you want your companion's dish kept warm?", "Yes, please. We would like to eat together.", "他们确认了食材。要帮您的同伴把餐点保温吗？", "要，谢谢。我们想一起吃。"],
      ["The replacement is ready. Would you like me to describe how it was prepared?", "Yes. Please tell me whether a separate pan and utensils were used.", "重做的餐点好了，需要我说明制作过程吗？", "需要。请告诉我是否用了单独的锅具和餐具。"],
      ["The kitchen used separate equipment, but cannot guarantee an allergen-free environment. Do you still want it?", "Thank you for being clear. I will not eat it; please remove it from the bill.", "厨房用了单独器具，但无法保证环境完全无过敏原。您还要吗？", "谢谢您说明清楚。我不吃这道了，请从账单中去掉。"],
      ["I understand. Would you like to keep your drinks and your companion's meal?", "Yes, please. We will pay for those items.", "明白。饮料和您同伴的餐点还保留吗？", "保留。我们会支付这些项目。"],
      ["The bill still includes the returned dish. Shall I correct it now?", "Yes. Please show me the corrected itemized bill before charging my card.", "账单还包含退回的菜。要现在更正吗？", "要。刷卡前请让我看更正后的明细账单。"],
      ["The corrected total covers only the drinks and one meal. Is that right?", "Yes. Please charge this card and give me a receipt.", "更正后只包含饮料和一份餐点，对吗？", "对。请刷这张卡，并给我收据。"],
      ["Here is your receipt. Is there anything else we can do?", "No, thank you. I appreciate the clear explanation and corrected bill.", "这是收据，还需要我们做什么吗？", "不用了，谢谢。感谢您说明清楚并更正账单。"],
    ],
  },
  hospital: {
    intermediate: [
      ["Do you have an appointment today?", "Yes, at two o'clock. It is under Lee.", "您今天有预约吗？", "有，两点钟，预约姓名是李。"],
      ["May I confirm your date of birth privately?", "Yes. Please let me know where I can give that information.", "可以私下核对您的出生日期吗？", "可以。请告诉我在哪里提供这项信息。"],
      ["What brings you in today?", "I have had a cough and fever since yesterday.", "今天因为什么来就诊？", "从昨天起我一直咳嗽、发烧。"],
      ["Have the symptoms changed since you booked the visit?", "Yes. The fever is higher today, and I would like the clinician to know.", "预约后症状有变化吗？", "有，今天烧得更高了。我想让医护人员知道。"],
      ["Do you need an interpreter for the appointment?", "Yes, a Chinese interpreter would help me explain clearly.", "就诊时需要翻译吗？", "需要。中文翻译能帮我把情况说清楚。"],
      ["Do you have any allergies the clinician should know about?", "Yes, I have a medication allergy. I will describe it to the clinician.", "有没有需要告知医护人员的过敏情况？", "有，我对一种药物过敏。我会向医护人员说明。"],
      ["Would you like to write down your symptoms while you wait?", "Yes. I also want to note when they started.", "等候时要把症状写下来吗？", "要。我还想写下症状开始的时间。"],
      ["The clinician is running fifteen minutes late. Can you wait?", "Yes. Please tell me if the waiting time changes again.", "医护人员大约晚十五分钟，可以等吗？", "可以。如果等候时间再变，请告诉我。"],
      ["The clinician is ready. Do you have your symptom notes?", "Yes, here they are. I would like to ask about the next steps.", "医护人员可以接诊了。您带着症状记录吗？", "带了，在这里。我还想问问下一步怎么办。"],
      ["Would you like the follow-up instructions in writing?", "Yes, please. I want to check them again at home.", "需要书面的后续安排吗？", "需要。我想回家后再核对。"],
    ],
    advanced: [
      ["Your appointment appears under a different patient name. Shall I check the record?", "Yes. Please verify my identity privately before changing anything.", "您的预约显示为另一个患者姓名，要我查一下吗？", "要。修改任何内容前，请私下核对我的身份。"],
      ["The birth date also does not match. Would you like me to stop this check-in?", "Yes. Please do not attach today's visit to the wrong record.", "出生日期也不符，要先暂停登记吗？", "要。请不要把今天的就诊记到错误的病历里。"],
      ["I found a second record that may be yours. May I ask registration staff to review it?", "Yes, but please do not merge the records until they confirm they are mine.", "还找到一份可能属于您的记录，要请登记人员核查吗？", "要，但确认前请不要合并两份病历。"],
      ["The registration team confirmed the correct record. Is the listed allergy accurate?", "No. That allergy entry is missing; please ask the clinician to review it with me.", "登记人员确认了正确的病历。上面记录的过敏信息准确吗？", "不准确，漏了一项。请让医护人员和我一起核对。"],
      ["Would you like an interpreter before discussing the allergy?", "Yes. I do not want to guess at the medicine names.", "讨论过敏信息前需要翻译吗？", "需要。我不想猜测药物名称。"],
      ["The interpreter is available by video. Is that acceptable?", "Yes, as long as we can speak privately with the clinician.", "可以通过视频连线翻译，可以吗？", "可以，只要能和医护人员私下交流。"],
      ["Your appointment time has passed while we corrected the record. Shall I ask about the wait?", "Yes. Please tell me whether I am still on today's schedule.", "核对病历期间过了预约时间，要我问一下等候情况吗？", "要。请确认我今天还能按安排就诊。"],
      ["You are still on the schedule, but there is a thirty-minute wait. Can you stay?", "Yes. Please alert the care team if my reported symptoms need earlier attention.", "您还在今天的名单上，但要等三十分钟，可以吗？", "可以。如果我报告的症状需要更快处理，请通知医护团队。"],
      ["The clinician has reviewed your symptoms and is ready now. Shall I take you in?", "Yes. I have my symptom timeline and the allergy information ready.", "医护人员已看过您的症状，现在可以接诊。要带您进去吗？", "要。我准备好了症状时间线和过敏信息。"],
      ["The visit is complete. Would you like the corrected record and follow-up plan confirmed?", "Yes. Please give me the written plan and tell me whom to contact with questions.", "就诊结束了，要确认更正的病历和后续安排吗？", "要。请给我书面安排，并告诉我有疑问时联系谁。"],
    ],
  },
  school: {
    intermediate: [
      ["Are you here for the language course orientation?", "Yes. I enrolled in the morning course and need my timetable.", "您是来参加语言课程说明会的吗？", "是的。我报名了上午的课程，需要课程表。"],
      ["Your first class is on Tuesday. Can you attend at nine?", "Yes. How early should I arrive on the first day?", "第一节课是周二，九点能来吗？", "能。第一天需要提前多久到？"],
      ["Please arrive fifteen minutes early. Do you know the classroom?", "Not yet. Which building and room should I go to?", "请提前十五分钟到。您知道教室吗？", "还不知道。我该去哪个楼、哪个教室？"],
      ["It is room 12 in the north building. Do you have your student card?", "Yes, but I am not sure where to scan it.", "在北楼的 12 号教室。您有学生证吗？", "有，但我不确定在哪里刷卡。"],
      ["Scan it at the entrance. Have you received the course materials?", "I have the book, but I cannot open the online exercises.", "在入口刷卡。您收到课程资料了吗？", "书收到了，但我打不开线上练习。"],
      ["I can check your course access. Which email did you use to enroll?", "I can show it to you privately on my phone.", "我可以核查课程访问权限。报名时用了哪个邮箱？", "我可以私下在手机上给您看。"],
      ["Your access is active now. Can you open the first exercise?", "Yes, it loads. Is the homework due before Tuesday?", "您的权限现在已开通。第一份练习能打开吗？", "能打开。作业要在周二前交吗？"],
      ["No, it is due after the first class. Do you need a study partner?", "That would help. Is there a beginner study group?", "不用，第一节课后才到期。需要学习伙伴吗？", "需要。有初级学习小组吗？"],
      ["Yes, the group meets on Thursday. Would you like the details?", "Yes, please send me the time and room number.", "有，学习小组周四见。需要详细信息吗？", "需要，请把时间和房号给我。"],
      ["Your timetable and study-group details are ready. Anything unclear?", "No. I know where to go and how to access the exercises.", "课程表和小组信息都好了，还有哪里不清楚吗？", "没有了。我知道去哪里上课，也知道怎么打开练习了。"],
    ],
    advanced: [
      ["Your timetable shows a class that overlaps your required placement interview. Did you notice?", "Yes. I need to keep the interview. Can we resolve the class conflict?", "课程表上的课与必需的分级访谈冲突，您注意到了吗？", "注意到了。我需要参加访谈，能解决上课冲突吗？"],
      ["There is another section, but it meets later. Would that work?", "Possibly. Is the teacher and course level the same?", "有另一个班次，但上课时间更晚，可以吗？", "可能可以。教师和课程等级一样吗？"],
      ["The level is the same, but the teacher is different. Do you need both schedules?", "Yes. Please compare the times before changing my enrollment.", "等级一样，但老师不同。要看两份课表吗？", "要。更改报名之前请先比较时间。"],
      ["The later section starts at four and has one open seat. Shall I hold it?", "Yes, temporarily. When will the hold expire?", "晚班四点开始，还有一个空位。要暂时保留吗？", "要，先暂时保留。保留到什么时候？"],
      ["The hold lasts until tomorrow at noon. Do you need accessibility support for that room?", "Yes. Please confirm that I can reach the room by elevator.", "保留到明天中午。那个教室需要无障碍设施吗？", "需要。请确认可以乘电梯到那个教室。"],
      ["The room is accessible. Would you like the later section confirmed now?", "Yes. Please make sure my completed exercises remain on my account.", "那个教室有无障碍通道。现在确认晚班吗？", "确认。请确保已完成的练习仍保留在我的账号里。"],
      ["The transfer is complete, but the online page still shows your old section. Shall I check?", "Yes. I do not want to submit homework to the wrong section.", "转班完成了，但线上页面仍显示原班次。要我查吗？", "要。我不想把作业交到错误的班次。"],
      ["The system is updating. Can you wait a few minutes before submitting?", "Yes. Please tell me how I can confirm the change myself.", "系统正在更新。提交前能等几分钟吗？", "可以。请告诉我怎么自己确认更改。"],
      ["The new section now appears, and your earlier work is still there. Is it correct?", "Yes. The level, schedule, and completed exercises are all correct.", "新班次显示出来了，之前的练习也还在。对吗？", "对。等级、课表和已完成的练习都正确。"],
      ["Would you like written confirmation of the transfer?", "Yes. Please include the new teacher, room, and first class date.", "需要转班的书面确认吗？", "需要。请写上新老师、教室和第一节课日期。"],
    ],
  },
  library: {
    intermediate: [
      ["What book are you trying to find?", "I need an introductory history book for my course.", "您想找什么书？", "我需要一本课程用的历史入门书。"],
      ["Do you know the title or the author's name?", "I have the title on my reading list. Can I show you?", "您知道书名或作者吗？", "阅读清单上有书名，我可以给您看吗？"],
      ["This edition is on the second floor. Do you want to borrow it?", "Yes. Is it available today?", "这一版在二楼，您想借吗？", "想。今天能借到吗？"],
      ["One copy is available. Do you have a library card?", "Yes, here it is. How long may I keep the book?", "还有一本可借。您有借书证吗？", "有，在这里。这本书能借多久？"],
      ["You can keep it for three weeks. Does that cover your assignment?", "Yes. Can I renew it online if I need more time?", "可以借三周，够完成作业吗？", "够。如果需要更久，能在线续借吗？"],
      ["You may renew it if no one has reserved it. Do you need a study space?", "Yes. Is there a quiet area near the books?", "如果没人预约就能续借。还需要学习座位吗？", "需要。书架附近有安静的学习区吗？"],
      ["There is a quiet room on the same floor. Would you like directions?", "Yes, and please tell me whether drinks are allowed there.", "同一层有安静的自习室，要我指路吗？", "要。也请告诉我那里能不能带饮料。"],
      ["Water with a lid is allowed. Would you like to check out the book first?", "Yes. Please scan my card and the book.", "可以带有盖子的水。要先办理借书吗？", "要。请刷我的卡和这本书。"],
      ["Your due date is the twenty-first. Would you like a receipt?", "Yes. I will keep it with the reading list.", "归还日期是二十一号，需要凭条吗？", "需要。我会和阅读清单放在一起。"],
      ["The book is checked out. Do you know how to reach the quiet room?", "Yes, thank you. I have the book and the due date.", "借书办好了，您知道怎么去自习室吗？", "知道，谢谢。书和归还日期我都有了。"],
    ],
    advanced: [
      ["The edition your course requires is checked out. Would another edition work?", "I am not sure. Can we compare the publication years and chapters?", "课程指定的版本已借出，其他版本可以吗？", "我不确定。能比较出版年份和章节吗？"],
      ["The older edition is missing two chapters. Would you like a digital copy of the required edition?", "Yes, if my library card gives me access to those chapters.", "旧版少了两章。您要查看指定版本的电子版吗？", "要，前提是我的借书证有权限查看那些章节。"],
      ["The digital license is full today. Should I place a hold on the printed copy?", "Yes. Please tell me my place in the queue and the estimated wait.", "今天电子版的借阅名额已满。要预约纸质版吗？", "要。请告诉我排在第几位，以及预计要等多久。"],
      ["You are third in line, and the wait may be two weeks. When is your assignment due?", "It is due next week, so I need another legal way to read the chapters.", "您排第三，可能要等两周。作业何时到期？", "下周到期，所以我需要其他合规的阅读方式。"],
      ["We can request an interlibrary loan. Would you like me to check its arrival date?", "Yes, please. I need to know whether it can arrive before Friday.", "可以申请馆际互借，要查预计到达日期吗？", "要。请查能否在周五前到。"],
      ["That copy should arrive on Thursday. Shall I submit the request?", "Yes. Please keep the hold as a backup until the loan is confirmed.", "那本预计周四到，要提交申请吗？", "要。馆际互借确认前，请保留原来的预约。"],
      ["The request was accepted. Would you like a notification when it arrives?", "Yes. Please use my account notification, not an open message at the desk.", "申请已受理。到馆时需要通知吗？", "需要。请通过我的账户通知，不要在服务台公开留言。"],
      ["Your account shows a small fee from an older loan. Should I explain it?", "Yes. Please show me which loan it belongs to before I pay.", "您的账户有一笔旧借阅的小额费用，要我说明吗？", "要。付款前请告诉我它对应哪次借阅。"],
      ["It belongs to a late return from last month. Would you like an itemized record?", "Yes, please. I want to compare it with my return receipt.", "是上个月逾期归还产生的。需要明细记录吗？", "需要。我想和还书凭条核对。"],
      ["I have printed the record and your new loan request. Is anything missing?", "No. I have the request, queue position, and fee record. Thank you.", "借阅记录和新申请都打印好了，还缺什么吗？", "不缺了。申请、排队顺序和费用记录都有了，谢谢。"],
    ],
  },
  pharmacy: {
    intermediate: [
      ["How can the pharmacist help you today?", "I have a headache and want to ask about an over-the-counter medicine.", "今天需要药剂师帮您什么？", "我头痛，想咨询一种非处方药。"],
      ["Before I get the pharmacist, when did your headache begin?", "This morning. I would like to describe my symptoms to the pharmacist.", "叫药剂师来之前，请问头痛什么时候开始的？", "今天早上。我想向药剂师说明症状。"],
      ["Are you taking any other medicine?", "Yes. I have the names on my phone for the pharmacist to check.", "您正在服用其他药吗？", "有。我把药名存在手机里，想请药剂师核对。"],
      ["Do you have any medication allergies?", "Yes. Please ask the pharmacist to review my allergy before I buy anything.", "您对药物过敏吗？", "有。买药前请让药剂师核对我的过敏情况。"],
      ["Would you like to speak with the pharmacist privately?", "Yes, please. I have a question about the medicine I already take.", "需要私下和药剂师谈谈吗？", "需要。我想问问目前服用的药。"],
      ["The pharmacist can meet you now. Do you have the package with you?", "Yes. Here is the package, and I can show the label.", "药剂师现在有空。您带着药盒吗？", "带了，在这里。我可以给他看标签。"],
      ["The pharmacist has explained the options. Do you want the smaller package?", "Yes, if the label matches the option we discussed.", "药剂师解释了几种选择。您要小包装吗？", "要，前提是标签与刚才讨论的那种一致。"],
      ["Would you like the written directions printed larger?", "Yes, please. I want to read them clearly at home.", "需要大字版的书面说明吗？", "需要，谢谢。我想回家后看清楚。"],
      ["Do you understand when to ask for more help?", "Not fully. Could the pharmacist explain the warning signs again?", "您明白什么时候需要进一步求助吗？", "还不完全明白。能请药剂师再解释一下需要注意的症状吗？"],
      ["Would you like a receipt with the product name?", "Yes. I will keep it with the written instructions.", "需要标有产品名称的收据吗？", "需要。我会和书面说明放在一起。"],
    ],
    advanced: [
      ["The medicine you requested is out of stock. Would you like a substitute?", "Possibly, but I want the pharmacist to check it against my allergy and current medicines.", "您要的药缺货了，想换一种吗？", "可能可以，但我想请药剂师核对我的过敏情况和正在服用的药。"],
      ["One substitute has a different active ingredient. Shall I ask the pharmacist to explain?", "Yes. Please do not treat it as the same medicine without that review.", "一种替代品的有效成分不同，要请药剂师解释吗？", "要。未经核查，请不要当作同一种药。"],
      ["The pharmacist would like to know the names of your current medicines. Can you share them privately?", "Yes. I will show the packages in the consultation area.", "药剂师需要知道您正在服用的药名，能私下提供吗？", "可以。我会在咨询区给他看药盒。"],
      ["The pharmacist recommends contacting your prescriber before switching. Would you like help finding the number?", "Yes. Please let me contact the prescriber before I decide.", "药剂师建议换药前联系开药医生，需要帮您找电话号码吗？", "需要。我想先联系开药医生，再决定。"],
      ["The prescriber has not answered yet. Would you like us to reserve the substitute?", "Yes, only as a reservation. I do not want to buy or use it before the advice is confirmed.", "开药医生还没接电话，要先帮您留一份替代品吗？", "可以，但只保留。我想确认建议后再购买或使用。"],
      ["Your original medicine may be available at another branch. Shall I check its stock?", "Yes. Please confirm the exact product and package size before I travel there.", "另一家分店可能有原来的药，要查库存吗？", "要。去之前请确认准确的品名和包装规格。"],
      ["That branch has the exact product, but only one package. Would you like it held?", "Yes. How long will they hold it, and what time do they close?", "那家分店有同款，但只剩一盒。要请他们预留吗？", "要。他们能留多久？几点关门？"],
      ["They will hold it until six. Can you collect it by then?", "Yes. Please give me the branch address and reservation number.", "可以留到六点，您能在那之前取吗？", "能。请给我分店地址和预留编号。"],
      ["The product label shows the same strength. Would you like the pharmacist to confirm it once more?", "Yes. I want to verify the name, strength, and directions together.", "标签上的剂量规格相同，要请药剂师再确认一次吗？", "要。我想一起核对品名、规格和用法说明。"],
      ["Everything matches your original package. Do you still have questions?", "No. I have the reservation details and will follow the pharmacist's confirmed directions.", "与原来的药盒完全一致，还有问题吗？", "没有了。我有预留信息，会按药剂师确认的说明办理。"],
    ],
  },
  bank: {
    intermediate: [
      ["What would you like to do at the bank today?", "I would like to open a checking account and learn about its fees.", "今天来银行要办理什么？", "我想开一个活期账户，并了解费用。"],
      ["May I verify your identification at the private desk?", "Yes. Please tell me which documents are required.", "可以在私密柜台核对您的证件吗？", "可以。请告诉我需要哪些证件。"],
      ["This document is accepted. Do you also need a debit card?", "Yes. Is there a monthly card fee?", "这份证件可以使用。您还需要借记卡吗？", "需要。借记卡有月费吗？"],
      ["There is no card fee, but the account may have a monthly fee. Would you like the details?", "Yes. Please explain when that fee applies.", "卡没有费用，但账户可能有月费。要了解细节吗？", "要。请说明什么情况下收月费。"],
      ["The fee depends on the account balance. Do you want the written schedule?", "Yes, please. I want to compare it before signing.", "月费取决于账户余额。需要书面收费表吗？", "需要。我想签字前比较一下。"],
      ["Would you like to add money to the new account today?", "Yes, two hundred dollars. May I see the deposit amount before confirming?", "今天要往新账户存钱吗？", "要，存两百美元。确认前能让我核对存款金额吗？"],
      ["The deposit shows two hundred dollars. Is that correct?", "Yes. Please give me a deposit receipt.", "存款显示两百美元，正确吗？", "对。请给我存款凭条。"],
      ["Would you like to set up online banking?", "Yes. Please show me how to do it on my own device.", "需要开通网上银行吗？", "需要。请教我在自己的设备上操作。"],
      ["Your application is complete. Where should we send the card?", "Please use the address I provided on the form. Can I verify it first?", "申请完成了。卡寄到哪里？", "请寄到表格上填写的地址。我能先核对一下吗？"],
      ["The address is correct. Do you need a copy of the account terms?", "Yes. I will keep the terms and the deposit receipt.", "地址正确。需要一份账户条款吗？", "需要。我会留好条款和存款凭条。"],
    ],
    advanced: [
      ["You say your card was charged twice for one purchase. Shall I review the transactions?", "Yes. Please check both entries without reading my account details aloud.", "您说一次购物被刷了两笔，要核对交易吗？", "要。请核查两笔记录，但不要大声念出我的账户资料。"],
      ["One charge is pending and the other is posted. Do you have the merchant receipt?", "Yes. The receipt shows only one payment. Here is a copy.", "一笔待处理，另一笔已入账。您有商家收据吗？", "有。收据只显示一次付款。这是副本。"],
      ["A pending charge may disappear, but I cannot promise that. Would you like to monitor it or start a review?", "Please start a review and explain the expected timeline in writing.", "待处理的交易可能会消失，但我不能保证。您想观察还是申请调查？", "请申请调查，并书面说明预计处理时间。"],
      ["We can open a dispute for the posted charge. Shall I confirm the transaction date and amount?", "Yes. Please read back only the date and amount, not my full card number.", "我们可以针对已入账交易提出争议。要核对日期和金额吗？", "要。请只复述日期和金额，不要念完整卡号。"],
      ["The date and amount match your receipt. Do you also think the card is compromised?", "I am not sure. What are my options for temporarily locking the card?", "日期和金额与收据一致。您认为卡也可能被盗用了吗？", "我不确定。暂时锁卡有哪些选择？"],
      ["You can lock it in the app or request a replacement. Which would you prefer now?", "I will lock it in my app now. Please show me where to find the control.", "可以在应用里锁卡或申请换卡。现在您选哪种？", "我现在先在应用里锁卡。请告诉我在哪里操作。"],
      ["The app shows the card is locked. Do you still need a replacement?", "Yes. Please explain how I can receive a new card securely.", "应用显示卡已锁定。还要换卡吗？", "要。请说明如何安全地收到新卡。"],
      ["A replacement can be mailed to your verified address. Would you like to check that address privately?", "Yes, please. I will verify it at the private desk.", "新卡可以寄到已核实的地址。要私下核对地址吗？", "要。我会在私密柜台核对。"],
      ["The dispute and replacement request are recorded. Would you like reference numbers?", "Yes. Please provide both numbers and the next update date in writing.", "争议申请和换卡请求已登记。需要受理编号吗？", "需要。请书面给我两个编号和下次更新日期。"],
      ["Here is the written summary. Does it match what we agreed?", "Yes. The disputed charge, locked card, and replacement are all listed.", "这是书面摘要，与我们商定的一致吗？", "一致。争议交易、锁卡和换卡都列明了。"],
    ],
  },
  police: {
    intermediate: [
      ["Are you safe, and what would you like to report?", "I am safe. I lost my phone on the bus this afternoon.", "您现在安全吗？要报告什么事？", "我安全。今天下午我把手机落在公交车上了。"],
      ["Which bus route were you on?", "Route 24, heading toward Central Station.", "您坐的是哪路公交？", "开往中央车站的 24 路。"],
      ["About what time did you last have the phone?", "Around three o'clock, just before I got off.", "您最后一次拿着手机大约是什么时候？", "大约三点，下车前不久。"],
      ["Can you describe the phone and its case?", "It is black with a red case and a cracked corner.", "能描述一下手机和手机壳吗？", "黑色手机、红色手机壳，边角有裂纹。"],
      ["Have you contacted the bus company's lost-property office?", "Not yet. Do you have the number or website?", "您联系过公交公司的失物招领处吗？", "还没有。有他们的电话或网址吗？"],
      ["I can give you the contact details. Do you need an interpreter for the report?", "Yes, a Chinese interpreter would help me explain the details.", "我可以给您联系方式。报案时需要翻译吗？", "需要。中文翻译能帮我说清楚细节。"],
      ["Would you like to give a safe way for us to contact you?", "Yes. I will provide a different phone number privately.", "您愿意提供一个安全的联系方式吗？", "愿意。我会私下提供另一个电话号码。"],
      ["The report is ready. Would you like to review the time and route?", "Yes. Please correct the route to 24 before I sign.", "报告写好了，要核对时间和线路吗？", "要。签字前请把线路改成 24 路。"],
      ["The route is corrected. Would you like the report reference number?", "Yes, please write it down for me.", "线路已更正。需要报案编号吗？", "需要，请帮我写下来。"],
      ["Do you know what to do if the phone is found?", "I will use the reference number when I contact the lost-property office.", "知道找到手机后该怎么处理吗？", "我联系失物招领处时会提供报案编号。"],
    ],
    advanced: [
      ["You said your phone is missing, but the report marks it as stolen. Would you like that reviewed?", "Yes. I do not know whether it was stolen; please record only what I observed.", "您说手机不见了，但报告写成了被盗。要核对吗？", "要。我不知道是否被盗，请只记录我亲眼所见。"],
      ["What did you observe before the phone went missing?", "I had it when I boarded the bus, then could not find it after I got off.", "手机不见前您观察到了什么？", "上车时手机还在，下车后就找不到了。"],
      ["Did anyone threaten you or take it in front of you?", "No. I did not see anyone take it, and I am safe now.", "有人威胁您，或当面拿走手机吗？", "没有。我没看到有人拿走，现在也安全。"],
      ["Do you have a location update from the phone?", "Yes, but it may not be exact. I can show it without going there myself.", "手机有定位更新吗？", "有，但位置可能不准确。我可以展示定位，不会自己去那里。"],
      ["Please do not go to that location alone. Would you like us to note the information?", "Yes. Please record the time and location shown on my device.", "请不要独自去那个地点。要我们记下定位信息吗？", "要。请记录设备显示的时间和地点。"],
      ["The earlier report also has the wrong bus route. What is the correct route?", "It was route 24 toward Central Station, not route 42.", "先前报告里的公交线路也错了。正确线路是什么？", "是开往中央车站的 24 路，不是 42 路。"],
      ["I have corrected the route and changed 'stolen' to 'missing.' May I read the summary back?", "Yes. Please include that I did not see anyone take the phone.", "我改好了线路，并把“被盗”改为“不见”。可以复述摘要吗？", "可以。请写明我没有亲眼看到有人拿走手机。"],
      ["Does this revised summary accurately reflect your statement?", "Yes. Please tell me how to receive a copy before I sign.", "修改后的摘要准确反映了您的陈述吗？", "准确。签字前请告诉我如何拿到副本。"],
      ["You can receive a copy and a report number. Do you have a secure contact method?", "Yes. I will provide an alternate number privately.", "您可以拿到副本和报案编号。有安全的联系方式吗？", "有。我会私下提供另一个号码。"],
      ["Here are the corrected report and number. Do you need the lost-property contact details?", "Yes, please. I will follow up using this number and the corrected report.", "这是更正后的报告和编号。需要失物招领处的联系方式吗？", "需要。我会用这个编号和更正后的报告跟进。"],
    ],
  },
};
