import { getDatabase, getSessionUser } from "@/lib/auth";
import { isBootstrapAdminEmail } from "@/lib/admin-access";

const FEATURES=["sprint","smartcard_practice","smartcard_challenge","course"] as const;
const LEVELS=["beginner","intermediate","advanced"] as const;

async function admin(request:Request){const user=await getSessionUser(request);return user&&isBootstrapAdminEmail(user.email)?user:null;}
export async function GET(request:Request){if(!await admin(request))return Response.json({error:"Permanent administrator access required"},{status:403});const result=await getDatabase().prepare(`SELECT id,feature,level,minimum_score AS minimumScore,reward_points AS rewardPoints,status,updated_at AS updatedAt FROM smartlingo_learning_reward_rules ORDER BY feature,level,minimum_score`).run();return Response.json({rules:result.results||[]});}
export async function PATCH(request:Request){const user=await admin(request);if(!user)return Response.json({error:"Permanent administrator access required"},{status:403});const body=await request.json().catch(()=>null)as{rules?:Array<{id?:unknown;feature?:unknown;level?:unknown;minimumScore?:unknown;rewardPoints?:unknown;status?:unknown}>}|null;if(!Array.isArray(body?.rules)||!body.rules.length||body.rules.length>100)return Response.json({error:"One to 100 reward rules are required"},{status:400});const now=Math.floor(Date.now()/1000),statements=[];for(const rule of body.rules){const feature=String(rule.feature||""),level=String(rule.level||""),minimumScore=Number(rule.minimumScore),rewardPoints=Number(rule.rewardPoints),status=rule.status==="disabled"?"disabled":"active";if(!FEATURES.includes(feature as never)||!LEVELS.includes(level as never)||![60,80,95].includes(minimumScore)||!Number.isInteger(rewardPoints)||rewardPoints<0||rewardPoints>100000)return Response.json({error:"Invalid reward rule"},{status:400});statements.push(getDatabase().prepare(`UPDATE smartlingo_learning_reward_rules SET reward_points=?,status=?,updated_by_user_id=?,updated_at=? WHERE feature=? AND level=? AND minimum_score=?`).bind(rewardPoints,status,user.id,now,feature,level,minimumScore));}await getDatabase().batch(statements);return Response.json({updated:statements.length});}
