import { headers } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { AdminMemberRoleEditor } from "../../../../../components/AdminMemberRoleEditor";
import { SiteFooter } from "../../../../../components/SiteFooter";
import { SiteHeader } from "../../../../../components/SiteHeader";
import { isAdmin, isBootstrapAdminEmail } from "../../../../../lib/admin-access";
import { getDatabase, getSessionUser } from "../../../../../lib/auth";
import "../../admin.css";

export const dynamic="force-dynamic";
type Detail={id:string;email:string;displayName:string;preferredLanguage:string;role:"member"|"admin";createdAt:number;joinedClasses:number;ownedClasses:number;paidPayments:number};
export default async function AdminMemberDetail({params}:{params:Promise<{lang:string;memberId:string}>}){const{lang,memberId}=await params;if(lang!=="en"&&lang!=="zh")notFound();const incoming=await headers();const admin=await getSessionUser(new Request("https://smartlingo.net",{headers:{cookie:incoming.get("cookie")??""}}));if(!admin)redirect(`/${lang}/auth/login?returnTo=/${lang}/admin/members/${encodeURIComponent(memberId)}`);if(!isAdmin(admin))redirect(`/${lang}/dashboard`);const member=await getDatabase().prepare("SELECT u.id,u.email,u.display_name AS displayName,u.preferred_language AS preferredLanguage,u.role,u.created_at AS createdAt,(SELECT COUNT(*) FROM smartlingo_language_class_members cm WHERE cm.user_id=u.id AND cm.status='active') AS joinedClasses,(SELECT COUNT(*) FROM smartlingo_language_classes c WHERE c.owner_user_id=u.id) AS ownedClasses,(SELECT COUNT(*) FROM smartlingo_platform_subscription_payments p WHERE p.subscriber_user_id=u.id AND p.status='paid') AS paidPayments FROM users u WHERE u.id=? LIMIT 1").bind(memberId).first<Detail>();if(!member)notFound();const zh=lang==="zh";return <main><SiteHeader lang={lang}/><div className="admin-shell" data-layout-page="admin-member-detail" data-layout-fill="admin-shell"><div className="admin-toolbar"><div><p className="section-kicker">{zh?"会员档案":"MEMBER PROFILE"}</p><h1>{member.displayName}</h1><p>{member.email}</p></div><a href={`/${lang}/admin/members`}>← {zh?"返回会员列表":"Back to members"}</a></div><div className="admin-detail-grid"><section className="admin-detail-card"><h2>{zh?"账户概览":"Account overview"}</h2><dl><div><dt>{zh?"平台角色":"Role"}</dt><dd>{member.role==="admin"?(zh?"管理员":"Admin"):(zh?"会员":"Member")}</dd></div><div><dt>{zh?"界面语言":"Language"}</dt><dd>{member.preferredLanguage}</dd></div><div><dt>{zh?"加入日期":"Joined"}</dt><dd>{new Date(member.createdAt*1000).toLocaleDateString(zh?"zh-CN":"en-US")}</dd></div><div><dt>{zh?"加入班级":"Joined classes"}</dt><dd>{member.joinedClasses}</dd></div><div><dt>{zh?"创建班级":"Owned classes"}</dt><dd>{member.ownedClasses}</dd></div><div><dt>{zh?"平台付费记录":"Paid subscriptions"}</dt><dd>{member.paidPayments}</dd></div></dl></section><aside className="admin-detail-card"><h2>{zh?"角色管理":"Role management"}</h2><p>{zh?"角色变更立即影响管理权限，并由服务器执行验证。":"Role changes affect admin access immediately and are validated by the server."}</p><AdminMemberRoleEditor memberId={member.id} initialRole={member.role} lang={lang} locked={isBootstrapAdminEmail(member.email)||member.id===admin.id}/></aside></div></div><SiteFooter lang={lang}/></main>}
