import { classAccess, classByCode } from "@/lib/live-classrooms";
import { getDatabase, getSessionUser } from "@/lib/auth";

type R2Object={body:ReadableStream;size:number;httpMetadata?:{contentType?:string};range?:{offset?:number;length?:number}};
type R2Bucket={get(key:string,options?:{range?:{offset:number;length:number}}):Promise<R2Object|null>};

export async function GET(request:Request,{params}:{params:Promise<{code:string;id:string}>}){
  const {code,id}=await params,room=await classByCode(code);if(!room)return new Response("Not found",{status:404});const user=await getSessionUser(request),access=await classAccess(room,user);if(!access.allowed)return new Response("Class access required",{status:user?403:401});const item=await getDatabase().prepare("SELECT r2_key AS r2Key,content_type AS contentType,file_size_bytes AS size FROM class_playlist_items WHERE id=? AND room_id=? AND source_type='upload'").bind(id,room.id).first<{r2Key:string;contentType:string;size:number}>();if(!item?.r2Key)return new Response("Not found",{status:404});const {env}=await import("cloudflare:workers");const bucket=env.CLASS_FILES as unknown as R2Bucket|undefined;if(!bucket)return new Response("Storage unavailable",{status:503});const range=request.headers.get("range");let offset=0,length=item.size,status=200,contentRange="";if(range){const match=/bytes=(\d+)-(\d*)/.exec(range);if(match){offset=Math.min(Number(match[1]),Math.max(0,item.size-1));const end=match[2]?Math.min(Number(match[2]),item.size-1):item.size-1;length=Math.max(1,end-offset+1);status=206;contentRange=`bytes ${offset}-${offset+length-1}/${item.size}`;}}const object=await bucket.get(item.r2Key,status===206?{range:{offset,length}}:undefined);if(!object)return new Response("Not found",{status:404});return new Response(object.body,{status,headers:{"content-type":item.contentType||"video/mp4","content-length":String(length),"accept-ranges":"bytes",...(contentRange?{"content-range":contentRange}:{})}});
}
