import Link from "next/link";
import { notFound } from "next/navigation";
import { GameLanguagePicker } from "../../../components/GameLanguagePicker";
import { SiteFooter } from "../../../components/SiteFooter";
import { SiteHeader } from "../../../components/SiteHeader";
import { SMARTLINGO_LANGUAGE_COMMUNITIES, isSmartLingoCommunityLanguage } from "../../../lib/smartlingo-language-communities";

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }) { const { lang } = await params; return { title: lang === "zh" ? "游戏 · SmartLingo" : "Play · SmartLingo" }; }

export default async function PlayPage({ params, searchParams }: { params: Promise<{ lang: string }>; searchParams: Promise<{ language?: string }> }) {
  const value = await params; if (value.lang !== "en" && value.lang !== "zh") notFound();
  const lang = value.lang; const zh = lang === "zh"; const query = await searchParams;
  const language = query.language && isSmartLingoCommunityLanguage(query.language) ? query.language : undefined;
  const selected = SMARTLINGO_LANGUAGE_COMMUNITIES.find(item => item.code === language);
  const gameTiles = <section className="game-tiles"><Link href={`/${lang}/smartcards/starter-${language}`}><small>01 · SMART CARD PRACTICE</small><strong>{zh ? "智慧卡练习" : "Smart Card Practice"}</strong><em>{zh ? "看词、选义、开口说 · 自由练习" : "See it, choose it, say it · practice freely"}</em><b>{zh ? "开始练习" : "Start practice"} →</b></Link><Link href={`/${lang}/play/challenge?language=${language}`}><small>02 · SMART CARD CHALLENGE</small><strong>{zh ? "智慧卡挑战" : "Smart Card Challenge"}</strong><em>{zh ? "每日赛程、最高分与排行榜" : "Daily rounds, top scores, and rankings"}</em><b>{zh ? "查看挑战日历" : "Open challenge calendar"} →</b></Link></section>;
  return <main className="lingo-play-hub"><SiteHeader lang={lang}/><section className="play-hero"><p>PLAY · SPEAK · GROW</p><h1>{zh ? "边玩边学，每一分都算数。" : "Learn through play. Make every point count."}</h1><span>{selected ? (zh ? `已选择${selected.nameZh}。点游戏即可直接开始。` : `${selected.nameEn} selected. Choose a game to begin.`) : (zh ? "先选择想学习的语言，再开始游戏。" : "Choose the language you want to learn, then start playing.")}</span></section>{language ? gameTiles : <GameLanguagePicker lang={lang} basePath={`/${lang}/play`}/>}<SiteFooter lang={lang}/><style>{`.lingo-play-hub{min-height:100vh;background:radial-gradient(circle at 80% 5%,#bbffe2,transparent 28%),#f7f3ea;color:#153129}.play-hero,.game-tiles{width:min(1180px,calc(100% - 36px));margin:auto}.play-hero{padding:clamp(70px,10vw,120px) 0 45px}.play-hero>p{color:#087d62;font-size:12px;font-weight:950;letter-spacing:.15em}.play-hero h1{max-width:940px;margin:12px 0 20px;font:600 clamp(48px,8vw,92px)/.98 "Iowan Old Style","Noto Serif SC",serif}.play-hero>span{display:block;color:#597069;font-size:18px}.game-tiles{margin-bottom:100px;display:grid;grid-template-columns:1fr 1fr;gap:16px}.game-tiles a{min-height:310px;padding:clamp(27px,4vw,45px);display:flex;flex-direction:column;border-radius:28px;background:linear-gradient(145deg,#123f35,#087d62);color:#fff;text-decoration:none;box-shadow:0 24px 60px #163c3028;transition:transform .2s}.game-tiles a:nth-child(2){background:linear-gradient(145deg,#372453,#7555a6)}.game-tiles a:hover{transform:translateY(-4px)}.game-tiles small{color:#8ff0cf;font-weight:900}.game-tiles strong{margin:45px 0 12px;font-size:clamp(32px,5vw,52px)}.game-tiles em{color:#c8e9de;font-style:normal}.game-tiles b{margin-top:auto}@media(max-width:720px){.game-tiles{grid-template-columns:1fr}.game-tiles a{min-height:270px}}`}</style></main>;
}
