import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CollegeCard } from "../../../components/CollegeCard";
import { JoinCollegeByCode } from "../../../components/JoinCollegeByCode";
import { SiteFooter } from "../../../components/SiteFooter";
import { SiteHeader } from "../../../components/SiteHeader";
import { requestUser } from "../../../lib/request-user";
import { activeCollegeTags, colleges } from "../../../lib/smartlingo-colleges";

export const dynamic="force-dynamic";
export default async function CollegesPage({params,searchParams}:{params:Promise<{lang:string}>;searchParams:Promise<{q?:string;tag?:string;access?:string;view?:string}>}){
  const{lang}=await params;if(lang!=="en"&&lang!=="zh"&&lang!=="es"&&lang!=="ja"&&lang!=="ko"&&lang!=="fr"&&lang!=="de"&&lang!=="ru"&&lang!=="it"&&lang!=="pt"&&lang!=="ar"&&lang!=="hi")notFound();const zh=lang==="zh",query=await searchParams,user=await requestUser(),mine=query.view==="mine";
  if(mine&&!user)redirect(`/${lang}/auth/login?returnTo=${encodeURIComponent(`/${lang}/colleges?view=mine`)}`);
  const[items,tags]=await Promise.all([colleges({query:query.q,tag:query.tag,access:query.access,userId:user?.id,mine}),activeCollegeTags()]);
  return <main className="college-directory-page" data-layout-page="colleges"><SiteHeader lang={lang}/><section className="college-directory-hero" data-layout-fill="college-directory-hero"><p className="section-kicker">COLLEGES</p><h1>{zh?"选择学院":"Choose College"}</h1><p>{zh?"输入学院编号直达，或按名称、标签和访问类型浏览学院与课程表。":"Enter a college number, or browse college course tables by name, tag, and access type."}</p><JoinCollegeByCode lang={lang}/><div className="college-directory-actions"><Link className="primary-button" href={`/${lang}/colleges`}>{zh?"浏览学院":"Browse colleges"}</Link><Link className="secondary-button" href={`/${lang}/colleges?view=mine`}>{zh?"我的学院":"My colleges"}</Link>{user?.email.toLowerCase()==="bingliu@cybeye.com"?<Link className="secondary-button" href={`/${lang}/college/create`}>＋ {zh?"创建学院":"Create college"}</Link>:null}</div></section><section className="college-browser"><form className="college-filter-bar"><label><span className="sr-only">{zh?"搜索学院":"Search colleges"}</span><input type="search" name="q" defaultValue={query.q||""} placeholder={zh?"搜索学院名称或编号":"Search name or number"}/></label><select name="tag" defaultValue={query.tag||""} aria-label={zh?"学院标签":"College tag"}><option value="">{zh?"全部标签":"All tags"}</option>{tags.map(tag=><option key={tag.id} value={tag.slug}>{zh?tag.nameZh:tag.nameEn}</option>)}</select><select name="access" defaultValue={query.access||""} aria-label={zh?"访问类型":"Access type"}><option value="">{zh?"全部类型":"All types"}</option><option value="public">{zh?"公开学院":"Open college"}</option><option value="trial">{zh?"推荐学院":"Referred college"}</option><option value="private">{zh?"专属学院":"Private college"}</option></select>{mine?<input type="hidden" name="view" value="mine"/>:null}<button>{zh?"搜索":"Search"}</button></form><nav className="college-tag-links">{tags.map(tag=><Link key={tag.id} href={`/${lang}/colleges?tag=${tag.slug}`}>{zh?tag.nameZh:tag.nameEn}</Link>)}</nav><div className="college-card-grid">{items.map(college=><CollegeCard key={college.id} college={college} lang={lang}/>)}</div>{!items.length?<p className="college-empty">{zh?"没有符合条件的学院。":"No colleges match these filters."}</p>:null}</section><SiteFooter lang={lang}/></main>;
}
